
//input ports
add mapped point clk clk -type PI PI
add mapped point rst rst -type PI PI

//output ports
add mapped point debug_reg_r4[31] debug_reg_r4[31] -type PO PO
add mapped point debug_reg_r4[30] debug_reg_r4[30] -type PO PO
add mapped point debug_reg_r4[29] debug_reg_r4[29] -type PO PO
add mapped point debug_reg_r4[28] debug_reg_r4[28] -type PO PO
add mapped point debug_reg_r4[27] debug_reg_r4[27] -type PO PO
add mapped point debug_reg_r4[26] debug_reg_r4[26] -type PO PO
add mapped point debug_reg_r4[25] debug_reg_r4[25] -type PO PO
add mapped point debug_reg_r4[24] debug_reg_r4[24] -type PO PO
add mapped point debug_reg_r4[23] debug_reg_r4[23] -type PO PO
add mapped point debug_reg_r4[22] debug_reg_r4[22] -type PO PO
add mapped point debug_reg_r4[21] debug_reg_r4[21] -type PO PO
add mapped point debug_reg_r4[20] debug_reg_r4[20] -type PO PO
add mapped point debug_reg_r4[19] debug_reg_r4[19] -type PO PO
add mapped point debug_reg_r4[18] debug_reg_r4[18] -type PO PO
add mapped point debug_reg_r4[17] debug_reg_r4[17] -type PO PO
add mapped point debug_reg_r4[16] debug_reg_r4[16] -type PO PO
add mapped point debug_reg_r4[15] debug_reg_r4[15] -type PO PO
add mapped point debug_reg_r4[14] debug_reg_r4[14] -type PO PO
add mapped point debug_reg_r4[13] debug_reg_r4[13] -type PO PO
add mapped point debug_reg_r4[12] debug_reg_r4[12] -type PO PO
add mapped point debug_reg_r4[11] debug_reg_r4[11] -type PO PO
add mapped point debug_reg_r4[10] debug_reg_r4[10] -type PO PO
add mapped point debug_reg_r4[9] debug_reg_r4[9] -type PO PO
add mapped point debug_reg_r4[8] debug_reg_r4[8] -type PO PO
add mapped point debug_reg_r4[7] debug_reg_r4[7] -type PO PO
add mapped point debug_reg_r4[6] debug_reg_r4[6] -type PO PO
add mapped point debug_reg_r4[5] debug_reg_r4[5] -type PO PO
add mapped point debug_reg_r4[4] debug_reg_r4[4] -type PO PO
add mapped point debug_reg_r4[3] debug_reg_r4[3] -type PO PO
add mapped point debug_reg_r4[2] debug_reg_r4[2] -type PO PO
add mapped point debug_reg_r4[1] debug_reg_r4[1] -type PO PO
add mapped point debug_reg_r4[0] debug_reg_r4[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point ex_wb_rd_addr[0]/q ex_wb_rd_addr_reg[0]/Q -type DFF DFF
add mapped point id_ex_rd_addr[0]/q id_ex_rd_addr_reg[0]/Q -type DFF DFF
add mapped point id_ex_rd_addr[2]/q id_ex_rd_addr_reg[2]/Q -type DFF DFF
add mapped point id_ex_reg_write/q id_ex_reg_write_reg/Q -type DFF DFF
add mapped point if_id_instr[2]/q if_id_instr_reg[2]/Q -type DFF DFF
add mapped point if_id_instr[3]/q if_id_instr_reg[3]/Q -type DFF DFF
add mapped point if_id_instr[4]/q if_id_instr_reg[4]/Q -type DFF DFF
add mapped point pc[0]/q pc_reg[0]/Q -type DFF DFF
add mapped point pc[1]/q pc_reg[1]/Q -type DFF DFF
add mapped point pc[2]/q pc_reg[2]/Q -type DFF DFF
add mapped point pc[3]/q pc_reg[3]/Q -type DFF DFF
add mapped point reg_file[1][0]/q reg_file_reg[1][0]/Q -type DFF DFF
add mapped point reg_file[1][1]/q reg_file_reg[1][1]/Q -type DFF DFF
add mapped point reg_file[1][2]/q reg_file_reg[1][2]/Q -type DFF DFF
add mapped point reg_file[1][3]/q reg_file_reg[1][3]/Q -type DFF DFF
add mapped point reg_file[1][4]/q reg_file_reg[1][4]/Q -type DFF DFF
add mapped point reg_file[1][5]/q reg_file_reg[1][5]/Q -type DFF DFF
add mapped point reg_file[1][6]/q reg_file_reg[1][6]/Q -type DFF DFF
add mapped point reg_file[1][7]/q reg_file_reg[1][7]/Q -type DFF DFF
add mapped point reg_file[1][8]/q reg_file_reg[1][8]/Q -type DFF DFF
add mapped point reg_file[1][9]/q reg_file_reg[1][9]/Q -type DFF DFF
add mapped point reg_file[1][10]/q reg_file_reg[1][10]/Q -type DFF DFF
add mapped point reg_file[1][11]/q reg_file_reg[1][11]/Q -type DFF DFF
add mapped point reg_file[1][12]/q reg_file_reg[1][12]/Q -type DFF DFF
add mapped point reg_file[1][13]/q reg_file_reg[1][13]/Q -type DFF DFF
add mapped point reg_file[1][14]/q reg_file_reg[1][14]/Q -type DFF DFF
add mapped point reg_file[1][15]/q reg_file_reg[1][15]/Q -type DFF DFF
add mapped point reg_file[1][16]/q reg_file_reg[1][16]/Q -type DFF DFF
add mapped point reg_file[1][17]/q reg_file_reg[1][17]/Q -type DFF DFF
add mapped point reg_file[1][18]/q reg_file_reg[1][18]/Q -type DFF DFF
add mapped point reg_file[1][19]/q reg_file_reg[1][19]/Q -type DFF DFF
add mapped point reg_file[1][20]/q reg_file_reg[1][20]/Q -type DFF DFF
add mapped point reg_file[1][21]/q reg_file_reg[1][21]/Q -type DFF DFF
add mapped point reg_file[1][22]/q reg_file_reg[1][22]/Q -type DFF DFF
add mapped point reg_file[1][23]/q reg_file_reg[1][23]/Q -type DFF DFF
add mapped point reg_file[1][24]/q reg_file_reg[1][24]/Q -type DFF DFF
add mapped point reg_file[1][25]/q reg_file_reg[1][25]/Q -type DFF DFF
add mapped point reg_file[1][26]/q reg_file_reg[1][26]/Q -type DFF DFF
add mapped point reg_file[1][27]/q reg_file_reg[1][27]/Q -type DFF DFF
add mapped point reg_file[1][28]/q reg_file_reg[1][28]/Q -type DFF DFF
add mapped point reg_file[1][29]/q reg_file_reg[1][29]/Q -type DFF DFF
add mapped point reg_file[1][30]/q reg_file_reg[1][30]/Q -type DFF DFF
add mapped point reg_file[1][31]/q reg_file_reg[1][31]/Q -type DFF DFF
add mapped point reg_file[4][0]/q reg_file_reg[4][0]/Q -type DFF DFF
add mapped point reg_file[4][1]/q reg_file_reg[4][1]/Q -type DFF DFF
add mapped point reg_file[4][2]/q reg_file_reg[4][2]/Q -type DFF DFF
add mapped point reg_file[4][3]/q reg_file_reg[4][3]/Q -type DFF DFF
add mapped point reg_file[4][4]/q reg_file_reg[4][4]/Q -type DFF DFF
add mapped point reg_file[4][5]/q reg_file_reg[4][5]/Q -type DFF DFF
add mapped point reg_file[4][6]/q reg_file_reg[4][6]/Q -type DFF DFF
add mapped point reg_file[4][7]/q reg_file_reg[4][7]/Q -type DFF DFF
add mapped point reg_file[4][8]/q reg_file_reg[4][8]/Q -type DFF DFF
add mapped point reg_file[4][9]/q reg_file_reg[4][9]/Q -type DFF DFF
add mapped point reg_file[4][10]/q reg_file_reg[4][10]/Q -type DFF DFF
add mapped point reg_file[4][11]/q reg_file_reg[4][11]/Q -type DFF DFF
add mapped point reg_file[4][12]/q reg_file_reg[4][12]/Q -type DFF DFF
add mapped point reg_file[4][13]/q reg_file_reg[4][13]/Q -type DFF DFF
add mapped point reg_file[4][14]/q reg_file_reg[4][14]/Q -type DFF DFF
add mapped point reg_file[4][15]/q reg_file_reg[4][15]/Q -type DFF DFF
add mapped point reg_file[4][16]/q reg_file_reg[4][16]/Q -type DFF DFF
add mapped point reg_file[4][17]/q reg_file_reg[4][17]/Q -type DFF DFF
add mapped point reg_file[4][18]/q reg_file_reg[4][18]/Q -type DFF DFF
add mapped point reg_file[4][19]/q reg_file_reg[4][19]/Q -type DFF DFF
add mapped point reg_file[4][20]/q reg_file_reg[4][20]/Q -type DFF DFF
add mapped point reg_file[4][21]/q reg_file_reg[4][21]/Q -type DFF DFF
add mapped point reg_file[4][22]/q reg_file_reg[4][22]/Q -type DFF DFF
add mapped point reg_file[4][23]/q reg_file_reg[4][23]/Q -type DFF DFF
add mapped point reg_file[4][24]/q reg_file_reg[4][24]/Q -type DFF DFF
add mapped point reg_file[4][25]/q reg_file_reg[4][25]/Q -type DFF DFF
add mapped point reg_file[4][26]/q reg_file_reg[4][26]/Q -type DFF DFF
add mapped point reg_file[4][27]/q reg_file_reg[4][27]/Q -type DFF DFF
add mapped point reg_file[4][28]/q reg_file_reg[4][28]/Q -type DFF DFF
add mapped point reg_file[4][29]/q reg_file_reg[4][29]/Q -type DFF DFF
add mapped point reg_file[4][30]/q reg_file_reg[4][30]/Q -type DFF DFF
add mapped point reg_file[4][31]/q reg_file_reg[4][31]/Q -type DFF DFF
add mapped point reg_file[5][0]/q reg_file_reg[5][0]/Q -type DFF DFF
add mapped point reg_file[5][1]/q reg_file_reg[5][1]/Q -type DFF DFF
add mapped point reg_file[5][2]/q reg_file_reg[5][2]/Q -type DFF DFF
add mapped point reg_file[5][3]/q reg_file_reg[5][3]/Q -type DFF DFF
add mapped point reg_file[5][4]/q reg_file_reg[5][4]/Q -type DFF DFF
add mapped point reg_file[5][5]/q reg_file_reg[5][5]/Q -type DFF DFF
add mapped point reg_file[5][6]/q reg_file_reg[5][6]/Q -type DFF DFF
add mapped point reg_file[5][7]/q reg_file_reg[5][7]/Q -type DFF DFF
add mapped point reg_file[5][8]/q reg_file_reg[5][8]/Q -type DFF DFF
add mapped point reg_file[5][9]/q reg_file_reg[5][9]/Q -type DFF DFF
add mapped point reg_file[5][10]/q reg_file_reg[5][10]/Q -type DFF DFF
add mapped point reg_file[5][11]/q reg_file_reg[5][11]/Q -type DFF DFF
add mapped point reg_file[5][12]/q reg_file_reg[5][12]/Q -type DFF DFF
add mapped point reg_file[5][13]/q reg_file_reg[5][13]/Q -type DFF DFF
add mapped point reg_file[5][14]/q reg_file_reg[5][14]/Q -type DFF DFF
add mapped point reg_file[5][15]/q reg_file_reg[5][15]/Q -type DFF DFF
add mapped point reg_file[5][16]/q reg_file_reg[5][16]/Q -type DFF DFF
add mapped point reg_file[5][17]/q reg_file_reg[5][17]/Q -type DFF DFF
add mapped point reg_file[5][18]/q reg_file_reg[5][18]/Q -type DFF DFF
add mapped point reg_file[5][19]/q reg_file_reg[5][19]/Q -type DFF DFF
add mapped point reg_file[5][20]/q reg_file_reg[5][20]/Q -type DFF DFF
add mapped point reg_file[5][21]/q reg_file_reg[5][21]/Q -type DFF DFF
add mapped point reg_file[5][22]/q reg_file_reg[5][22]/Q -type DFF DFF
add mapped point reg_file[5][23]/q reg_file_reg[5][23]/Q -type DFF DFF
add mapped point reg_file[5][24]/q reg_file_reg[5][24]/Q -type DFF DFF
add mapped point reg_file[5][25]/q reg_file_reg[5][25]/Q -type DFF DFF
add mapped point reg_file[5][26]/q reg_file_reg[5][26]/Q -type DFF DFF
add mapped point reg_file[5][27]/q reg_file_reg[5][27]/Q -type DFF DFF
add mapped point reg_file[5][28]/q reg_file_reg[5][28]/Q -type DFF DFF
add mapped point reg_file[5][29]/q reg_file_reg[5][29]/Q -type DFF DFF
add mapped point reg_file[5][30]/q reg_file_reg[5][30]/Q -type DFF DFF
add mapped point reg_file[5][31]/q reg_file_reg[5][31]/Q -type DFF DFF
add mapped point ex_wb_alu_result[0]/q ex_wb_alu_result_reg[0]/Q -type DFF DFF
add mapped point ex_wb_alu_result[1]/q ex_wb_alu_result_reg[1]/Q -type DFF DFF
add mapped point ex_wb_alu_result[2]/q ex_wb_alu_result_reg[2]/Q -type DFF DFF
add mapped point ex_wb_alu_result[3]/q ex_wb_alu_result_reg[3]/Q -type DFF DFF
add mapped point ex_wb_alu_result[4]/q ex_wb_alu_result_reg[4]/Q -type DFF DFF
add mapped point ex_wb_alu_result[5]/q ex_wb_alu_result_reg[5]/Q -type DFF DFF
add mapped point ex_wb_alu_result[6]/q ex_wb_alu_result_reg[6]/Q -type DFF DFF
add mapped point ex_wb_alu_result[7]/q ex_wb_alu_result_reg[7]/Q -type DFF DFF
add mapped point ex_wb_alu_result[8]/q ex_wb_alu_result_reg[8]/Q -type DFF DFF
add mapped point ex_wb_alu_result[9]/q ex_wb_alu_result_reg[9]/Q -type DFF DFF
add mapped point ex_wb_alu_result[10]/q ex_wb_alu_result_reg[10]/Q -type DFF DFF
add mapped point ex_wb_alu_result[11]/q ex_wb_alu_result_reg[11]/Q -type DFF DFF
add mapped point ex_wb_alu_result[12]/q ex_wb_alu_result_reg[12]/Q -type DFF DFF
add mapped point ex_wb_alu_result[13]/q ex_wb_alu_result_reg[13]/Q -type DFF DFF
add mapped point ex_wb_alu_result[14]/q ex_wb_alu_result_reg[14]/Q -type DFF DFF
add mapped point ex_wb_alu_result[15]/q ex_wb_alu_result_reg[15]/Q -type DFF DFF
add mapped point ex_wb_alu_result[16]/q ex_wb_alu_result_reg[16]/Q -type DFF DFF
add mapped point ex_wb_alu_result[17]/q ex_wb_alu_result_reg[17]/Q -type DFF DFF
add mapped point ex_wb_alu_result[18]/q ex_wb_alu_result_reg[18]/Q -type DFF DFF
add mapped point ex_wb_alu_result[19]/q ex_wb_alu_result_reg[19]/Q -type DFF DFF
add mapped point ex_wb_alu_result[20]/q ex_wb_alu_result_reg[20]/Q -type DFF DFF
add mapped point ex_wb_alu_result[21]/q ex_wb_alu_result_reg[21]/Q -type DFF DFF
add mapped point ex_wb_alu_result[22]/q ex_wb_alu_result_reg[22]/Q -type DFF DFF
add mapped point ex_wb_alu_result[23]/q ex_wb_alu_result_reg[23]/Q -type DFF DFF
add mapped point ex_wb_alu_result[24]/q ex_wb_alu_result_reg[24]/Q -type DFF DFF
add mapped point ex_wb_alu_result[25]/q ex_wb_alu_result_reg[25]/Q -type DFF DFF
add mapped point ex_wb_alu_result[26]/q ex_wb_alu_result_reg[26]/Q -type DFF DFF
add mapped point ex_wb_alu_result[27]/q ex_wb_alu_result_reg[27]/Q -type DFF DFF
add mapped point ex_wb_alu_result[28]/q ex_wb_alu_result_reg[28]/Q -type DFF DFF
add mapped point ex_wb_alu_result[29]/q ex_wb_alu_result_reg[29]/Q -type DFF DFF
add mapped point ex_wb_alu_result[30]/q ex_wb_alu_result_reg[30]/Q -type DFF DFF
add mapped point ex_wb_alu_result[31]/q ex_wb_alu_result_reg[31]/Q -type DFF DFF
add mapped point ex_wb_rd_addr[2]/q ex_wb_rd_addr_reg[2]/Q -type DFF DFF
add mapped point ex_wb_reg_write/q ex_wb_reg_write_reg/Q -type DFF DFF
add mapped point id_ex_data1[0]/q id_ex_data1_reg[0]/Q -type DFF DFF
add mapped point id_ex_data1[1]/q id_ex_data1_reg[1]/Q -type DFF DFF
add mapped point id_ex_data1[2]/q id_ex_data1_reg[2]/Q -type DFF DFF
add mapped point id_ex_data1[3]/q id_ex_data1_reg[3]/Q -type DFF DFF
add mapped point id_ex_data1[4]/q id_ex_data1_reg[4]/Q -type DFF DFF
add mapped point id_ex_data1[5]/q id_ex_data1_reg[5]/Q -type DFF DFF
add mapped point id_ex_data1[6]/q id_ex_data1_reg[6]/Q -type DFF DFF
add mapped point id_ex_data1[7]/q id_ex_data1_reg[7]/Q -type DFF DFF
add mapped point id_ex_data1[8]/q id_ex_data1_reg[8]/Q -type DFF DFF
add mapped point id_ex_data1[9]/q id_ex_data1_reg[9]/Q -type DFF DFF
add mapped point id_ex_data1[10]/q id_ex_data1_reg[10]/Q -type DFF DFF
add mapped point id_ex_data1[11]/q id_ex_data1_reg[11]/Q -type DFF DFF
add mapped point id_ex_data1[12]/q id_ex_data1_reg[12]/Q -type DFF DFF
add mapped point id_ex_data1[13]/q id_ex_data1_reg[13]/Q -type DFF DFF
add mapped point id_ex_data1[14]/q id_ex_data1_reg[14]/Q -type DFF DFF
add mapped point id_ex_data1[15]/q id_ex_data1_reg[15]/Q -type DFF DFF
add mapped point id_ex_data1[16]/q id_ex_data1_reg[16]/Q -type DFF DFF
add mapped point id_ex_data1[17]/q id_ex_data1_reg[17]/Q -type DFF DFF
add mapped point id_ex_data1[18]/q id_ex_data1_reg[18]/Q -type DFF DFF
add mapped point id_ex_data1[19]/q id_ex_data1_reg[19]/Q -type DFF DFF
add mapped point id_ex_data1[20]/q id_ex_data1_reg[20]/Q -type DFF DFF
add mapped point id_ex_data1[21]/q id_ex_data1_reg[21]/Q -type DFF DFF
add mapped point id_ex_data1[22]/q id_ex_data1_reg[22]/Q -type DFF DFF
add mapped point id_ex_data1[23]/q id_ex_data1_reg[23]/Q -type DFF DFF
add mapped point id_ex_data1[24]/q id_ex_data1_reg[24]/Q -type DFF DFF
add mapped point id_ex_data1[25]/q id_ex_data1_reg[25]/Q -type DFF DFF
add mapped point id_ex_data1[26]/q id_ex_data1_reg[26]/Q -type DFF DFF
add mapped point id_ex_data1[27]/q id_ex_data1_reg[27]/Q -type DFF DFF
add mapped point id_ex_data1[28]/q id_ex_data1_reg[28]/Q -type DFF DFF
add mapped point id_ex_data1[29]/q id_ex_data1_reg[29]/Q -type DFF DFF
add mapped point id_ex_data1[30]/q id_ex_data1_reg[30]/Q -type DFF DFF
add mapped point id_ex_data1[31]/q id_ex_data1_reg[31]/Q -type DFF DFF
add mapped point id_ex_data2[0]/q id_ex_data2_reg[0]/Q -type DFF DFF
add mapped point id_ex_data2[1]/q id_ex_data2_reg[1]/Q -type DFF DFF
add mapped point id_ex_data2[2]/q id_ex_data2_reg[2]/Q -type DFF DFF
add mapped point id_ex_data2[3]/q id_ex_data2_reg[3]/Q -type DFF DFF
add mapped point id_ex_data2[4]/q id_ex_data2_reg[4]/Q -type DFF DFF
add mapped point id_ex_data2[5]/q id_ex_data2_reg[5]/Q -type DFF DFF
add mapped point id_ex_data2[6]/q id_ex_data2_reg[6]/Q -type DFF DFF
add mapped point id_ex_data2[7]/q id_ex_data2_reg[7]/Q -type DFF DFF
add mapped point id_ex_data2[8]/q id_ex_data2_reg[8]/Q -type DFF DFF
add mapped point id_ex_data2[9]/q id_ex_data2_reg[9]/Q -type DFF DFF
add mapped point id_ex_data2[10]/q id_ex_data2_reg[10]/Q -type DFF DFF
add mapped point id_ex_data2[11]/q id_ex_data2_reg[11]/Q -type DFF DFF
add mapped point id_ex_data2[12]/q id_ex_data2_reg[12]/Q -type DFF DFF
add mapped point id_ex_data2[13]/q id_ex_data2_reg[13]/Q -type DFF DFF
add mapped point id_ex_data2[14]/q id_ex_data2_reg[14]/Q -type DFF DFF
add mapped point id_ex_data2[15]/q id_ex_data2_reg[15]/Q -type DFF DFF
add mapped point id_ex_data2[16]/q id_ex_data2_reg[16]/Q -type DFF DFF
add mapped point id_ex_data2[17]/q id_ex_data2_reg[17]/Q -type DFF DFF
add mapped point id_ex_data2[18]/q id_ex_data2_reg[18]/Q -type DFF DFF
add mapped point id_ex_data2[19]/q id_ex_data2_reg[19]/Q -type DFF DFF
add mapped point id_ex_data2[20]/q id_ex_data2_reg[20]/Q -type DFF DFF
add mapped point id_ex_data2[21]/q id_ex_data2_reg[21]/Q -type DFF DFF
add mapped point id_ex_data2[22]/q id_ex_data2_reg[22]/Q -type DFF DFF
add mapped point id_ex_data2[23]/q id_ex_data2_reg[23]/Q -type DFF DFF
add mapped point id_ex_data2[24]/q id_ex_data2_reg[24]/Q -type DFF DFF
add mapped point id_ex_data2[25]/q id_ex_data2_reg[25]/Q -type DFF DFF
add mapped point id_ex_data2[26]/q id_ex_data2_reg[26]/Q -type DFF DFF
add mapped point id_ex_data2[27]/q id_ex_data2_reg[27]/Q -type DFF DFF
add mapped point id_ex_data2[28]/q id_ex_data2_reg[28]/Q -type DFF DFF
add mapped point id_ex_data2[29]/q id_ex_data2_reg[29]/Q -type DFF DFF
add mapped point id_ex_data2[30]/q id_ex_data2_reg[30]/Q -type DFF DFF
add mapped point id_ex_data2[31]/q id_ex_data2_reg[31]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
