 
# Template script intended to jumpstart the user to run Modus Automatic Test Pattern Generation (ATPG) software.
 
#  Generated by Genus(TM) Synthesis Solution 21.14-s082_1
 
# Modus ATPG Script
 
#-------------------------------------------------------------------------------
# INITIALIZE VARIABLES
#-------------------------------------------------------------------------------
# "set_db workdir" is recommended to be set first to initialize where the Database is to be located
# WORKDIR Tcl variable can be used in the script to reference file locations
set_db workdir ./test_scripts;
set   WORKDIR [get_db workdir]
 
# Configure the database
set_option stdout     summary;                                # Only print a summary for each command to the terminal
                                                          # Logs contain the complete command output
set ::env(CDS_LIC_REPORT) yes
# test_checks.tcl provides check_log proc to stop script on message severity
source  $::env(Install_Dir)/bin/64bit/test_checks.tcl;    # Load test_checks.tcl from Modus installation - provides check_log below
set STOP_ON_MSG_SEV ERROR;                                # Messagee severity for check_log to stop at (ERROR, WARNING_SEVERE, WARNING)
set LOGDIR          $WORKDIR/testresults/logs;            # Location of logs for check_log
 
file delete -force $WORKDIR/tbdata;                       # Delete Test Database
file delete -force $WORKDIR/testresults;                  # Delete Test Output Files/Logs
 
 
 
#-------------------------------------------------------------------------------
# BUILD THE LOGIC MODEL
#-------------------------------------------------------------------------------
build_model \
    -cell	 d_ff \
    -techlib	 /home/install/FOUNDRY/digital/90nm/dig/lib \
    -designsource	 $WORKDIR/d_ff.test_netlist.v \
    -allowmissingmodules	 yes \
    -messagecounteach	 100 \

check_log log_build_model
 
#-------------------------------------------------------------------------------
# BUILD THE TEST MODEL
#-------------------------------------------------------------------------------
build_testmode \
    -testmode	 ASSUMED \
    -assignfile	 $WORKDIR/d_ff.ASSUMED.pinassign \
    -modedef	 test.modedef \
    -modedefpath	 $WORKDIR \
    -excludelatchfile	 $WORKDIR/test.exclude \
 
check_log log_build_testmode_ASSUMED
 
#-------------------------------------------------------------------------------
# REPORT THE TEST MODEL
#-------------------------------------------------------------------------------
report_test_structures \
    -testmode	 ASSUMED \
    -reportscanchain	 all \
 
check_log log_report_test_structures_ASSUMED
 
#-------------------------------------------------------------------------------
# VERIFY THE TEST MODEL
#-------------------------------------------------------------------------------
verify_test_structures \
    -messagecount	 TSV-016=10,TSV-024=10,TSV-315=10,TSV-027=10 \
    -testmode	 ASSUMED \
 
check_log log_verify_test_structures_ASSUMED
 
#-------------------------------------------------------------------------------
# BUILD THE FAULT MODEL
#-------------------------------------------------------------------------------
build_faultmodel \
    -includedynamic	 no \
 
check_log log_build_faultmodel
 
#-------------------------------------------------------------------------------
# ATPG - TEST GENERATION
#-------------------------------------------------------------------------------
create_logic_tests \
    -experiment	 d_ff_atpg \
    -testmode	 ASSUMED \

check_log log_create_logic_tests_ASSUMED_d_ff_atpg

#-------------------------------------------------------------------------------
# ATPG - Report Vectors
#-------------------------------------------------------------------------------
report_vectors \
    -experiment	 d_ff_atpg \
    -testmode	 ASSUMED 

check_log log_report_vectors_ASSUMED_d_ff_atpg

exit
