
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Nov  4 2025 18:44:47 IST (Nov  4 2025 13:14:47 UTC)

// Verification Directory fv/control_unit_fsm 

module control_unit_fsm(clk, rst_n, opcode, RegWrite, ALUSrc, ALUOp,
     MemRead, MemWrite, MemtoReg, Branch, SE, scan_in, scan_out);
  input clk, rst_n, SE, scan_in;
  input [3:0] opcode;
  output RegWrite, ALUSrc, MemRead, MemWrite, MemtoReg, Branch,
       scan_out;
  output [1:0] ALUOp;
  wire clk, rst_n, SE, scan_in;
  wire [3:0] opcode;
  wire RegWrite, ALUSrc, MemRead, MemWrite, MemtoReg, Branch, scan_out;
  wire [1:0] ALUOp;
  wire [3:0] state;
  wire n_0, n_1, n_2, n_3, n_5, n_6, n_8, n_9;
  wire n_11, n_12, n_15, n_16, n_17, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26;
  assign Branch = ALUOp[0];
  SDFFRHQX1 \state_reg[1] (.RN (rst_n), .CK (clk), .D (n_26), .SI
       (state[0]), .SE (SE), .Q (state[1]));
  SDFFRHQX1 \state_reg[2] (.RN (rst_n), .CK (clk), .D (n_24), .SI
       (state[1]), .SE (SE), .Q (state[2]));
  OAI211X1 g660__2398(.A0 (opcode[0]), .A1 (n_25), .B0 (n_11), .C0
       (n_23), .Y (n_26));
  SDFFRHQX1 \state_reg[3] (.RN (rst_n), .CK (clk), .D (n_22), .SI
       (state[2]), .SE (SE), .Q (scan_out));
  SDFFRHQX1 \state_reg[0] (.RN (rst_n), .CK (clk), .D (n_17), .SI
       (scan_in), .SE (SE), .Q (state[0]));
  NAND2XL g663__5107(.A (n_21), .B (n_20), .Y (n_25));
  OAI21X1 g665__6260(.A0 (n_16), .A1 (n_15), .B0 (n_23), .Y (n_24));
  AND4XL g666__4319(.A (opcode[1]), .B (opcode[0]), .C (n_21), .D
       (n_19), .Y (n_22));
  MX2X1 g669__8428(.A (n_19), .B (ALUSrc), .S0 (opcode[1]), .Y (n_20));
  OAI22X1 g668__5526(.A0 (n_16), .A1 (n_8), .B0 (scan_out), .B1 (n_9),
       .Y (n_17));
  NOR2XL g670__6783(.A (ALUSrc), .B (n_19), .Y (n_15));
  CLKINVX1 g674(.A (MemRead), .Y (n_23));
  NOR2XL g672__3680(.A (n_5), .B (n_1), .Y (RegWrite));
  NOR2XL g677__1617(.A (n_6), .B (n_12), .Y (MemRead));
  NOR2XL g676__2802(.A (state[2]), .B (n_12), .Y (n_19));
  INVXL g671(.A (ALUOp[1]), .Y (n_11));
  NOR3BXL g667__1705(.AN (scan_out), .B (state[1]), .C (n_9), .Y
       (ALUOp[0]));
  CLKINVX1 g678(.A (n_8), .Y (ALUSrc));
  NOR3XL g675__5122(.A (n_6), .B (n_3), .C (n_5), .Y (MemWrite));
  NOR3XL g679__8246(.A (state[0]), .B (n_6), .C (n_5), .Y (MemtoReg));
  OAI211X1 g680__7098(.A0 (opcode[0]), .A1 (opcode[1]), .B0 (n_21), .C0
       (n_0), .Y (n_16));
  NAND3X1 g681__6131(.A (state[2]), .B (n_3), .C (n_2), .Y (n_8));
  NOR2XL g673__1881(.A (n_5), .B (n_9), .Y (ALUOp[1]));
  NAND2XL g682__5115(.A (state[0]), .B (n_2), .Y (n_12));
  AOI22X1 g683__7482(.A0 (state[0]), .A1 (n_6), .B0 (state[2]), .B1
       (n_3), .Y (n_1));
  NAND2XL g688__4733(.A (n_6), .B (n_3), .Y (n_9));
  NOR2XL g684__6161(.A (opcode[2]), .B (opcode[3]), .Y (n_21));
  NAND2BX1 g685__9315(.AN (scan_out), .B (state[1]), .Y (n_5));
  NAND2XL g686__9945(.A (opcode[0]), .B (opcode[1]), .Y (n_0));
  NOR2XL g687__2883(.A (state[1]), .B (scan_out), .Y (n_2));
  CLKINVX1 g690(.A (state[0]), .Y (n_3));
  CLKINVX1 g689(.A (state[2]), .Y (n_6));
endmodule

