/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID ic312.vit.ac.in)
#  Generated on:      Fri Nov  7 18:12:57 2025
#  Design:            control_unit_fsm
#  Command:           saveNetlist control_unit_fsm.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Nov  4 2025 18:44:47 IST (Nov  4 2025 13:14:47 UTC)
// Verification Directory fv/control_unit_fsm 
module control_unit_fsm (
	clk, 
	rst_n, 
	opcode, 
	RegWrite, 
	ALUSrc, 
	ALUOp, 
	MemRead, 
	MemWrite, 
	MemtoReg, 
	Branch, 
	SE, 
	scan_in, 
	scan_out);
   input clk;
   input rst_n;
   input [3:0] opcode;
   output RegWrite;
   output ALUSrc;
   output [1:0] ALUOp;
   output MemRead;
   output MemWrite;
   output MemtoReg;
   output Branch;
   input SE;
   input scan_in;
   output scan_out;

   // Internal wires
   wire [3:0] state;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_5;
   wire n_6;
   wire n_8;
   wire n_9;
   wire n_11;
   wire n_12;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;

   assign Branch = ALUOp[0] ;

   SDFFRHQX1 \state_reg[1]  (.CK(clk),
	.D(n_26),
	.Q(state[1]),
	.RN(rst_n),
	.SE(SE),
	.SI(state[0]));
   SDFFRHQX1 \state_reg[2]  (.CK(clk),
	.D(n_24),
	.Q(state[2]),
	.RN(rst_n),
	.SE(SE),
	.SI(state[1]));
   OAI211X1 g660__2398 (.A0(opcode[0]),
	.A1(n_25),
	.B0(n_11),
	.C0(n_23),
	.Y(n_26));
   SDFFRHQX1 \state_reg[3]  (.CK(clk),
	.D(n_22),
	.Q(scan_out),
	.RN(rst_n),
	.SE(SE),
	.SI(state[2]));
   SDFFRHQX1 \state_reg[0]  (.CK(clk),
	.D(n_17),
	.Q(state[0]),
	.RN(rst_n),
	.SE(SE),
	.SI(scan_in));
   NAND2XL g663__5107 (.A(n_21),
	.B(n_20),
	.Y(n_25));
   OAI21X1 g665__6260 (.A0(n_16),
	.A1(n_15),
	.B0(n_23),
	.Y(n_24));
   AND4XL g666__4319 (.A(opcode[1]),
	.B(opcode[0]),
	.C(n_21),
	.D(n_19),
	.Y(n_22));
   MX2X1 g669__8428 (.A(n_19),
	.B(ALUSrc),
	.S0(opcode[1]),
	.Y(n_20));
   OAI22X1 g668__5526 (.A0(n_16),
	.A1(n_8),
	.B0(scan_out),
	.B1(n_9),
	.Y(n_17));
   NOR2XL g670__6783 (.A(ALUSrc),
	.B(n_19),
	.Y(n_15));
   CLKINVX1 g674 (.A(MemRead),
	.Y(n_23));
   NOR2XL g672__3680 (.A(n_5),
	.B(n_1),
	.Y(RegWrite));
   NOR2XL g677__1617 (.A(n_6),
	.B(n_12),
	.Y(MemRead));
   NOR2XL g676__2802 (.A(state[2]),
	.B(n_12),
	.Y(n_19));
   INVXL g671 (.A(ALUOp[1]),
	.Y(n_11));
   NOR3BXL g667__1705 (.AN(scan_out),
	.B(state[1]),
	.C(n_9),
	.Y(ALUOp[0]));
   CLKINVX1 g678 (.A(n_8),
	.Y(ALUSrc));
   NOR3XL g675__5122 (.A(n_6),
	.B(n_3),
	.C(n_5),
	.Y(MemWrite));
   NOR3XL g679__8246 (.A(state[0]),
	.B(n_6),
	.C(n_5),
	.Y(MemtoReg));
   OAI211X1 g680__7098 (.A0(opcode[0]),
	.A1(opcode[1]),
	.B0(n_21),
	.C0(n_0),
	.Y(n_16));
   NAND3X1 g681__6131 (.A(state[2]),
	.B(n_3),
	.C(n_2),
	.Y(n_8));
   NOR2XL g673__1881 (.A(n_5),
	.B(n_9),
	.Y(ALUOp[1]));
   NAND2XL g682__5115 (.A(state[0]),
	.B(n_2),
	.Y(n_12));
   AOI22X1 g683__7482 (.A0(state[0]),
	.A1(n_6),
	.B0(state[2]),
	.B1(n_3),
	.Y(n_1));
   NAND2XL g688__4733 (.A(n_6),
	.B(n_3),
	.Y(n_9));
   NOR2XL g684__6161 (.A(opcode[2]),
	.B(opcode[3]),
	.Y(n_21));
   NAND2BX1 g685__9315 (.AN(scan_out),
	.B(state[1]),
	.Y(n_5));
   NAND2XL g686__9945 (.A(opcode[0]),
	.B(opcode[1]),
	.Y(n_0));
   NOR2XL g687__2883 (.A(state[1]),
	.B(scan_out),
	.Y(n_2));
   CLKINVX1 g690 (.A(state[0]),
	.Y(n_3));
   CLKINVX1 g689 (.A(state[2]),
	.Y(n_6));
endmodule

