/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID ic312.vit.ac.in)
#  Generated on:      Fri Nov  7 19:19:50 2025
#  Design:            pipeline_cpu
#  Command:           saveNetlist pipeline_cpu.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Nov  5 2025 16:56:17 IST (Nov  5 2025 11:26:17 UTC)
// Verification Directory fv/pipeline_cpu 
module pipeline_cpu (
	clk, 
	rst, 
	debug_reg_r4, 
	SE, 
	scan_in, 
	scan_out);
   input clk;
   input rst;
   output [31:0] debug_reg_r4;
   input SE;
   input scan_in;
   output scan_out;

   // Internal wires
   wire [3:0] id_ex_rd_addr;
   wire [15:0] if_id_instr;
   wire [3:0] ex_wb_rd_addr;
   wire [31:0] ex_wb_alu_result;
   wire [31:0] id_ex_data2;
   wire [3:0] pc;
   wire [31:0] \reg_file[1] ;
   wire [31:0] \reg_file[5] ;
   wire [31:0] ex_alu_result;
   wire [31:0] id_ex_data1;
   wire add_156_40_n_0;
   wire add_156_40_n_1;
   wire add_156_40_n_3;
   wire add_156_40_n_5;
   wire add_156_40_n_7;
   wire add_156_40_n_9;
   wire add_156_40_n_11;
   wire add_156_40_n_13;
   wire add_156_40_n_15;
   wire add_156_40_n_17;
   wire add_156_40_n_19;
   wire add_156_40_n_21;
   wire add_156_40_n_23;
   wire add_156_40_n_25;
   wire add_156_40_n_27;
   wire add_156_40_n_29;
   wire add_156_40_n_31;
   wire add_156_40_n_33;
   wire add_156_40_n_35;
   wire add_156_40_n_37;
   wire add_156_40_n_39;
   wire add_156_40_n_41;
   wire add_156_40_n_43;
   wire add_156_40_n_45;
   wire add_156_40_n_47;
   wire add_156_40_n_49;
   wire add_156_40_n_51;
   wire add_156_40_n_53;
   wire add_156_40_n_55;
   wire add_156_40_n_57;
   wire add_156_40_n_59;
   wire add_156_40_n_62;
   wire add_156_40_n_63;
   wire ex_wb_reg_write;
   wire id_ex_reg_write;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_131;
   wire n_132;
   wire n_133;
   wire n_134;
   wire n_135;
   wire n_136;
   wire n_137;
   wire n_138;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_144;
   wire n_145;
   wire n_146;
   wire n_147;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_152;
   wire n_153;
   wire n_154;
   wire n_155;
   wire n_156;
   wire n_157;
   wire n_158;
   wire n_159;
   wire n_160;
   wire n_161;
   wire n_162;
   wire n_163;
   wire n_164;
   wire n_165;
   wire n_166;
   wire n_167;
   wire n_168;
   wire n_169;
   wire n_170;
   wire n_171;
   wire n_172;
   wire n_173;
   wire n_174;
   wire n_175;
   wire n_176;
   wire n_177;
   wire n_178;
   wire n_179;
   wire n_180;
   wire n_181;
   wire n_182;
   wire n_183;
   wire n_184;
   wire n_185;
   wire n_186;
   wire n_187;
   wire n_188;
   wire n_189;
   wire n_190;
   wire n_191;
   wire n_192;
   wire n_193;
   wire n_194;
   wire n_195;
   wire n_196;
   wire n_197;
   wire n_198;
   wire n_199;
   wire n_200;
   wire n_201;
   wire n_202;
   wire n_203;
   wire n_204;
   wire n_205;
   wire n_206;
   wire n_207;
   wire n_208;
   wire n_209;
   wire n_210;
   wire n_211;
   wire n_212;
   wire n_213;
   wire n_214;
   wire n_215;
   wire n_216;
   wire n_217;
   wire n_218;
   wire n_219;
   wire n_220;
   wire n_221;
   wire n_222;
   wire n_223;
   wire n_224;
   wire n_225;
   wire n_226;
   wire n_227;
   wire n_228;
   wire n_229;
   wire n_230;
   wire n_231;
   wire n_232;
   wire n_234;
   wire n_235;
   wire n_237;
   wire n_238;
   wire n_240;
   wire n_241;
   wire n_242;
   wire n_243;
   wire n_244;
   wire n_245;
   wire n_246;
   wire n_247;
   wire n_248;
   wire n_249;
   wire n_252;

   OAI21X1 g2712__2398 (.A0(id_ex_rd_addr[2]),
	.A1(n_243),
	.B0(n_246),
	.Y(n_245));
   NAND2XL g2713__5107 (.A(n_243),
	.B(n_249),
	.Y(n_248));
   NAND3BX1 g2714__6260 (.AN(if_id_instr[3]),
	.B(if_id_instr[2]),
	.C(if_id_instr[4]),
	.Y(n_244));
   OR2X1 g2715__4319 (.A(ex_wb_rd_addr[2]),
	.B(n_249),
	.Y(n_246));
   NAND2BX1 g2716__8428 (.AN(if_id_instr[3]),
	.B(if_id_instr[4]),
	.Y(n_247));
   NAND2XL g2717__5526 (.A(id_ex_reg_write),
	.B(id_ex_rd_addr[0]),
	.Y(n_243));
   NAND2XL g2718__6783 (.A(ex_wb_rd_addr[0]),
	.B(ex_wb_reg_write),
	.Y(n_249));
   SDFFRHQX1 \ex_wb_rd_addr_reg[0]  (.CK(clk),
	.D(id_ex_rd_addr[0]),
	.Q(ex_wb_rd_addr[0]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[31]));
   SDFFRHQX1 \id_ex_rd_addr_reg[0]  (.CK(clk),
	.D(if_id_instr[3]),
	.Q(id_ex_rd_addr[0]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[31]));
   SDFFRHQX1 \id_ex_rd_addr_reg[2]  (.CK(clk),
	.D(n_232),
	.Q(id_ex_rd_addr[2]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_rd_addr[0]));
   SDFFRHQX1 id_ex_reg_write_reg (.CK(clk),
	.D(n_231),
	.Q(id_ex_reg_write),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_rd_addr[2]));
   SDFFRHQX1 \if_id_instr_reg[2]  (.CK(clk),
	.D(n_235),
	.Q(if_id_instr[2]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_reg_write));
   SDFFRHQX1 \if_id_instr_reg[3]  (.CK(clk),
	.D(n_252),
	.Q(if_id_instr[3]),
	.RN(n_0),
	.SE(SE),
	.SI(if_id_instr[2]));
   SDFFRHQX1 \if_id_instr_reg[4]  (.CK(clk),
	.D(n_240),
	.Q(if_id_instr[4]),
	.RN(n_0),
	.SE(SE),
	.SI(if_id_instr[3]));
   SDFFRHQX1 \pc_reg[0]  (.CK(clk),
	.D(n_234),
	.Q(pc[0]),
	.RN(n_0),
	.SE(SE),
	.SI(if_id_instr[4]));
   SDFFRHQX1 \pc_reg[1]  (.CK(clk),
	.D(n_241),
	.Q(pc[1]),
	.RN(n_0),
	.SE(SE),
	.SI(pc[0]));
   SDFFRHQX1 \pc_reg[2]  (.CK(clk),
	.D(n_242),
	.Q(pc[2]),
	.RN(n_0),
	.SE(SE),
	.SI(pc[1]));
   SDFFRHQX1 \pc_reg[3]  (.CK(clk),
	.D(n_238),
	.Q(pc[3]),
	.RN(n_0),
	.SE(SE),
	.SI(pc[2]));
   SDFFRHQX1 \reg_file_reg[1][0]  (.CK(clk),
	.D(n_139),
	.Q(\reg_file[1] [0]),
	.RN(n_0),
	.SE(SE),
	.SI(pc[3]));
   SDFFRHQX1 \reg_file_reg[1][1]  (.CK(clk),
	.D(n_129),
	.Q(\reg_file[1] [1]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [0]));
   SDFFRHQX1 \reg_file_reg[1][2]  (.CK(clk),
	.D(n_140),
	.Q(\reg_file[1] [2]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [1]));
   SDFFRHQX1 \reg_file_reg[1][3]  (.CK(clk),
	.D(n_128),
	.Q(\reg_file[1] [3]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [2]));
   SDFFRHQX1 \reg_file_reg[1][4]  (.CK(clk),
	.D(n_127),
	.Q(\reg_file[1] [4]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [3]));
   SDFFRHQX1 \reg_file_reg[1][5]  (.CK(clk),
	.D(n_126),
	.Q(\reg_file[1] [5]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [4]));
   SDFFRHQX1 \reg_file_reg[1][6]  (.CK(clk),
	.D(n_125),
	.Q(\reg_file[1] [6]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [5]));
   SDFFRHQX1 \reg_file_reg[1][7]  (.CK(clk),
	.D(n_124),
	.Q(\reg_file[1] [7]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [6]));
   SDFFRHQX1 \reg_file_reg[1][8]  (.CK(clk),
	.D(n_123),
	.Q(\reg_file[1] [8]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [7]));
   SDFFRHQX1 \reg_file_reg[1][9]  (.CK(clk),
	.D(n_122),
	.Q(\reg_file[1] [9]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [8]));
   SDFFRHQX1 \reg_file_reg[1][10]  (.CK(clk),
	.D(n_146),
	.Q(\reg_file[1] [10]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [9]));
   SDFFRHQX1 \reg_file_reg[1][11]  (.CK(clk),
	.D(n_148),
	.Q(\reg_file[1] [11]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [10]));
   SDFFRHQX1 \reg_file_reg[1][12]  (.CK(clk),
	.D(n_152),
	.Q(\reg_file[1] [12]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [11]));
   SDFFRHQX1 \reg_file_reg[1][13]  (.CK(clk),
	.D(n_151),
	.Q(\reg_file[1] [13]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [12]));
   SDFFRHQX1 \reg_file_reg[1][14]  (.CK(clk),
	.D(n_131),
	.Q(\reg_file[1] [14]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [13]));
   SDFFRHQX1 \reg_file_reg[1][15]  (.CK(clk),
	.D(n_150),
	.Q(\reg_file[1] [15]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [14]));
   SDFFRHQX1 \reg_file_reg[1][16]  (.CK(clk),
	.D(n_134),
	.Q(\reg_file[1] [16]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [15]));
   SDFFRHQX1 \reg_file_reg[1][17]  (.CK(clk),
	.D(n_149),
	.Q(\reg_file[1] [17]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [16]));
   SDFFRHQX1 \reg_file_reg[1][18]  (.CK(clk),
	.D(n_132),
	.Q(\reg_file[1] [18]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [17]));
   SDFFRHQX1 \reg_file_reg[1][19]  (.CK(clk),
	.D(n_147),
	.Q(\reg_file[1] [19]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [18]));
   SDFFRHQX1 \reg_file_reg[1][20]  (.CK(clk),
	.D(n_133),
	.Q(\reg_file[1] [20]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [19]));
   SDFFRHQX1 \reg_file_reg[1][21]  (.CK(clk),
	.D(n_145),
	.Q(\reg_file[1] [21]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [20]));
   SDFFRHQX1 \reg_file_reg[1][22]  (.CK(clk),
	.D(n_144),
	.Q(\reg_file[1] [22]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [21]));
   SDFFRHQX1 \reg_file_reg[1][23]  (.CK(clk),
	.D(n_143),
	.Q(\reg_file[1] [23]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [22]));
   SDFFRHQX1 \reg_file_reg[1][24]  (.CK(clk),
	.D(n_142),
	.Q(\reg_file[1] [24]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [23]));
   SDFFRHQX1 \reg_file_reg[1][25]  (.CK(clk),
	.D(n_141),
	.Q(\reg_file[1] [25]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [24]));
   SDFFRHQX1 \reg_file_reg[1][26]  (.CK(clk),
	.D(n_154),
	.Q(\reg_file[1] [26]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [25]));
   SDFFRHQX1 \reg_file_reg[1][27]  (.CK(clk),
	.D(n_130),
	.Q(\reg_file[1] [27]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [26]));
   SDFFRHQX1 \reg_file_reg[1][28]  (.CK(clk),
	.D(n_138),
	.Q(\reg_file[1] [28]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [27]));
   SDFFRHQX1 \reg_file_reg[1][29]  (.CK(clk),
	.D(n_137),
	.Q(\reg_file[1] [29]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [28]));
   SDFFRHQX1 \reg_file_reg[1][30]  (.CK(clk),
	.D(n_136),
	.Q(\reg_file[1] [30]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [29]));
   SDFFRHQX1 \reg_file_reg[1][31]  (.CK(clk),
	.D(n_135),
	.Q(\reg_file[1] [31]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [30]));
   SDFFRHQX1 \reg_file_reg[4][0]  (.CK(clk),
	.D(n_221),
	.Q(debug_reg_r4[0]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[1] [31]));
   SDFFRHQX1 \reg_file_reg[4][1]  (.CK(clk),
	.D(n_220),
	.Q(debug_reg_r4[1]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[0]));
   SDFFRHQX1 \reg_file_reg[4][2]  (.CK(clk),
	.D(n_219),
	.Q(debug_reg_r4[2]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[1]));
   SDFFRHQX1 \reg_file_reg[4][3]  (.CK(clk),
	.D(n_218),
	.Q(debug_reg_r4[3]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[2]));
   SDFFRHQX1 \reg_file_reg[4][4]  (.CK(clk),
	.D(n_217),
	.Q(debug_reg_r4[4]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[3]));
   SDFFRHQX1 \reg_file_reg[4][5]  (.CK(clk),
	.D(n_216),
	.Q(debug_reg_r4[5]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[4]));
   SDFFRHQX1 \reg_file_reg[4][6]  (.CK(clk),
	.D(n_215),
	.Q(debug_reg_r4[6]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[5]));
   SDFFRHQX1 \reg_file_reg[4][7]  (.CK(clk),
	.D(n_214),
	.Q(debug_reg_r4[7]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[6]));
   SDFFRHQX1 \reg_file_reg[4][8]  (.CK(clk),
	.D(n_213),
	.Q(debug_reg_r4[8]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[7]));
   SDFFRHQX1 \reg_file_reg[4][9]  (.CK(clk),
	.D(n_212),
	.Q(debug_reg_r4[9]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[8]));
   SDFFRHQX1 \reg_file_reg[4][10]  (.CK(clk),
	.D(n_211),
	.Q(debug_reg_r4[10]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[9]));
   SDFFRHQX1 \reg_file_reg[4][11]  (.CK(clk),
	.D(n_210),
	.Q(debug_reg_r4[11]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[10]));
   SDFFRHQX1 \reg_file_reg[4][12]  (.CK(clk),
	.D(n_209),
	.Q(debug_reg_r4[12]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[11]));
   SDFFRHQX1 \reg_file_reg[4][13]  (.CK(clk),
	.D(n_208),
	.Q(debug_reg_r4[13]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[12]));
   SDFFRHQX1 \reg_file_reg[4][14]  (.CK(clk),
	.D(n_207),
	.Q(debug_reg_r4[14]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[13]));
   SDFFRHQX1 \reg_file_reg[4][15]  (.CK(clk),
	.D(n_222),
	.Q(debug_reg_r4[15]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[14]));
   SDFFRHQX1 \reg_file_reg[4][16]  (.CK(clk),
	.D(n_205),
	.Q(debug_reg_r4[16]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[15]));
   SDFFRHQX1 \reg_file_reg[4][17]  (.CK(clk),
	.D(n_204),
	.Q(debug_reg_r4[17]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[16]));
   SDFFRHQX1 \reg_file_reg[4][18]  (.CK(clk),
	.D(n_203),
	.Q(debug_reg_r4[18]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[17]));
   SDFFRHQX1 \reg_file_reg[4][19]  (.CK(clk),
	.D(n_202),
	.Q(debug_reg_r4[19]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[18]));
   SDFFRHQX1 \reg_file_reg[4][20]  (.CK(clk),
	.D(n_201),
	.Q(debug_reg_r4[20]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[19]));
   SDFFRHQX1 \reg_file_reg[4][21]  (.CK(clk),
	.D(n_200),
	.Q(debug_reg_r4[21]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[20]));
   SDFFRHQX1 \reg_file_reg[4][22]  (.CK(clk),
	.D(n_199),
	.Q(debug_reg_r4[22]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[21]));
   SDFFRHQX1 \reg_file_reg[4][23]  (.CK(clk),
	.D(n_198),
	.Q(debug_reg_r4[23]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[22]));
   SDFFRHQX1 \reg_file_reg[4][24]  (.CK(clk),
	.D(n_197),
	.Q(debug_reg_r4[24]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[23]));
   SDFFRHQX1 \reg_file_reg[4][25]  (.CK(clk),
	.D(n_196),
	.Q(debug_reg_r4[25]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[24]));
   SDFFRHQX1 \reg_file_reg[4][26]  (.CK(clk),
	.D(n_195),
	.Q(debug_reg_r4[26]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[25]));
   SDFFRHQX1 \reg_file_reg[4][27]  (.CK(clk),
	.D(n_192),
	.Q(debug_reg_r4[27]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[26]));
   SDFFRHQX1 \reg_file_reg[4][28]  (.CK(clk),
	.D(n_194),
	.Q(debug_reg_r4[28]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[27]));
   SDFFRHQX1 \reg_file_reg[4][29]  (.CK(clk),
	.D(n_193),
	.Q(debug_reg_r4[29]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[28]));
   SDFFRHQX1 \reg_file_reg[4][30]  (.CK(clk),
	.D(n_191),
	.Q(debug_reg_r4[30]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[29]));
   SDFFRHQX1 \reg_file_reg[4][31]  (.CK(clk),
	.D(n_206),
	.Q(debug_reg_r4[31]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[30]));
   SDFFRHQX1 \reg_file_reg[5][0]  (.CK(clk),
	.D(n_167),
	.Q(\reg_file[5] [0]),
	.RN(n_0),
	.SE(SE),
	.SI(debug_reg_r4[31]));
   SDFFRHQX1 \reg_file_reg[5][1]  (.CK(clk),
	.D(n_166),
	.Q(\reg_file[5] [1]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [0]));
   SDFFRHQX1 \reg_file_reg[5][2]  (.CK(clk),
	.D(n_165),
	.Q(\reg_file[5] [2]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [1]));
   SDFFRHQX1 \reg_file_reg[5][3]  (.CK(clk),
	.D(n_164),
	.Q(\reg_file[5] [3]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [2]));
   SDFFRHQX1 \reg_file_reg[5][4]  (.CK(clk),
	.D(n_163),
	.Q(\reg_file[5] [4]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [3]));
   SDFFRHQX1 \reg_file_reg[5][5]  (.CK(clk),
	.D(n_162),
	.Q(\reg_file[5] [5]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [4]));
   SDFFRHQX1 \reg_file_reg[5][6]  (.CK(clk),
	.D(n_161),
	.Q(\reg_file[5] [6]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [5]));
   SDFFRHQX1 \reg_file_reg[5][7]  (.CK(clk),
	.D(n_160),
	.Q(\reg_file[5] [7]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [6]));
   SDFFRHQX1 \reg_file_reg[5][8]  (.CK(clk),
	.D(n_159),
	.Q(\reg_file[5] [8]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [7]));
   SDFFRHQX1 \reg_file_reg[5][9]  (.CK(clk),
	.D(n_158),
	.Q(\reg_file[5] [9]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [8]));
   SDFFRHQX1 \reg_file_reg[5][10]  (.CK(clk),
	.D(n_157),
	.Q(\reg_file[5] [10]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [9]));
   SDFFRHQX1 \reg_file_reg[5][11]  (.CK(clk),
	.D(n_188),
	.Q(\reg_file[5] [11]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [10]));
   SDFFRHQX1 \reg_file_reg[5][12]  (.CK(clk),
	.D(n_187),
	.Q(\reg_file[5] [12]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [11]));
   SDFFRHQX1 \reg_file_reg[5][13]  (.CK(clk),
	.D(n_186),
	.Q(\reg_file[5] [13]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [12]));
   SDFFRHQX1 \reg_file_reg[5][14]  (.CK(clk),
	.D(n_185),
	.Q(\reg_file[5] [14]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [13]));
   SDFFRHQX1 \reg_file_reg[5][15]  (.CK(clk),
	.D(n_184),
	.Q(\reg_file[5] [15]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [14]));
   SDFFRHQX1 \reg_file_reg[5][16]  (.CK(clk),
	.D(n_183),
	.Q(\reg_file[5] [16]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [15]));
   SDFFRHQX1 \reg_file_reg[5][17]  (.CK(clk),
	.D(n_182),
	.Q(\reg_file[5] [17]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [16]));
   SDFFRHQX1 \reg_file_reg[5][18]  (.CK(clk),
	.D(n_181),
	.Q(\reg_file[5] [18]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [17]));
   SDFFRHQX1 \reg_file_reg[5][19]  (.CK(clk),
	.D(n_180),
	.Q(\reg_file[5] [19]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [18]));
   SDFFRHQX1 \reg_file_reg[5][20]  (.CK(clk),
	.D(n_179),
	.Q(\reg_file[5] [20]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [19]));
   SDFFRHQX1 \reg_file_reg[5][21]  (.CK(clk),
	.D(n_178),
	.Q(\reg_file[5] [21]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [20]));
   SDFFRHQX1 \reg_file_reg[5][22]  (.CK(clk),
	.D(n_177),
	.Q(\reg_file[5] [22]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [21]));
   SDFFRHQX1 \reg_file_reg[5][23]  (.CK(clk),
	.D(n_176),
	.Q(\reg_file[5] [23]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [22]));
   SDFFRHQX1 \reg_file_reg[5][24]  (.CK(clk),
	.D(n_175),
	.Q(\reg_file[5] [24]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [23]));
   SDFFRHQX1 \reg_file_reg[5][25]  (.CK(clk),
	.D(n_174),
	.Q(\reg_file[5] [25]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [24]));
   SDFFRHQX1 \reg_file_reg[5][26]  (.CK(clk),
	.D(n_189),
	.Q(\reg_file[5] [26]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [25]));
   SDFFRHQX1 \reg_file_reg[5][27]  (.CK(clk),
	.D(n_172),
	.Q(\reg_file[5] [27]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [26]));
   SDFFRHQX1 \reg_file_reg[5][28]  (.CK(clk),
	.D(n_171),
	.Q(\reg_file[5] [28]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [27]));
   SDFFRHQX1 \reg_file_reg[5][29]  (.CK(clk),
	.D(n_170),
	.Q(\reg_file[5] [29]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [28]));
   SDFFRHQX1 \reg_file_reg[5][30]  (.CK(clk),
	.D(n_169),
	.Q(\reg_file[5] [30]),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [29]));
   SDFFRHQX1 \reg_file_reg[5][31]  (.CK(clk),
	.D(n_168),
	.Q(scan_out),
	.RN(n_0),
	.SE(SE),
	.SI(\reg_file[5] [30]));
   OAI2BB1X1 g2851__3680 (.A0N(pc[2]),
	.A1N(n_228),
	.B0(n_229),
	.Y(n_242));
   OAI2BB1X1 g2852__1617 (.A0N(pc[1]),
	.A1N(n_228),
	.B0(n_230),
	.Y(n_241));
   INVX1 g2856 (.A(n_237),
	.Y(n_240));
   MX2X1 g2858__2802 (.A(n_226),
	.B(pc[3]),
	.S0(n_228),
	.Y(n_238));
   AOI32X1 g2859__1705 (.A0(pc[0]),
	.A1(n_156),
	.A2(n_227),
	.B0(if_id_instr[4]),
	.B1(n_228),
	.Y(n_237));
   MX2X1 g2861__8246 (.A(n_156),
	.B(if_id_instr[2]),
	.S0(n_228),
	.Y(n_235));
   MXI2XL g2862__7098 (.A(n_228),
	.B(n_227),
	.S0(pc[0]),
	.Y(n_234));
   NOR2BX1 g2864__6131 (.AN(if_id_instr[4]),
	.B(n_228),
	.Y(n_232));
   NOR2XL g2865__1881 (.A(n_113),
	.B(n_228),
	.Y(n_231));
   OAI211X1 g2866__5115 (.A0(pc[0]),
	.A1(pc[1]),
	.B0(n_120),
	.C0(n_227),
	.Y(n_230));
   OAI211X1 g2867__7482 (.A0(pc[2]),
	.A1(n_190),
	.B0(n_223),
	.C0(n_227),
	.Y(n_229));
   CLKINVX1 g2868 (.A(n_228),
	.Y(n_227));
   OAI211X1 g2869__4733 (.A0(n_247),
	.A1(n_224),
	.B0(n_118),
	.C0(n_153),
	.Y(n_228));
   OAI21XL g2870__6161 (.A0(n_223),
	.A1(pc[3]),
	.B0(n_225),
	.Y(n_226));
   NAND2XL g2871__9315 (.A(pc[3]),
	.B(n_223),
	.Y(n_225));
   AOI21X1 g2888__9945 (.A0(n_113),
	.A1(n_173),
	.B0(n_245),
	.Y(n_224));
   MX2X1 g2937__2883 (.A(ex_wb_alu_result[15]),
	.B(debug_reg_r4[15]),
	.S0(n_155),
	.Y(n_222));
   MX2X1 g2938__2346 (.A(ex_wb_alu_result[0]),
	.B(debug_reg_r4[0]),
	.S0(n_155),
	.Y(n_221));
   MX2X1 g2939__1666 (.A(ex_wb_alu_result[1]),
	.B(debug_reg_r4[1]),
	.S0(n_155),
	.Y(n_220));
   MX2X1 g2940__7410 (.A(ex_wb_alu_result[2]),
	.B(debug_reg_r4[2]),
	.S0(n_155),
	.Y(n_219));
   MX2X1 g2941__6417 (.A(ex_wb_alu_result[3]),
	.B(debug_reg_r4[3]),
	.S0(n_155),
	.Y(n_218));
   MX2X1 g2942__5477 (.A(ex_wb_alu_result[4]),
	.B(debug_reg_r4[4]),
	.S0(n_155),
	.Y(n_217));
   MX2X1 g2943__2398 (.A(ex_wb_alu_result[5]),
	.B(debug_reg_r4[5]),
	.S0(n_155),
	.Y(n_216));
   MX2X1 g2944__5107 (.A(ex_wb_alu_result[6]),
	.B(debug_reg_r4[6]),
	.S0(n_155),
	.Y(n_215));
   MX2X1 g2945__6260 (.A(ex_wb_alu_result[7]),
	.B(debug_reg_r4[7]),
	.S0(n_155),
	.Y(n_214));
   MX2X1 g2946__4319 (.A(ex_wb_alu_result[8]),
	.B(debug_reg_r4[8]),
	.S0(n_155),
	.Y(n_213));
   MX2X1 g2947__8428 (.A(ex_wb_alu_result[9]),
	.B(debug_reg_r4[9]),
	.S0(n_155),
	.Y(n_212));
   MX2X1 g2948__5526 (.A(ex_wb_alu_result[10]),
	.B(debug_reg_r4[10]),
	.S0(n_155),
	.Y(n_211));
   MX2X1 g2949__6783 (.A(ex_wb_alu_result[11]),
	.B(debug_reg_r4[11]),
	.S0(n_155),
	.Y(n_210));
   MX2X1 g2950__3680 (.A(ex_wb_alu_result[12]),
	.B(debug_reg_r4[12]),
	.S0(n_155),
	.Y(n_209));
   MX2X1 g2951__1617 (.A(ex_wb_alu_result[13]),
	.B(debug_reg_r4[13]),
	.S0(n_155),
	.Y(n_208));
   MX2X1 g2952__2802 (.A(ex_wb_alu_result[14]),
	.B(debug_reg_r4[14]),
	.S0(n_155),
	.Y(n_207));
   MX2X1 g2953__1705 (.A(ex_wb_alu_result[31]),
	.B(debug_reg_r4[31]),
	.S0(n_155),
	.Y(n_206));
   MX2X1 g2954__5122 (.A(ex_wb_alu_result[16]),
	.B(debug_reg_r4[16]),
	.S0(n_155),
	.Y(n_205));
   MX2X1 g2955__8246 (.A(ex_wb_alu_result[17]),
	.B(debug_reg_r4[17]),
	.S0(n_155),
	.Y(n_204));
   MX2X1 g2956__7098 (.A(ex_wb_alu_result[18]),
	.B(debug_reg_r4[18]),
	.S0(n_155),
	.Y(n_203));
   MX2X1 g2957__6131 (.A(ex_wb_alu_result[19]),
	.B(debug_reg_r4[19]),
	.S0(n_155),
	.Y(n_202));
   MX2X1 g2958__1881 (.A(ex_wb_alu_result[20]),
	.B(debug_reg_r4[20]),
	.S0(n_155),
	.Y(n_201));
   MX2X1 g2959__5115 (.A(ex_wb_alu_result[21]),
	.B(debug_reg_r4[21]),
	.S0(n_155),
	.Y(n_200));
   MX2X1 g2960__7482 (.A(ex_wb_alu_result[22]),
	.B(debug_reg_r4[22]),
	.S0(n_155),
	.Y(n_199));
   MX2X1 g2961__4733 (.A(ex_wb_alu_result[23]),
	.B(debug_reg_r4[23]),
	.S0(n_155),
	.Y(n_198));
   MX2X1 g2962__6161 (.A(ex_wb_alu_result[24]),
	.B(debug_reg_r4[24]),
	.S0(n_155),
	.Y(n_197));
   MX2X1 g2963__9315 (.A(ex_wb_alu_result[25]),
	.B(debug_reg_r4[25]),
	.S0(n_155),
	.Y(n_196));
   MX2X1 g2964__9945 (.A(ex_wb_alu_result[26]),
	.B(debug_reg_r4[26]),
	.S0(n_155),
	.Y(n_195));
   MX2X1 g2965__2883 (.A(ex_wb_alu_result[28]),
	.B(debug_reg_r4[28]),
	.S0(n_155),
	.Y(n_194));
   MX2X1 g2966__2346 (.A(ex_wb_alu_result[29]),
	.B(debug_reg_r4[29]),
	.S0(n_155),
	.Y(n_193));
   MX2X1 g2967__1666 (.A(ex_wb_alu_result[27]),
	.B(debug_reg_r4[27]),
	.S0(n_155),
	.Y(n_192));
   MX2X1 g2968__7410 (.A(ex_wb_alu_result[30]),
	.B(debug_reg_r4[30]),
	.S0(n_155),
	.Y(n_191));
   NAND2XL g2969__6417 (.A(pc[2]),
	.B(n_190),
	.Y(n_223));
   INVX1 g2970 (.A(n_120),
	.Y(n_190));
   MX2X1 g3003__5477 (.A(\reg_file[5] [26]),
	.B(ex_wb_alu_result[26]),
	.S0(n_119),
	.Y(n_189));
   MX2X1 g3004__2398 (.A(\reg_file[5] [11]),
	.B(ex_wb_alu_result[11]),
	.S0(n_119),
	.Y(n_188));
   MX2X1 g3005__5107 (.A(\reg_file[5] [12]),
	.B(ex_wb_alu_result[12]),
	.S0(n_119),
	.Y(n_187));
   MX2X1 g3006__6260 (.A(\reg_file[5] [13]),
	.B(ex_wb_alu_result[13]),
	.S0(n_119),
	.Y(n_186));
   MX2X1 g3007__4319 (.A(\reg_file[5] [14]),
	.B(ex_wb_alu_result[14]),
	.S0(n_119),
	.Y(n_185));
   MX2X1 g3008__8428 (.A(\reg_file[5] [15]),
	.B(ex_wb_alu_result[15]),
	.S0(n_119),
	.Y(n_184));
   MX2X1 g3009__5526 (.A(\reg_file[5] [16]),
	.B(ex_wb_alu_result[16]),
	.S0(n_119),
	.Y(n_183));
   MX2X1 g3010__6783 (.A(\reg_file[5] [17]),
	.B(ex_wb_alu_result[17]),
	.S0(n_119),
	.Y(n_182));
   MX2X1 g3011__3680 (.A(\reg_file[5] [18]),
	.B(ex_wb_alu_result[18]),
	.S0(n_119),
	.Y(n_181));
   MX2X1 g3012__1617 (.A(\reg_file[5] [19]),
	.B(ex_wb_alu_result[19]),
	.S0(n_119),
	.Y(n_180));
   MX2X1 g3013__2802 (.A(\reg_file[5] [20]),
	.B(ex_wb_alu_result[20]),
	.S0(n_119),
	.Y(n_179));
   MX2X1 g3014__1705 (.A(\reg_file[5] [21]),
	.B(ex_wb_alu_result[21]),
	.S0(n_119),
	.Y(n_178));
   MX2X1 g3015__5122 (.A(\reg_file[5] [22]),
	.B(ex_wb_alu_result[22]),
	.S0(n_119),
	.Y(n_177));
   MX2X1 g3016__8246 (.A(\reg_file[5] [23]),
	.B(ex_wb_alu_result[23]),
	.S0(n_119),
	.Y(n_176));
   MX2X1 g3017__7098 (.A(\reg_file[5] [24]),
	.B(ex_wb_alu_result[24]),
	.S0(n_119),
	.Y(n_175));
   MX2X1 g3018__6131 (.A(\reg_file[5] [25]),
	.B(ex_wb_alu_result[25]),
	.S0(n_119),
	.Y(n_174));
   OAI21X1 g3019__1881 (.A0(id_ex_rd_addr[0]),
	.A1(n_121),
	.B0(n_155),
	.Y(n_173));
   MX2X1 g3020__5115 (.A(\reg_file[5] [27]),
	.B(ex_wb_alu_result[27]),
	.S0(n_119),
	.Y(n_172));
   MX2X1 g3021__7482 (.A(\reg_file[5] [28]),
	.B(ex_wb_alu_result[28]),
	.S0(n_119),
	.Y(n_171));
   MX2X1 g3022__4733 (.A(\reg_file[5] [29]),
	.B(ex_wb_alu_result[29]),
	.S0(n_119),
	.Y(n_170));
   MX2X1 g3023__6161 (.A(\reg_file[5] [30]),
	.B(ex_wb_alu_result[30]),
	.S0(n_119),
	.Y(n_169));
   MX2X1 g3024__9315 (.A(scan_out),
	.B(ex_wb_alu_result[31]),
	.S0(n_119),
	.Y(n_168));
   MX2X1 g3025__9945 (.A(\reg_file[5] [0]),
	.B(ex_wb_alu_result[0]),
	.S0(n_119),
	.Y(n_167));
   MX2X1 g3026__2883 (.A(\reg_file[5] [1]),
	.B(ex_wb_alu_result[1]),
	.S0(n_119),
	.Y(n_166));
   MX2X1 g3027__2346 (.A(\reg_file[5] [2]),
	.B(ex_wb_alu_result[2]),
	.S0(n_119),
	.Y(n_165));
   MX2X1 g3028__1666 (.A(\reg_file[5] [3]),
	.B(ex_wb_alu_result[3]),
	.S0(n_119),
	.Y(n_164));
   MX2X1 g3029__7410 (.A(\reg_file[5] [4]),
	.B(ex_wb_alu_result[4]),
	.S0(n_119),
	.Y(n_163));
   MX2X1 g3030__6417 (.A(\reg_file[5] [5]),
	.B(ex_wb_alu_result[5]),
	.S0(n_119),
	.Y(n_162));
   MX2X1 g3031__5477 (.A(\reg_file[5] [6]),
	.B(ex_wb_alu_result[6]),
	.S0(n_119),
	.Y(n_161));
   MX2X1 g3032__2398 (.A(\reg_file[5] [7]),
	.B(ex_wb_alu_result[7]),
	.S0(n_119),
	.Y(n_160));
   MX2X1 g3033__5107 (.A(\reg_file[5] [8]),
	.B(ex_wb_alu_result[8]),
	.S0(n_119),
	.Y(n_159));
   MX2X1 g3034__6260 (.A(\reg_file[5] [9]),
	.B(ex_wb_alu_result[9]),
	.S0(n_119),
	.Y(n_158));
   MX2X1 g3035__4319 (.A(\reg_file[5] [10]),
	.B(ex_wb_alu_result[10]),
	.S0(n_119),
	.Y(n_157));
   MX2X1 g3036__8428 (.A(ex_wb_alu_result[26]),
	.B(\reg_file[1] [26]),
	.S0(n_246),
	.Y(n_154));
   NAND3BX1 g3037__5526 (.AN(if_id_instr[3]),
	.B(if_id_instr[2]),
	.C(n_245),
	.Y(n_153));
   MX2X1 g3038__6783 (.A(ex_wb_alu_result[12]),
	.B(\reg_file[1] [12]),
	.S0(n_246),
	.Y(n_152));
   MX2X1 g3039__3680 (.A(ex_wb_alu_result[13]),
	.B(\reg_file[1] [13]),
	.S0(n_246),
	.Y(n_151));
   MX2X1 g3040__1617 (.A(ex_wb_alu_result[15]),
	.B(\reg_file[1] [15]),
	.S0(n_246),
	.Y(n_150));
   MX2X1 g3041__2802 (.A(ex_wb_alu_result[17]),
	.B(\reg_file[1] [17]),
	.S0(n_246),
	.Y(n_149));
   MX2X1 g3042__1705 (.A(ex_wb_alu_result[11]),
	.B(\reg_file[1] [11]),
	.S0(n_246),
	.Y(n_148));
   MX2X1 g3043__5122 (.A(ex_wb_alu_result[19]),
	.B(\reg_file[1] [19]),
	.S0(n_246),
	.Y(n_147));
   MX2X1 g3044__8246 (.A(ex_wb_alu_result[10]),
	.B(\reg_file[1] [10]),
	.S0(n_246),
	.Y(n_146));
   MX2X1 g3045__7098 (.A(ex_wb_alu_result[21]),
	.B(\reg_file[1] [21]),
	.S0(n_246),
	.Y(n_145));
   MX2X1 g3046__6131 (.A(ex_wb_alu_result[22]),
	.B(\reg_file[1] [22]),
	.S0(n_246),
	.Y(n_144));
   MX2X1 g3047__1881 (.A(ex_wb_alu_result[23]),
	.B(\reg_file[1] [23]),
	.S0(n_246),
	.Y(n_143));
   MX2X1 g3048__5115 (.A(ex_wb_alu_result[24]),
	.B(\reg_file[1] [24]),
	.S0(n_246),
	.Y(n_142));
   MX2X1 g3049__7482 (.A(ex_wb_alu_result[25]),
	.B(\reg_file[1] [25]),
	.S0(n_246),
	.Y(n_141));
   MX2X1 g3050__4733 (.A(ex_wb_alu_result[2]),
	.B(\reg_file[1] [2]),
	.S0(n_246),
	.Y(n_140));
   NOR3X1 g3051__6161 (.A(pc[2]),
	.B(pc[1]),
	.C(pc[3]),
	.Y(n_156));
   OR3X1 g3052__9315 (.A(ex_wb_rd_addr[0]),
	.B(n_116),
	.C(n_115),
	.Y(n_155));
   MX2X1 g3053__9945 (.A(ex_wb_alu_result[0]),
	.B(\reg_file[1] [0]),
	.S0(n_246),
	.Y(n_139));
   MX2X1 g3054__2883 (.A(ex_wb_alu_result[28]),
	.B(\reg_file[1] [28]),
	.S0(n_246),
	.Y(n_138));
   MX2X1 g3055__2346 (.A(ex_wb_alu_result[29]),
	.B(\reg_file[1] [29]),
	.S0(n_246),
	.Y(n_137));
   MX2X1 g3056__1666 (.A(ex_wb_alu_result[30]),
	.B(\reg_file[1] [30]),
	.S0(n_246),
	.Y(n_136));
   MX2X1 g3057__7410 (.A(ex_wb_alu_result[31]),
	.B(\reg_file[1] [31]),
	.S0(n_246),
	.Y(n_135));
   MX2X1 g3058__6417 (.A(ex_wb_alu_result[16]),
	.B(\reg_file[1] [16]),
	.S0(n_246),
	.Y(n_134));
   MX2X1 g3059__5477 (.A(ex_wb_alu_result[20]),
	.B(\reg_file[1] [20]),
	.S0(n_246),
	.Y(n_133));
   MX2X1 g3060__2398 (.A(ex_wb_alu_result[18]),
	.B(\reg_file[1] [18]),
	.S0(n_246),
	.Y(n_132));
   MX2X1 g3061__5107 (.A(ex_wb_alu_result[14]),
	.B(\reg_file[1] [14]),
	.S0(n_246),
	.Y(n_131));
   MX2X1 g3062__6260 (.A(ex_wb_alu_result[27]),
	.B(\reg_file[1] [27]),
	.S0(n_246),
	.Y(n_130));
   MX2X1 g3063__4319 (.A(ex_wb_alu_result[1]),
	.B(\reg_file[1] [1]),
	.S0(n_246),
	.Y(n_129));
   MX2X1 g3064__8428 (.A(ex_wb_alu_result[3]),
	.B(\reg_file[1] [3]),
	.S0(n_246),
	.Y(n_128));
   MX2X1 g3065__5526 (.A(ex_wb_alu_result[4]),
	.B(\reg_file[1] [4]),
	.S0(n_246),
	.Y(n_127));
   MX2X1 g3066__6783 (.A(ex_wb_alu_result[5]),
	.B(\reg_file[1] [5]),
	.S0(n_246),
	.Y(n_126));
   MX2X1 g3067__3680 (.A(ex_wb_alu_result[6]),
	.B(\reg_file[1] [6]),
	.S0(n_246),
	.Y(n_125));
   MX2X1 g3068__1617 (.A(ex_wb_alu_result[7]),
	.B(\reg_file[1] [7]),
	.S0(n_246),
	.Y(n_124));
   MX2X1 g3069__2802 (.A(ex_wb_alu_result[8]),
	.B(\reg_file[1] [8]),
	.S0(n_246),
	.Y(n_123));
   MX2X1 g3070__1705 (.A(ex_wb_alu_result[9]),
	.B(\reg_file[1] [9]),
	.S0(n_246),
	.Y(n_122));
   NAND2XL g3071__5122 (.A(id_ex_rd_addr[2]),
	.B(id_ex_reg_write),
	.Y(n_121));
   NAND2BX1 g3073__8246 (.AN(n_244),
	.B(n_248),
	.Y(n_118));
   NAND2XL g3074__7098 (.A(pc[0]),
	.B(pc[1]),
	.Y(n_120));
   NOR2X2 g3075__6131 (.A(n_115),
	.B(n_249),
	.Y(n_119));
   INVXL g3079 (.A(pc[0]),
	.Y(n_117));
   INVX1 g3080 (.A(ex_wb_reg_write),
	.Y(n_116));
   CLKINVX1 g3081 (.A(ex_wb_rd_addr[2]),
	.Y(n_115));
   INVX1 g3085 (.A(if_id_instr[2]),
	.Y(n_113));
   INVXL g3086 (.A(rst),
	.Y(n_0));
   SDFFRHQX1 \ex_wb_alu_result_reg[0]  (.CK(clk),
	.D(ex_alu_result[0]),
	.Q(ex_wb_alu_result[0]),
	.RN(n_0),
	.SE(SE),
	.SI(scan_in));
   SDFFRHQX1 \ex_wb_alu_result_reg[1]  (.CK(clk),
	.D(ex_alu_result[1]),
	.Q(ex_wb_alu_result[1]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[0]));
   SDFFRHQX1 \ex_wb_alu_result_reg[2]  (.CK(clk),
	.D(ex_alu_result[2]),
	.Q(ex_wb_alu_result[2]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[1]));
   SDFFRHQX1 \ex_wb_alu_result_reg[3]  (.CK(clk),
	.D(ex_alu_result[3]),
	.Q(ex_wb_alu_result[3]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[2]));
   SDFFRHQX1 \ex_wb_alu_result_reg[4]  (.CK(clk),
	.D(ex_alu_result[4]),
	.Q(ex_wb_alu_result[4]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[3]));
   SDFFRHQX1 \ex_wb_alu_result_reg[5]  (.CK(clk),
	.D(ex_alu_result[5]),
	.Q(ex_wb_alu_result[5]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[4]));
   SDFFRHQX1 \ex_wb_alu_result_reg[6]  (.CK(clk),
	.D(ex_alu_result[6]),
	.Q(ex_wb_alu_result[6]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[5]));
   SDFFRHQX1 \ex_wb_alu_result_reg[7]  (.CK(clk),
	.D(ex_alu_result[7]),
	.Q(ex_wb_alu_result[7]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[6]));
   SDFFRHQX1 \ex_wb_alu_result_reg[8]  (.CK(clk),
	.D(ex_alu_result[8]),
	.Q(ex_wb_alu_result[8]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[7]));
   SDFFRHQX1 \ex_wb_alu_result_reg[9]  (.CK(clk),
	.D(ex_alu_result[9]),
	.Q(ex_wb_alu_result[9]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[8]));
   SDFFRHQX1 \ex_wb_alu_result_reg[10]  (.CK(clk),
	.D(ex_alu_result[10]),
	.Q(ex_wb_alu_result[10]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[9]));
   SDFFRHQX1 \ex_wb_alu_result_reg[11]  (.CK(clk),
	.D(ex_alu_result[11]),
	.Q(ex_wb_alu_result[11]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[10]));
   SDFFRHQX1 \ex_wb_alu_result_reg[12]  (.CK(clk),
	.D(ex_alu_result[12]),
	.Q(ex_wb_alu_result[12]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[11]));
   SDFFRHQX1 \ex_wb_alu_result_reg[13]  (.CK(clk),
	.D(ex_alu_result[13]),
	.Q(ex_wb_alu_result[13]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[12]));
   SDFFRHQX1 \ex_wb_alu_result_reg[14]  (.CK(clk),
	.D(ex_alu_result[14]),
	.Q(ex_wb_alu_result[14]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[13]));
   SDFFRHQX1 \ex_wb_alu_result_reg[15]  (.CK(clk),
	.D(ex_alu_result[15]),
	.Q(ex_wb_alu_result[15]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[14]));
   SDFFRHQX1 \ex_wb_alu_result_reg[16]  (.CK(clk),
	.D(ex_alu_result[16]),
	.Q(ex_wb_alu_result[16]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[15]));
   SDFFRHQX1 \ex_wb_alu_result_reg[17]  (.CK(clk),
	.D(ex_alu_result[17]),
	.Q(ex_wb_alu_result[17]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[16]));
   SDFFRHQX1 \ex_wb_alu_result_reg[18]  (.CK(clk),
	.D(ex_alu_result[18]),
	.Q(ex_wb_alu_result[18]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[17]));
   SDFFRHQX1 \ex_wb_alu_result_reg[19]  (.CK(clk),
	.D(ex_alu_result[19]),
	.Q(ex_wb_alu_result[19]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[18]));
   SDFFRHQX1 \ex_wb_alu_result_reg[20]  (.CK(clk),
	.D(ex_alu_result[20]),
	.Q(ex_wb_alu_result[20]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[19]));
   SDFFRHQX1 \ex_wb_alu_result_reg[21]  (.CK(clk),
	.D(ex_alu_result[21]),
	.Q(ex_wb_alu_result[21]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[20]));
   SDFFRHQX1 \ex_wb_alu_result_reg[22]  (.CK(clk),
	.D(ex_alu_result[22]),
	.Q(ex_wb_alu_result[22]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[21]));
   SDFFRHQX1 \ex_wb_alu_result_reg[23]  (.CK(clk),
	.D(ex_alu_result[23]),
	.Q(ex_wb_alu_result[23]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[22]));
   SDFFRHQX1 \ex_wb_alu_result_reg[24]  (.CK(clk),
	.D(ex_alu_result[24]),
	.Q(ex_wb_alu_result[24]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[23]));
   SDFFRHQX1 \ex_wb_alu_result_reg[25]  (.CK(clk),
	.D(ex_alu_result[25]),
	.Q(ex_wb_alu_result[25]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[24]));
   SDFFRHQX1 \ex_wb_alu_result_reg[26]  (.CK(clk),
	.D(ex_alu_result[26]),
	.Q(ex_wb_alu_result[26]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[25]));
   SDFFRHQX1 \ex_wb_alu_result_reg[27]  (.CK(clk),
	.D(ex_alu_result[27]),
	.Q(ex_wb_alu_result[27]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[26]));
   SDFFRHQX1 \ex_wb_alu_result_reg[28]  (.CK(clk),
	.D(ex_alu_result[28]),
	.Q(ex_wb_alu_result[28]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[27]));
   SDFFRHQX1 \ex_wb_alu_result_reg[29]  (.CK(clk),
	.D(ex_alu_result[29]),
	.Q(ex_wb_alu_result[29]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[28]));
   SDFFRHQX1 \ex_wb_alu_result_reg[30]  (.CK(clk),
	.D(ex_alu_result[30]),
	.Q(ex_wb_alu_result[30]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[29]));
   SDFFRHQX1 \ex_wb_alu_result_reg[31]  (.CK(clk),
	.D(ex_alu_result[31]),
	.Q(ex_wb_alu_result[31]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_alu_result[30]));
   SDFFRHQX1 \ex_wb_rd_addr_reg[2]  (.CK(clk),
	.D(id_ex_rd_addr[2]),
	.Q(ex_wb_rd_addr[2]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_rd_addr[0]));
   SDFFRHQX1 ex_wb_reg_write_reg (.CK(clk),
	.D(id_ex_reg_write),
	.Q(ex_wb_reg_write),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_rd_addr[2]));
   SDFFRHQX1 \id_ex_data1_reg[0]  (.CK(clk),
	.D(n_106),
	.Q(id_ex_data1[0]),
	.RN(n_0),
	.SE(SE),
	.SI(ex_wb_reg_write));
   SDFFRHQX1 \id_ex_data1_reg[1]  (.CK(clk),
	.D(n_97),
	.Q(id_ex_data1[1]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[0]));
   SDFFRHQX1 \id_ex_data1_reg[2]  (.CK(clk),
	.D(n_111),
	.Q(id_ex_data1[2]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[1]));
   SDFFRHQX1 \id_ex_data1_reg[3]  (.CK(clk),
	.D(n_110),
	.Q(id_ex_data1[3]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[2]));
   SDFFRHQX1 \id_ex_data1_reg[4]  (.CK(clk),
	.D(n_109),
	.Q(id_ex_data1[4]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[3]));
   SDFFRHQX1 \id_ex_data1_reg[5]  (.CK(clk),
	.D(n_108),
	.Q(id_ex_data1[5]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[4]));
   SDFFRHQX1 \id_ex_data1_reg[6]  (.CK(clk),
	.D(n_107),
	.Q(id_ex_data1[6]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[5]));
   SDFFRHQX1 \id_ex_data1_reg[7]  (.CK(clk),
	.D(n_105),
	.Q(id_ex_data1[7]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[6]));
   SDFFRHQX1 \id_ex_data1_reg[8]  (.CK(clk),
	.D(n_104),
	.Q(id_ex_data1[8]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[7]));
   SDFFRHQX1 \id_ex_data1_reg[9]  (.CK(clk),
	.D(n_103),
	.Q(id_ex_data1[9]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[8]));
   SDFFRHQX1 \id_ex_data1_reg[10]  (.CK(clk),
	.D(n_102),
	.Q(id_ex_data1[10]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[9]));
   SDFFRHQX1 \id_ex_data1_reg[11]  (.CK(clk),
	.D(n_101),
	.Q(id_ex_data1[11]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[10]));
   SDFFRHQX1 \id_ex_data1_reg[12]  (.CK(clk),
	.D(n_100),
	.Q(id_ex_data1[12]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[11]));
   SDFFRHQX1 \id_ex_data1_reg[13]  (.CK(clk),
	.D(n_98),
	.Q(id_ex_data1[13]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[12]));
   SDFFRHQX1 \id_ex_data1_reg[14]  (.CK(clk),
	.D(n_99),
	.Q(id_ex_data1[14]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[13]));
   SDFFRHQX1 \id_ex_data1_reg[15]  (.CK(clk),
	.D(n_112),
	.Q(id_ex_data1[15]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[14]));
   SDFFRHQX1 \id_ex_data1_reg[16]  (.CK(clk),
	.D(n_81),
	.Q(id_ex_data1[16]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[15]));
   SDFFRHQX1 \id_ex_data1_reg[17]  (.CK(clk),
	.D(n_95),
	.Q(id_ex_data1[17]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[16]));
   SDFFRHQX1 \id_ex_data1_reg[18]  (.CK(clk),
	.D(n_94),
	.Q(id_ex_data1[18]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[17]));
   SDFFRHQX1 \id_ex_data1_reg[19]  (.CK(clk),
	.D(n_93),
	.Q(id_ex_data1[19]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[18]));
   SDFFRHQX1 \id_ex_data1_reg[20]  (.CK(clk),
	.D(n_92),
	.Q(id_ex_data1[20]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[19]));
   SDFFRHQX1 \id_ex_data1_reg[21]  (.CK(clk),
	.D(n_91),
	.Q(id_ex_data1[21]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[20]));
   SDFFRHQX1 \id_ex_data1_reg[22]  (.CK(clk),
	.D(n_90),
	.Q(id_ex_data1[22]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[21]));
   SDFFRHQX1 \id_ex_data1_reg[23]  (.CK(clk),
	.D(n_89),
	.Q(id_ex_data1[23]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[22]));
   SDFFRHQX1 \id_ex_data1_reg[24]  (.CK(clk),
	.D(n_88),
	.Q(id_ex_data1[24]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[23]));
   SDFFRHQX1 \id_ex_data1_reg[25]  (.CK(clk),
	.D(n_87),
	.Q(id_ex_data1[25]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[24]));
   SDFFRHQX1 \id_ex_data1_reg[26]  (.CK(clk),
	.D(n_86),
	.Q(id_ex_data1[26]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[25]));
   SDFFRHQX1 \id_ex_data1_reg[27]  (.CK(clk),
	.D(n_85),
	.Q(id_ex_data1[27]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[26]));
   SDFFRHQX1 \id_ex_data1_reg[28]  (.CK(clk),
	.D(n_82),
	.Q(id_ex_data1[28]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[27]));
   SDFFRHQX1 \id_ex_data1_reg[29]  (.CK(clk),
	.D(n_84),
	.Q(id_ex_data1[29]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[28]));
   SDFFRHQX1 \id_ex_data1_reg[30]  (.CK(clk),
	.D(n_83),
	.Q(id_ex_data1[30]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[29]));
   SDFFRHQX1 \id_ex_data1_reg[31]  (.CK(clk),
	.D(n_96),
	.Q(id_ex_data1[31]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[30]));
   SDFFRHQX1 \id_ex_data2_reg[0]  (.CK(clk),
	.D(n_71),
	.Q(id_ex_data2[0]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data1[31]));
   SDFFRHQX1 \id_ex_data2_reg[1]  (.CK(clk),
	.D(n_70),
	.Q(id_ex_data2[1]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[0]));
   SDFFRHQX1 \id_ex_data2_reg[2]  (.CK(clk),
	.D(n_69),
	.Q(id_ex_data2[2]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[1]));
   SDFFRHQX1 \id_ex_data2_reg[3]  (.CK(clk),
	.D(n_68),
	.Q(id_ex_data2[3]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[2]));
   SDFFRHQX1 \id_ex_data2_reg[4]  (.CK(clk),
	.D(n_67),
	.Q(id_ex_data2[4]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[3]));
   SDFFRHQX1 \id_ex_data2_reg[5]  (.CK(clk),
	.D(n_66),
	.Q(id_ex_data2[5]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[4]));
   SDFFRHQX1 \id_ex_data2_reg[6]  (.CK(clk),
	.D(n_65),
	.Q(id_ex_data2[6]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[5]));
   SDFFRHQX1 \id_ex_data2_reg[7]  (.CK(clk),
	.D(n_79),
	.Q(id_ex_data2[7]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[6]));
   SDFFRHQX1 \id_ex_data2_reg[8]  (.CK(clk),
	.D(n_32),
	.Q(id_ex_data2[8]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[7]));
   SDFFRHQX1 \id_ex_data2_reg[9]  (.CK(clk),
	.D(n_46),
	.Q(id_ex_data2[9]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[8]));
   SDFFRHQX1 \id_ex_data2_reg[10]  (.CK(clk),
	.D(n_45),
	.Q(id_ex_data2[10]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[9]));
   SDFFRHQX1 \id_ex_data2_reg[11]  (.CK(clk),
	.D(n_44),
	.Q(id_ex_data2[11]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[10]));
   SDFFRHQX1 \id_ex_data2_reg[12]  (.CK(clk),
	.D(n_43),
	.Q(id_ex_data2[12]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[11]));
   SDFFRHQX1 \id_ex_data2_reg[13]  (.CK(clk),
	.D(n_42),
	.Q(id_ex_data2[13]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[12]));
   SDFFRHQX1 \id_ex_data2_reg[14]  (.CK(clk),
	.D(n_41),
	.Q(id_ex_data2[14]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[13]));
   SDFFRHQX1 \id_ex_data2_reg[15]  (.CK(clk),
	.D(n_40),
	.Q(id_ex_data2[15]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[14]));
   SDFFRHQX1 \id_ex_data2_reg[16]  (.CK(clk),
	.D(n_39),
	.Q(id_ex_data2[16]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[15]));
   SDFFRHQX1 \id_ex_data2_reg[17]  (.CK(clk),
	.D(n_38),
	.Q(id_ex_data2[17]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[16]));
   SDFFRHQX1 \id_ex_data2_reg[18]  (.CK(clk),
	.D(n_37),
	.Q(id_ex_data2[18]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[17]));
   SDFFRHQX1 \id_ex_data2_reg[19]  (.CK(clk),
	.D(n_35),
	.Q(id_ex_data2[19]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[18]));
   SDFFRHQX1 \id_ex_data2_reg[20]  (.CK(clk),
	.D(n_36),
	.Q(id_ex_data2[20]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[19]));
   SDFFRHQX1 \id_ex_data2_reg[21]  (.CK(clk),
	.D(n_34),
	.Q(id_ex_data2[21]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[20]));
   SDFFRHQX1 \id_ex_data2_reg[22]  (.CK(clk),
	.D(n_33),
	.Q(id_ex_data2[22]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[21]));
   SDFFRHQX1 \id_ex_data2_reg[23]  (.CK(clk),
	.D(n_47),
	.Q(id_ex_data2[23]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[22]));
   SDFFRHQX1 \id_ex_data2_reg[24]  (.CK(clk),
	.D(n_78),
	.Q(id_ex_data2[24]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[23]));
   SDFFRHQX1 \id_ex_data2_reg[25]  (.CK(clk),
	.D(n_64),
	.Q(id_ex_data2[25]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[24]));
   SDFFRHQX1 \id_ex_data2_reg[26]  (.CK(clk),
	.D(n_77),
	.Q(id_ex_data2[26]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[25]));
   SDFFRHQX1 \id_ex_data2_reg[27]  (.CK(clk),
	.D(n_76),
	.Q(id_ex_data2[27]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[26]));
   SDFFRHQX1 \id_ex_data2_reg[28]  (.CK(clk),
	.D(n_75),
	.Q(id_ex_data2[28]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[27]));
   SDFFRHQX1 \id_ex_data2_reg[29]  (.CK(clk),
	.D(n_74),
	.Q(id_ex_data2[29]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[28]));
   SDFFRHQX1 \id_ex_data2_reg[30]  (.CK(clk),
	.D(n_73),
	.Q(id_ex_data2[30]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[29]));
   SDFFRHQX1 \id_ex_data2_reg[31]  (.CK(clk),
	.D(n_72),
	.Q(id_ex_data2[31]),
	.RN(n_0),
	.SE(SE),
	.SI(id_ex_data2[30]));
   AND2X1 g4060__1881 (.A(\reg_file[1] [15]),
	.B(n_80),
	.Y(n_112));
   AND2X1 g4061__5115 (.A(\reg_file[1] [2]),
	.B(n_80),
	.Y(n_111));
   AND2X1 g4062__7482 (.A(\reg_file[1] [3]),
	.B(n_80),
	.Y(n_110));
   AND2X1 g4063__4733 (.A(\reg_file[1] [4]),
	.B(n_80),
	.Y(n_109));
   AND2X1 g4064__6161 (.A(\reg_file[1] [5]),
	.B(n_80),
	.Y(n_108));
   AND2X1 g4065__9315 (.A(\reg_file[1] [6]),
	.B(n_80),
	.Y(n_107));
   AND2X1 g4066__9945 (.A(\reg_file[1] [0]),
	.B(n_80),
	.Y(n_106));
   AND2X1 g4067__2883 (.A(\reg_file[1] [7]),
	.B(n_80),
	.Y(n_105));
   AND2X1 g4068__2346 (.A(\reg_file[1] [8]),
	.B(n_80),
	.Y(n_104));
   AND2X1 g4069__1666 (.A(\reg_file[1] [9]),
	.B(n_80),
	.Y(n_103));
   AND2X1 g4070__7410 (.A(\reg_file[1] [10]),
	.B(n_80),
	.Y(n_102));
   AND2X1 g4071__6417 (.A(\reg_file[1] [11]),
	.B(n_80),
	.Y(n_101));
   AND2X1 g4072__5477 (.A(\reg_file[1] [12]),
	.B(n_80),
	.Y(n_100));
   AND2X1 g4073__2398 (.A(\reg_file[1] [14]),
	.B(n_80),
	.Y(n_99));
   AND2X1 g4074__5107 (.A(\reg_file[1] [13]),
	.B(n_80),
	.Y(n_98));
   AND2X1 g4075__6260 (.A(\reg_file[1] [1]),
	.B(n_80),
	.Y(n_97));
   AND2X1 g4076__4319 (.A(\reg_file[1] [31]),
	.B(n_80),
	.Y(n_96));
   AND2X1 g4077__8428 (.A(\reg_file[1] [17]),
	.B(n_80),
	.Y(n_95));
   AND2X1 g4078__5526 (.A(\reg_file[1] [18]),
	.B(n_80),
	.Y(n_94));
   AND2X1 g4079__6783 (.A(\reg_file[1] [19]),
	.B(n_80),
	.Y(n_93));
   AND2X1 g4080__3680 (.A(\reg_file[1] [20]),
	.B(n_80),
	.Y(n_92));
   AND2X1 g4081__1617 (.A(\reg_file[1] [21]),
	.B(n_80),
	.Y(n_91));
   AND2X1 g4082__2802 (.A(\reg_file[1] [22]),
	.B(n_80),
	.Y(n_90));
   AND2X1 g4083__1705 (.A(\reg_file[1] [23]),
	.B(n_80),
	.Y(n_89));
   AND2X1 g4084__5122 (.A(\reg_file[1] [24]),
	.B(n_80),
	.Y(n_88));
   AND2X1 g4085__8246 (.A(\reg_file[1] [25]),
	.B(n_80),
	.Y(n_87));
   AND2X1 g4086__7098 (.A(\reg_file[1] [26]),
	.B(n_80),
	.Y(n_86));
   AND2X1 g4087__6131 (.A(\reg_file[1] [27]),
	.B(n_80),
	.Y(n_85));
   AND2X1 g4088__1881 (.A(\reg_file[1] [29]),
	.B(n_80),
	.Y(n_84));
   AND2X1 g4089__5115 (.A(\reg_file[1] [30]),
	.B(n_80),
	.Y(n_83));
   AND2X1 g4090__7482 (.A(\reg_file[1] [28]),
	.B(n_80),
	.Y(n_82));
   AND2X1 g4091__4733 (.A(\reg_file[1] [16]),
	.B(n_80),
	.Y(n_81));
   OR3X1 g4124__6161 (.A(n_6),
	.B(n_11),
	.C(n_15),
	.Y(n_80));
   INVX1 g4125 (.A(n_63),
	.Y(n_79));
   INVX1 g4126 (.A(n_62),
	.Y(n_78));
   INVX1 g4127 (.A(n_61),
	.Y(n_77));
   INVX1 g4128 (.A(n_60),
	.Y(n_76));
   INVX1 g4129 (.A(n_59),
	.Y(n_75));
   INVX1 g4130 (.A(n_58),
	.Y(n_74));
   INVX1 g4131 (.A(n_57),
	.Y(n_73));
   INVX1 g4132 (.A(n_56),
	.Y(n_72));
   INVX1 g4133 (.A(n_55),
	.Y(n_71));
   INVX1 g4134 (.A(n_54),
	.Y(n_70));
   INVX1 g4135 (.A(n_53),
	.Y(n_69));
   INVX1 g4136 (.A(n_52),
	.Y(n_68));
   INVX1 g4137 (.A(n_51),
	.Y(n_67));
   INVX1 g4138 (.A(n_50),
	.Y(n_66));
   INVX1 g4139 (.A(n_49),
	.Y(n_65));
   INVX1 g4140 (.A(n_48),
	.Y(n_64));
   AOI222XL g4141__9315 (.A0(\reg_file[1] [7]),
	.A1(n_9),
	.B0(debug_reg_r4[7]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [7]),
	.Y(n_63));
   AOI222XL g4142__9945 (.A0(\reg_file[1] [24]),
	.A1(n_9),
	.B0(debug_reg_r4[24]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [24]),
	.Y(n_62));
   AOI222XL g4143__2883 (.A0(\reg_file[1] [26]),
	.A1(n_9),
	.B0(debug_reg_r4[26]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [26]),
	.Y(n_61));
   AOI222XL g4144__2346 (.A0(\reg_file[1] [27]),
	.A1(n_9),
	.B0(debug_reg_r4[27]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [27]),
	.Y(n_60));
   AOI222XL g4145__1666 (.A0(\reg_file[1] [28]),
	.A1(n_9),
	.B0(debug_reg_r4[28]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [28]),
	.Y(n_59));
   AOI222XL g4146__7410 (.A0(\reg_file[1] [29]),
	.A1(n_9),
	.B0(debug_reg_r4[29]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [29]),
	.Y(n_58));
   AOI222XL g4147__6417 (.A0(\reg_file[1] [30]),
	.A1(n_9),
	.B0(debug_reg_r4[30]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [30]),
	.Y(n_57));
   AOI222XL g4148__5477 (.A0(\reg_file[1] [31]),
	.A1(n_9),
	.B0(debug_reg_r4[31]),
	.B1(n_14),
	.C0(n_2),
	.C1(scan_out),
	.Y(n_56));
   AOI222XL g4149__2398 (.A0(\reg_file[1] [0]),
	.A1(n_9),
	.B0(debug_reg_r4[0]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [0]),
	.Y(n_55));
   AOI222XL g4150__5107 (.A0(\reg_file[1] [1]),
	.A1(n_9),
	.B0(debug_reg_r4[1]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [1]),
	.Y(n_54));
   AOI222XL g4151__6260 (.A0(\reg_file[1] [2]),
	.A1(n_9),
	.B0(debug_reg_r4[2]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [2]),
	.Y(n_53));
   AOI222XL g4152__4319 (.A0(\reg_file[1] [3]),
	.A1(n_9),
	.B0(debug_reg_r4[3]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [3]),
	.Y(n_52));
   AOI222XL g4153__8428 (.A0(\reg_file[1] [4]),
	.A1(n_9),
	.B0(debug_reg_r4[4]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [4]),
	.Y(n_51));
   AOI222XL g4154__5526 (.A0(\reg_file[1] [5]),
	.A1(n_9),
	.B0(debug_reg_r4[5]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [5]),
	.Y(n_50));
   AOI222XL g4155__6783 (.A0(\reg_file[1] [6]),
	.A1(n_9),
	.B0(debug_reg_r4[6]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [6]),
	.Y(n_49));
   AOI222XL g4156__3680 (.A0(\reg_file[1] [25]),
	.A1(n_9),
	.B0(debug_reg_r4[25]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [25]),
	.Y(n_48));
   INVX1 g4157 (.A(n_31),
	.Y(n_47));
   INVX1 g4158 (.A(n_30),
	.Y(n_46));
   INVX1 g4159 (.A(n_29),
	.Y(n_45));
   INVX1 g4160 (.A(n_28),
	.Y(n_44));
   INVX1 g4161 (.A(n_27),
	.Y(n_43));
   INVX1 g4162 (.A(n_26),
	.Y(n_42));
   INVX1 g4163 (.A(n_25),
	.Y(n_41));
   INVX1 g4164 (.A(n_24),
	.Y(n_40));
   INVX1 g4165 (.A(n_23),
	.Y(n_39));
   INVX1 g4166 (.A(n_22),
	.Y(n_38));
   INVX1 g4167 (.A(n_21),
	.Y(n_37));
   INVX1 g4168 (.A(n_20),
	.Y(n_36));
   INVX1 g4169 (.A(n_19),
	.Y(n_35));
   INVX1 g4170 (.A(n_18),
	.Y(n_34));
   INVX1 g4171 (.A(n_17),
	.Y(n_33));
   INVX1 g4172 (.A(n_16),
	.Y(n_32));
   AOI222XL g4173__1617 (.A0(\reg_file[1] [23]),
	.A1(n_9),
	.B0(debug_reg_r4[23]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [23]),
	.Y(n_31));
   AOI222XL g4174__2802 (.A0(\reg_file[1] [9]),
	.A1(n_9),
	.B0(debug_reg_r4[9]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [9]),
	.Y(n_30));
   AOI222XL g4175__1705 (.A0(\reg_file[1] [10]),
	.A1(n_9),
	.B0(debug_reg_r4[10]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [10]),
	.Y(n_29));
   AOI222XL g4176__5122 (.A0(\reg_file[1] [11]),
	.A1(n_9),
	.B0(debug_reg_r4[11]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [11]),
	.Y(n_28));
   AOI222XL g4177__8246 (.A0(\reg_file[1] [12]),
	.A1(n_9),
	.B0(debug_reg_r4[12]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [12]),
	.Y(n_27));
   AOI222XL g4178__7098 (.A0(\reg_file[1] [13]),
	.A1(n_9),
	.B0(debug_reg_r4[13]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [13]),
	.Y(n_26));
   AOI222XL g4179__6131 (.A0(\reg_file[1] [14]),
	.A1(n_9),
	.B0(debug_reg_r4[14]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [14]),
	.Y(n_25));
   AOI222XL g4180__1881 (.A0(\reg_file[1] [15]),
	.A1(n_9),
	.B0(debug_reg_r4[15]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [15]),
	.Y(n_24));
   AOI222XL g4181__5115 (.A0(\reg_file[1] [16]),
	.A1(n_9),
	.B0(debug_reg_r4[16]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [16]),
	.Y(n_23));
   AOI222XL g4182__7482 (.A0(\reg_file[1] [17]),
	.A1(n_9),
	.B0(debug_reg_r4[17]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [17]),
	.Y(n_22));
   AOI222XL g4183__4733 (.A0(\reg_file[1] [18]),
	.A1(n_9),
	.B0(debug_reg_r4[18]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [18]),
	.Y(n_21));
   AOI222XL g4184__6161 (.A0(\reg_file[1] [20]),
	.A1(n_9),
	.B0(debug_reg_r4[20]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [20]),
	.Y(n_20));
   AOI222XL g4185__9315 (.A0(\reg_file[1] [19]),
	.A1(n_9),
	.B0(debug_reg_r4[19]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [19]),
	.Y(n_19));
   AOI222XL g4186__9945 (.A0(\reg_file[1] [21]),
	.A1(n_9),
	.B0(debug_reg_r4[21]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [21]),
	.Y(n_18));
   AOI222XL g4187__2883 (.A0(\reg_file[1] [22]),
	.A1(n_9),
	.B0(debug_reg_r4[22]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [22]),
	.Y(n_17));
   AOI222XL g4188__2346 (.A0(\reg_file[1] [8]),
	.A1(n_9),
	.B0(debug_reg_r4[8]),
	.B1(n_14),
	.C0(n_2),
	.C1(\reg_file[5] [8]),
	.Y(n_16));
   OAI33X1 g4189__1666 (.A0(if_id_instr[2]),
	.A1(n_247),
	.A2(n_12),
	.B0(id_ex_rd_addr[0]),
	.B1(n_1),
	.B2(n_244),
	.Y(n_15));
   NOR2BX1 g4190__7410 (.AN(n_13),
	.B(if_id_instr[2]),
	.Y(n_14));
   AOI211X1 g4191__6417 (.A0(n_4),
	.A1(n_7),
	.B0(n_247),
	.C0(n_10),
	.Y(n_13));
   OA22XL g4192__5477 (.A0(n_4),
	.A1(n_10),
	.B0(n_3),
	.B1(n_7),
	.Y(n_12));
   NOR3BX1 g4193__2398 (.AN(n_8),
	.B(n_247),
	.C(n_7),
	.Y(n_11));
   NOR2BX1 g4194__5107 (.AN(n_3),
	.B(n_8),
	.Y(n_10));
   AND2X1 g4195__6260 (.A(if_id_instr[2]),
	.B(n_5),
	.Y(n_9));
   OAI21X1 g4196__4319 (.A0(id_ex_rd_addr[2]),
	.A1(id_ex_rd_addr[0]),
	.B0(id_ex_reg_write),
	.Y(n_8));
   OA21X1 g4197__8428 (.A0(ex_wb_rd_addr[0]),
	.A1(ex_wb_rd_addr[2]),
	.B0(ex_wb_reg_write),
	.Y(n_7));
   NOR3X1 g4198__5526 (.A(id_ex_reg_write),
	.B(ex_wb_rd_addr[0]),
	.C(n_244),
	.Y(n_6));
   NOR3X1 g4199__6783 (.A(if_id_instr[4]),
	.B(if_id_instr[3]),
	.C(n_245),
	.Y(n_5));
   NAND2XL g4234__3680 (.A(ex_wb_rd_addr[0]),
	.B(ex_wb_rd_addr[2]),
	.Y(n_4));
   NAND2XL g4235__1617 (.A(id_ex_rd_addr[2]),
	.B(id_ex_rd_addr[0]),
	.Y(n_3));
   NOR2X1 g4236__2802 (.A(n_248),
	.B(n_244),
	.Y(n_2));
   INVX1 g4237 (.A(n_249),
	.Y(n_1));
   OAI21X1 add_156_40_g750__1705 (.A0(add_156_40_n_1),
	.A1(add_156_40_n_62),
	.B0(add_156_40_n_63),
	.Y(ex_alu_result[31]));
   NAND2XL add_156_40_g751__5122 (.A(add_156_40_n_1),
	.B(add_156_40_n_62),
	.Y(add_156_40_n_63));
   ADDFX1 add_156_40_g752__8246 (.A(id_ex_data2[30]),
	.B(id_ex_data1[30]),
	.CI(add_156_40_n_59),
	.CO(add_156_40_n_62),
	.S(ex_alu_result[30]));
   ADDFX1 add_156_40_g753__7098 (.A(id_ex_data2[29]),
	.B(id_ex_data1[29]),
	.CI(add_156_40_n_57),
	.CO(add_156_40_n_59),
	.S(ex_alu_result[29]));
   ADDFX1 add_156_40_g754__6131 (.A(id_ex_data2[28]),
	.B(id_ex_data1[28]),
	.CI(add_156_40_n_55),
	.CO(add_156_40_n_57),
	.S(ex_alu_result[28]));
   ADDFX1 add_156_40_g755__1881 (.A(id_ex_data2[27]),
	.B(id_ex_data1[27]),
	.CI(add_156_40_n_53),
	.CO(add_156_40_n_55),
	.S(ex_alu_result[27]));
   ADDFX1 add_156_40_g756__5115 (.A(id_ex_data2[26]),
	.B(id_ex_data1[26]),
	.CI(add_156_40_n_51),
	.CO(add_156_40_n_53),
	.S(ex_alu_result[26]));
   ADDFX1 add_156_40_g757__7482 (.A(id_ex_data2[25]),
	.B(id_ex_data1[25]),
	.CI(add_156_40_n_49),
	.CO(add_156_40_n_51),
	.S(ex_alu_result[25]));
   ADDFX1 add_156_40_g758__4733 (.A(id_ex_data2[24]),
	.B(id_ex_data1[24]),
	.CI(add_156_40_n_47),
	.CO(add_156_40_n_49),
	.S(ex_alu_result[24]));
   ADDFX1 add_156_40_g759__6161 (.A(id_ex_data2[23]),
	.B(id_ex_data1[23]),
	.CI(add_156_40_n_45),
	.CO(add_156_40_n_47),
	.S(ex_alu_result[23]));
   ADDFX1 add_156_40_g760__9315 (.A(id_ex_data2[22]),
	.B(id_ex_data1[22]),
	.CI(add_156_40_n_43),
	.CO(add_156_40_n_45),
	.S(ex_alu_result[22]));
   ADDFX1 add_156_40_g761__9945 (.A(id_ex_data2[21]),
	.B(id_ex_data1[21]),
	.CI(add_156_40_n_41),
	.CO(add_156_40_n_43),
	.S(ex_alu_result[21]));
   ADDFX1 add_156_40_g762__2883 (.A(id_ex_data2[20]),
	.B(id_ex_data1[20]),
	.CI(add_156_40_n_39),
	.CO(add_156_40_n_41),
	.S(ex_alu_result[20]));
   ADDFX1 add_156_40_g763__2346 (.A(id_ex_data2[19]),
	.B(id_ex_data1[19]),
	.CI(add_156_40_n_37),
	.CO(add_156_40_n_39),
	.S(ex_alu_result[19]));
   ADDFX1 add_156_40_g764__1666 (.A(id_ex_data2[18]),
	.B(id_ex_data1[18]),
	.CI(add_156_40_n_35),
	.CO(add_156_40_n_37),
	.S(ex_alu_result[18]));
   ADDFX1 add_156_40_g765__7410 (.A(id_ex_data2[17]),
	.B(id_ex_data1[17]),
	.CI(add_156_40_n_33),
	.CO(add_156_40_n_35),
	.S(ex_alu_result[17]));
   ADDFX1 add_156_40_g766__6417 (.A(id_ex_data2[16]),
	.B(id_ex_data1[16]),
	.CI(add_156_40_n_31),
	.CO(add_156_40_n_33),
	.S(ex_alu_result[16]));
   ADDFX1 add_156_40_g767__5477 (.A(id_ex_data2[15]),
	.B(id_ex_data1[15]),
	.CI(add_156_40_n_29),
	.CO(add_156_40_n_31),
	.S(ex_alu_result[15]));
   ADDFX1 add_156_40_g768__2398 (.A(id_ex_data2[14]),
	.B(id_ex_data1[14]),
	.CI(add_156_40_n_27),
	.CO(add_156_40_n_29),
	.S(ex_alu_result[14]));
   ADDFX1 add_156_40_g769__5107 (.A(id_ex_data2[13]),
	.B(id_ex_data1[13]),
	.CI(add_156_40_n_25),
	.CO(add_156_40_n_27),
	.S(ex_alu_result[13]));
   ADDFX1 add_156_40_g770__6260 (.A(id_ex_data2[12]),
	.B(id_ex_data1[12]),
	.CI(add_156_40_n_23),
	.CO(add_156_40_n_25),
	.S(ex_alu_result[12]));
   ADDFX1 add_156_40_g771__4319 (.A(id_ex_data2[11]),
	.B(id_ex_data1[11]),
	.CI(add_156_40_n_21),
	.CO(add_156_40_n_23),
	.S(ex_alu_result[11]));
   ADDFX1 add_156_40_g772__8428 (.A(id_ex_data2[10]),
	.B(id_ex_data1[10]),
	.CI(add_156_40_n_19),
	.CO(add_156_40_n_21),
	.S(ex_alu_result[10]));
   ADDFX1 add_156_40_g773__5526 (.A(id_ex_data2[9]),
	.B(id_ex_data1[9]),
	.CI(add_156_40_n_17),
	.CO(add_156_40_n_19),
	.S(ex_alu_result[9]));
   ADDFX1 add_156_40_g774__6783 (.A(id_ex_data2[8]),
	.B(id_ex_data1[8]),
	.CI(add_156_40_n_15),
	.CO(add_156_40_n_17),
	.S(ex_alu_result[8]));
   ADDFX1 add_156_40_g775__3680 (.A(id_ex_data2[7]),
	.B(id_ex_data1[7]),
	.CI(add_156_40_n_13),
	.CO(add_156_40_n_15),
	.S(ex_alu_result[7]));
   ADDFX1 add_156_40_g776__1617 (.A(id_ex_data2[6]),
	.B(id_ex_data1[6]),
	.CI(add_156_40_n_11),
	.CO(add_156_40_n_13),
	.S(ex_alu_result[6]));
   ADDFX1 add_156_40_g777__2802 (.A(id_ex_data2[5]),
	.B(id_ex_data1[5]),
	.CI(add_156_40_n_9),
	.CO(add_156_40_n_11),
	.S(ex_alu_result[5]));
   ADDFX1 add_156_40_g778__1705 (.A(id_ex_data2[4]),
	.B(id_ex_data1[4]),
	.CI(add_156_40_n_7),
	.CO(add_156_40_n_9),
	.S(ex_alu_result[4]));
   ADDFX1 add_156_40_g779__5122 (.A(id_ex_data2[3]),
	.B(id_ex_data1[3]),
	.CI(add_156_40_n_5),
	.CO(add_156_40_n_7),
	.S(ex_alu_result[3]));
   ADDFX1 add_156_40_g780__8246 (.A(id_ex_data2[2]),
	.B(id_ex_data1[2]),
	.CI(add_156_40_n_3),
	.CO(add_156_40_n_5),
	.S(ex_alu_result[2]));
   ADDFX1 add_156_40_g781__7098 (.A(id_ex_data2[1]),
	.B(id_ex_data1[1]),
	.CI(add_156_40_n_0),
	.CO(add_156_40_n_3),
	.S(ex_alu_result[1]));
   AOI2BB1X1 add_156_40_g782__6131 (.A0N(id_ex_data1[0]),
	.A1N(id_ex_data2[0]),
	.B0(add_156_40_n_0),
	.Y(ex_alu_result[0]));
   XNOR2X1 add_156_40_g783__1881 (.A(id_ex_data1[31]),
	.B(id_ex_data2[31]),
	.Y(add_156_40_n_1));
   AND2X1 add_156_40_g784__5115 (.A(id_ex_data2[0]),
	.B(id_ex_data1[0]),
	.Y(add_156_40_n_0));
   AND3XL g2 (.A(n_117),
	.B(n_156),
	.C(n_227),
	.Y(n_252));
endmodule

