/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID ic312.vit.ac.in)
#  Generated on:      Fri Nov  7 17:51:58 2025
#  Design:            resource_shared_datapath
#  Command:           saveNetlist resource_shared_datapath.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Nov  4 2025 19:25:01 IST (Nov  4 2025 13:55:01 UTC)
// Verification Directory fv/resource_shared_datapath 
module resource_shared_datapath (
	clk, 
	rst_n, 
	start, 
	A, 
	B, 
	C, 
	D, 
	Z, 
	done, 
	SE, 
	scan_in, 
	scan_out);
   input clk;
   input rst_n;
   input start;
   input [7:0] A;
   input [7:0] B;
   input [7:0] C;
   input [7:0] D;
   output [17:0] Z;
   output done;
   input SE;
   input scan_in;
   output scan_out;

   // Internal wires
   wire [2:0] state;
   wire [7:0] a_reg;
   wire [7:0] b_reg;
   wire [7:0] c_reg;
   wire [7:0] d_reg;
   wire [8:0] temp1_reg;
   wire [8:0] temp2_reg;
   wire [17:0] mul_out;
   wire mul_121_41_n_0;
   wire mul_121_41_n_1;
   wire mul_121_41_n_2;
   wire mul_121_41_n_3;
   wire mul_121_41_n_4;
   wire mul_121_41_n_5;
   wire mul_121_41_n_6;
   wire mul_121_41_n_7;
   wire mul_121_41_n_8;
   wire mul_121_41_n_10;
   wire mul_121_41_n_11;
   wire mul_121_41_n_12;
   wire mul_121_41_n_13;
   wire mul_121_41_n_14;
   wire mul_121_41_n_15;
   wire mul_121_41_n_16;
   wire mul_121_41_n_17;
   wire mul_121_41_n_18;
   wire mul_121_41_n_19;
   wire mul_121_41_n_20;
   wire mul_121_41_n_21;
   wire mul_121_41_n_22;
   wire mul_121_41_n_23;
   wire mul_121_41_n_24;
   wire mul_121_41_n_25;
   wire mul_121_41_n_26;
   wire mul_121_41_n_27;
   wire mul_121_41_n_28;
   wire mul_121_41_n_29;
   wire mul_121_41_n_30;
   wire mul_121_41_n_31;
   wire mul_121_41_n_32;
   wire mul_121_41_n_33;
   wire mul_121_41_n_34;
   wire mul_121_41_n_35;
   wire mul_121_41_n_36;
   wire mul_121_41_n_37;
   wire mul_121_41_n_38;
   wire mul_121_41_n_39;
   wire mul_121_41_n_40;
   wire mul_121_41_n_41;
   wire mul_121_41_n_42;
   wire mul_121_41_n_43;
   wire mul_121_41_n_44;
   wire mul_121_41_n_45;
   wire mul_121_41_n_46;
   wire mul_121_41_n_48;
   wire mul_121_41_n_49;
   wire mul_121_41_n_50;
   wire mul_121_41_n_51;
   wire mul_121_41_n_53;
   wire mul_121_41_n_54;
   wire mul_121_41_n_55;
   wire mul_121_41_n_56;
   wire mul_121_41_n_57;
   wire mul_121_41_n_58;
   wire mul_121_41_n_59;
   wire mul_121_41_n_60;
   wire mul_121_41_n_61;
   wire mul_121_41_n_62;
   wire mul_121_41_n_63;
   wire mul_121_41_n_64;
   wire mul_121_41_n_65;
   wire mul_121_41_n_66;
   wire mul_121_41_n_67;
   wire mul_121_41_n_68;
   wire mul_121_41_n_69;
   wire mul_121_41_n_70;
   wire mul_121_41_n_71;
   wire mul_121_41_n_72;
   wire mul_121_41_n_73;
   wire mul_121_41_n_74;
   wire mul_121_41_n_75;
   wire mul_121_41_n_76;
   wire mul_121_41_n_77;
   wire mul_121_41_n_78;
   wire mul_121_41_n_79;
   wire mul_121_41_n_80;
   wire mul_121_41_n_81;
   wire mul_121_41_n_82;
   wire mul_121_41_n_83;
   wire mul_121_41_n_84;
   wire mul_121_41_n_85;
   wire mul_121_41_n_86;
   wire mul_121_41_n_87;
   wire mul_121_41_n_88;
   wire mul_121_41_n_89;
   wire mul_121_41_n_90;
   wire mul_121_41_n_91;
   wire mul_121_41_n_92;
   wire mul_121_41_n_93;
   wire mul_121_41_n_94;
   wire mul_121_41_n_95;
   wire mul_121_41_n_96;
   wire mul_121_41_n_97;
   wire mul_121_41_n_98;
   wire mul_121_41_n_99;
   wire mul_121_41_n_100;
   wire mul_121_41_n_101;
   wire mul_121_41_n_102;
   wire mul_121_41_n_103;
   wire mul_121_41_n_104;
   wire mul_121_41_n_105;
   wire mul_121_41_n_106;
   wire mul_121_41_n_107;
   wire mul_121_41_n_108;
   wire mul_121_41_n_109;
   wire mul_121_41_n_110;
   wire mul_121_41_n_111;
   wire mul_121_41_n_112;
   wire mul_121_41_n_113;
   wire mul_121_41_n_114;
   wire mul_121_41_n_115;
   wire mul_121_41_n_116;
   wire mul_121_41_n_117;
   wire mul_121_41_n_118;
   wire mul_121_41_n_119;
   wire mul_121_41_n_120;
   wire mul_121_41_n_121;
   wire mul_121_41_n_122;
   wire mul_121_41_n_123;
   wire mul_121_41_n_124;
   wire mul_121_41_n_125;
   wire mul_121_41_n_126;
   wire mul_121_41_n_127;
   wire mul_121_41_n_128;
   wire mul_121_41_n_129;
   wire mul_121_41_n_130;
   wire mul_121_41_n_131;
   wire mul_121_41_n_132;
   wire mul_121_41_n_133;
   wire mul_121_41_n_134;
   wire mul_121_41_n_135;
   wire mul_121_41_n_136;
   wire mul_121_41_n_137;
   wire mul_121_41_n_138;
   wire mul_121_41_n_139;
   wire mul_121_41_n_140;
   wire mul_121_41_n_141;
   wire mul_121_41_n_142;
   wire mul_121_41_n_143;
   wire mul_121_41_n_144;
   wire mul_121_41_n_145;
   wire mul_121_41_n_146;
   wire mul_121_41_n_147;
   wire mul_121_41_n_148;
   wire mul_121_41_n_149;
   wire mul_121_41_n_150;
   wire mul_121_41_n_151;
   wire mul_121_41_n_152;
   wire mul_121_41_n_153;
   wire mul_121_41_n_154;
   wire mul_121_41_n_155;
   wire mul_121_41_n_157;
   wire mul_121_41_n_158;
   wire mul_121_41_n_159;
   wire mul_121_41_n_160;
   wire mul_121_41_n_161;
   wire mul_121_41_n_162;
   wire mul_121_41_n_163;
   wire mul_121_41_n_164;
   wire mul_121_41_n_165;
   wire mul_121_41_n_166;
   wire mul_121_41_n_167;
   wire mul_121_41_n_169;
   wire mul_121_41_n_170;
   wire mul_121_41_n_171;
   wire mul_121_41_n_172;
   wire mul_121_41_n_173;
   wire mul_121_41_n_174;
   wire mul_121_41_n_175;
   wire mul_121_41_n_176;
   wire mul_121_41_n_177;
   wire mul_121_41_n_178;
   wire mul_121_41_n_179;
   wire mul_121_41_n_180;
   wire mul_121_41_n_181;
   wire mul_121_41_n_182;
   wire mul_121_41_n_183;
   wire mul_121_41_n_184;
   wire mul_121_41_n_185;
   wire mul_121_41_n_186;
   wire mul_121_41_n_187;
   wire mul_121_41_n_188;
   wire mul_121_41_n_189;
   wire mul_121_41_n_191;
   wire mul_121_41_n_192;
   wire mul_121_41_n_193;
   wire mul_121_41_n_194;
   wire mul_121_41_n_195;
   wire mul_121_41_n_196;
   wire mul_121_41_n_197;
   wire mul_121_41_n_198;
   wire mul_121_41_n_199;
   wire mul_121_41_n_200;
   wire mul_121_41_n_201;
   wire mul_121_41_n_202;
   wire mul_121_41_n_203;
   wire mul_121_41_n_205;
   wire mul_121_41_n_206;
   wire mul_121_41_n_207;
   wire mul_121_41_n_208;
   wire mul_121_41_n_209;
   wire mul_121_41_n_210;
   wire mul_121_41_n_211;
   wire mul_121_41_n_213;
   wire mul_121_41_n_215;
   wire mul_121_41_n_217;
   wire mul_121_41_n_219;
   wire mul_121_41_n_221;
   wire mul_121_41_n_223;
   wire mul_121_41_n_225;
   wire mul_121_41_n_227;
   wire mul_121_41_n_229;
   wire mul_121_41_n_231;
   wire mul_121_41_n_233;
   wire n_0;
   wire n_1;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_131;
   wire n_132;
   wire n_133;
   wire n_134;
   wire n_135;
   wire n_136;
   wire n_137;
   wire n_138;
   wire n_139;
   wire n_140;
   wire n_141;

   assign scan_out = Z[17] ;

   NOR3BXL g1110__2398 (.AN(state[2]),
	.B(state[0]),
	.C(state[1]),
	.Y(done));
   SDFFRHQX1 \a_reg_reg[0]  (.CK(clk),
	.D(n_83),
	.Q(a_reg[0]),
	.RN(rst_n),
	.SE(SE),
	.SI(scan_in));
   SDFFRHQX1 \a_reg_reg[1]  (.CK(clk),
	.D(n_81),
	.Q(a_reg[1]),
	.RN(rst_n),
	.SE(SE),
	.SI(a_reg[0]));
   SDFFRHQX1 \a_reg_reg[2]  (.CK(clk),
	.D(n_84),
	.Q(a_reg[2]),
	.RN(rst_n),
	.SE(SE),
	.SI(a_reg[1]));
   SDFFRHQX1 \a_reg_reg[3]  (.CK(clk),
	.D(n_77),
	.Q(a_reg[3]),
	.RN(rst_n),
	.SE(SE),
	.SI(a_reg[2]));
   SDFFRHQX1 \a_reg_reg[4]  (.CK(clk),
	.D(n_75),
	.Q(a_reg[4]),
	.RN(rst_n),
	.SE(SE),
	.SI(a_reg[3]));
   SDFFRHQX1 \a_reg_reg[5]  (.CK(clk),
	.D(n_73),
	.Q(a_reg[5]),
	.RN(rst_n),
	.SE(SE),
	.SI(a_reg[4]));
   SDFFRHQX1 \a_reg_reg[6]  (.CK(clk),
	.D(n_70),
	.Q(a_reg[6]),
	.RN(rst_n),
	.SE(SE),
	.SI(a_reg[5]));
   SDFFRHQX1 \a_reg_reg[7]  (.CK(clk),
	.D(n_99),
	.Q(a_reg[7]),
	.RN(rst_n),
	.SE(SE),
	.SI(a_reg[6]));
   SDFFRHQX1 \b_reg_reg[0]  (.CK(clk),
	.D(n_98),
	.Q(b_reg[0]),
	.RN(rst_n),
	.SE(SE),
	.SI(a_reg[7]));
   SDFFRHQX1 \b_reg_reg[1]  (.CK(clk),
	.D(n_97),
	.Q(b_reg[1]),
	.RN(rst_n),
	.SE(SE),
	.SI(b_reg[0]));
   SDFFRHQX1 \b_reg_reg[2]  (.CK(clk),
	.D(n_96),
	.Q(b_reg[2]),
	.RN(rst_n),
	.SE(SE),
	.SI(b_reg[1]));
   SDFFRHQX1 \b_reg_reg[3]  (.CK(clk),
	.D(n_101),
	.Q(b_reg[3]),
	.RN(rst_n),
	.SE(SE),
	.SI(b_reg[2]));
   SDFFRHQX1 \b_reg_reg[4]  (.CK(clk),
	.D(n_95),
	.Q(b_reg[4]),
	.RN(rst_n),
	.SE(SE),
	.SI(b_reg[3]));
   SDFFRHQX1 \b_reg_reg[5]  (.CK(clk),
	.D(n_94),
	.Q(b_reg[5]),
	.RN(rst_n),
	.SE(SE),
	.SI(b_reg[4]));
   SDFFRHQX1 \b_reg_reg[6]  (.CK(clk),
	.D(n_93),
	.Q(b_reg[6]),
	.RN(rst_n),
	.SE(SE),
	.SI(b_reg[5]));
   SDFFRHQX1 \b_reg_reg[7]  (.CK(clk),
	.D(n_92),
	.Q(b_reg[7]),
	.RN(rst_n),
	.SE(SE),
	.SI(b_reg[6]));
   SDFFRHQX1 \c_reg_reg[0]  (.CK(clk),
	.D(n_91),
	.Q(c_reg[0]),
	.RN(rst_n),
	.SE(SE),
	.SI(b_reg[7]));
   SDFFRHQX1 \c_reg_reg[1]  (.CK(clk),
	.D(n_90),
	.Q(c_reg[1]),
	.RN(rst_n),
	.SE(SE),
	.SI(c_reg[0]));
   SDFFRHQX1 \c_reg_reg[2]  (.CK(clk),
	.D(n_89),
	.Q(c_reg[2]),
	.RN(rst_n),
	.SE(SE),
	.SI(c_reg[1]));
   SDFFRHQX1 \c_reg_reg[3]  (.CK(clk),
	.D(n_88),
	.Q(c_reg[3]),
	.RN(rst_n),
	.SE(SE),
	.SI(c_reg[2]));
   SDFFRHQX1 \c_reg_reg[4]  (.CK(clk),
	.D(n_87),
	.Q(c_reg[4]),
	.RN(rst_n),
	.SE(SE),
	.SI(c_reg[3]));
   SDFFRHQX1 \c_reg_reg[5]  (.CK(clk),
	.D(n_86),
	.Q(c_reg[5]),
	.RN(rst_n),
	.SE(SE),
	.SI(c_reg[4]));
   SDFFRHQX1 \c_reg_reg[6]  (.CK(clk),
	.D(n_85),
	.Q(c_reg[6]),
	.RN(rst_n),
	.SE(SE),
	.SI(c_reg[5]));
   SDFFRHQX1 \c_reg_reg[7]  (.CK(clk),
	.D(n_82),
	.Q(c_reg[7]),
	.RN(rst_n),
	.SE(SE),
	.SI(c_reg[6]));
   SDFFRHQX1 \d_reg_reg[0]  (.CK(clk),
	.D(n_80),
	.Q(d_reg[0]),
	.RN(rst_n),
	.SE(SE),
	.SI(c_reg[7]));
   SDFFRHQX1 \d_reg_reg[1]  (.CK(clk),
	.D(n_79),
	.Q(d_reg[1]),
	.RN(rst_n),
	.SE(SE),
	.SI(d_reg[0]));
   SDFFRHQX1 \d_reg_reg[2]  (.CK(clk),
	.D(n_78),
	.Q(d_reg[2]),
	.RN(rst_n),
	.SE(SE),
	.SI(d_reg[1]));
   SDFFRHQX1 \d_reg_reg[3]  (.CK(clk),
	.D(n_76),
	.Q(d_reg[3]),
	.RN(rst_n),
	.SE(SE),
	.SI(d_reg[2]));
   SDFFRHQX1 \d_reg_reg[4]  (.CK(clk),
	.D(n_74),
	.Q(d_reg[4]),
	.RN(rst_n),
	.SE(SE),
	.SI(d_reg[3]));
   SDFFRHQX1 \d_reg_reg[5]  (.CK(clk),
	.D(n_72),
	.Q(d_reg[5]),
	.RN(rst_n),
	.SE(SE),
	.SI(d_reg[4]));
   SDFFRHQX1 \d_reg_reg[6]  (.CK(clk),
	.D(n_71),
	.Q(d_reg[6]),
	.RN(rst_n),
	.SE(SE),
	.SI(d_reg[5]));
   SDFFRHQX1 \d_reg_reg[7]  (.CK(clk),
	.D(n_69),
	.Q(d_reg[7]),
	.RN(rst_n),
	.SE(SE),
	.SI(d_reg[6]));
   SDFFRHQX1 \state_reg[0]  (.CK(clk),
	.D(n_0),
	.Q(state[0]),
	.RN(rst_n),
	.SE(SE),
	.SI(d_reg[7]));
   SDFFRHQX1 \state_reg[1]  (.CK(clk),
	.D(n_28),
	.Q(state[1]),
	.RN(rst_n),
	.SE(SE),
	.SI(state[0]));
   SDFFRHQX1 \state_reg[2]  (.CK(clk),
	.D(n_22),
	.Q(state[2]),
	.RN(rst_n),
	.SE(SE),
	.SI(state[1]));
   SDFFRHQX1 \temp1_reg_reg[0]  (.CK(clk),
	.D(n_112),
	.Q(temp1_reg[0]),
	.RN(rst_n),
	.SE(SE),
	.SI(state[2]));
   SDFFRHQX1 \temp1_reg_reg[1]  (.CK(clk),
	.D(n_114),
	.Q(temp1_reg[1]),
	.RN(rst_n),
	.SE(SE),
	.SI(temp1_reg[0]));
   SDFFRHQX1 \temp1_reg_reg[2]  (.CK(clk),
	.D(n_119),
	.Q(temp1_reg[2]),
	.RN(rst_n),
	.SE(SE),
	.SI(temp1_reg[1]));
   SDFFRHQX1 \temp1_reg_reg[3]  (.CK(clk),
	.D(n_123),
	.Q(temp1_reg[3]),
	.RN(rst_n),
	.SE(SE),
	.SI(temp1_reg[2]));
   SDFFRHQX1 \temp1_reg_reg[4]  (.CK(clk),
	.D(n_127),
	.Q(temp1_reg[4]),
	.RN(rst_n),
	.SE(SE),
	.SI(temp1_reg[3]));
   SDFFRHQX1 \temp1_reg_reg[5]  (.CK(clk),
	.D(n_131),
	.Q(temp1_reg[5]),
	.RN(rst_n),
	.SE(SE),
	.SI(temp1_reg[4]));
   SDFFRHQX1 \temp1_reg_reg[6]  (.CK(clk),
	.D(n_135),
	.Q(temp1_reg[6]),
	.RN(rst_n),
	.SE(SE),
	.SI(temp1_reg[5]));
   SDFFRHQX1 \temp1_reg_reg[7]  (.CK(clk),
	.D(n_141),
	.Q(temp1_reg[7]),
	.RN(rst_n),
	.SE(SE),
	.SI(temp1_reg[6]));
   SDFFRHQX1 \temp1_reg_reg[8]  (.CK(clk),
	.D(n_138),
	.Q(temp1_reg[8]),
	.RN(rst_n),
	.SE(SE),
	.SI(temp1_reg[7]));
   SDFFRHQX1 \temp2_reg_reg[0]  (.CK(clk),
	.D(n_113),
	.Q(temp2_reg[0]),
	.RN(rst_n),
	.SE(SE),
	.SI(temp1_reg[8]));
   SDFFRHQX1 \temp2_reg_reg[1]  (.CK(clk),
	.D(n_115),
	.Q(temp2_reg[1]),
	.RN(rst_n),
	.SE(SE),
	.SI(temp2_reg[0]));
   SDFFRHQX1 \temp2_reg_reg[2]  (.CK(clk),
	.D(n_118),
	.Q(temp2_reg[2]),
	.RN(rst_n),
	.SE(SE),
	.SI(temp2_reg[1]));
   SDFFRHQX1 \temp2_reg_reg[3]  (.CK(clk),
	.D(n_122),
	.Q(temp2_reg[3]),
	.RN(rst_n),
	.SE(SE),
	.SI(temp2_reg[2]));
   SDFFRHQX1 \temp2_reg_reg[4]  (.CK(clk),
	.D(n_126),
	.Q(temp2_reg[4]),
	.RN(rst_n),
	.SE(SE),
	.SI(temp2_reg[3]));
   SDFFRHQX1 \temp2_reg_reg[5]  (.CK(clk),
	.D(n_130),
	.Q(temp2_reg[5]),
	.RN(rst_n),
	.SE(SE),
	.SI(temp2_reg[4]));
   SDFFRHQX1 \temp2_reg_reg[6]  (.CK(clk),
	.D(n_134),
	.Q(temp2_reg[6]),
	.RN(rst_n),
	.SE(SE),
	.SI(temp2_reg[5]));
   SDFFRHQX1 \temp2_reg_reg[7]  (.CK(clk),
	.D(n_140),
	.Q(temp2_reg[7]),
	.RN(rst_n),
	.SE(SE),
	.SI(temp2_reg[6]));
   SDFFRHQX1 \temp2_reg_reg[8]  (.CK(clk),
	.D(n_139),
	.Q(temp2_reg[8]),
	.RN(rst_n),
	.SE(SE),
	.SI(temp2_reg[7]));
   SDFFRHQX1 \z_reg_reg[0]  (.CK(clk),
	.D(n_51),
	.Q(Z[0]),
	.RN(rst_n),
	.SE(SE),
	.SI(temp2_reg[8]));
   SDFFRHQX1 \z_reg_reg[1]  (.CK(clk),
	.D(n_49),
	.Q(Z[1]),
	.RN(rst_n),
	.SE(SE),
	.SI(Z[0]));
   SDFFRHQX1 \z_reg_reg[2]  (.CK(clk),
	.D(n_63),
	.Q(Z[2]),
	.RN(rst_n),
	.SE(SE),
	.SI(Z[1]));
   SDFFRHQX1 \z_reg_reg[3]  (.CK(clk),
	.D(n_62),
	.Q(Z[3]),
	.RN(rst_n),
	.SE(SE),
	.SI(Z[2]));
   SDFFRHQX1 \z_reg_reg[4]  (.CK(clk),
	.D(n_61),
	.Q(Z[4]),
	.RN(rst_n),
	.SE(SE),
	.SI(Z[3]));
   SDFFRHQX1 \z_reg_reg[5]  (.CK(clk),
	.D(n_50),
	.Q(Z[5]),
	.RN(rst_n),
	.SE(SE),
	.SI(Z[4]));
   SDFFRHQX1 \z_reg_reg[6]  (.CK(clk),
	.D(n_59),
	.Q(Z[6]),
	.RN(rst_n),
	.SE(SE),
	.SI(Z[5]));
   SDFFRHQX1 \z_reg_reg[7]  (.CK(clk),
	.D(n_54),
	.Q(Z[7]),
	.RN(rst_n),
	.SE(SE),
	.SI(Z[6]));
   SDFFRHQX1 \z_reg_reg[8]  (.CK(clk),
	.D(n_60),
	.Q(Z[8]),
	.RN(rst_n),
	.SE(SE),
	.SI(Z[7]));
   SDFFRHQX1 \z_reg_reg[9]  (.CK(clk),
	.D(n_67),
	.Q(Z[9]),
	.RN(rst_n),
	.SE(SE),
	.SI(Z[8]));
   SDFFRHQX1 \z_reg_reg[10]  (.CK(clk),
	.D(n_66),
	.Q(Z[10]),
	.RN(rst_n),
	.SE(SE),
	.SI(Z[9]));
   SDFFRHQX1 \z_reg_reg[11]  (.CK(clk),
	.D(n_65),
	.Q(Z[11]),
	.RN(rst_n),
	.SE(SE),
	.SI(Z[10]));
   SDFFRHQX1 \z_reg_reg[12]  (.CK(clk),
	.D(n_64),
	.Q(Z[12]),
	.RN(rst_n),
	.SE(SE),
	.SI(Z[11]));
   SDFFRHQX1 \z_reg_reg[13]  (.CK(clk),
	.D(n_58),
	.Q(Z[13]),
	.RN(rst_n),
	.SE(SE),
	.SI(Z[12]));
   SDFFRHQX1 \z_reg_reg[14]  (.CK(clk),
	.D(n_57),
	.Q(Z[14]),
	.RN(rst_n),
	.SE(SE),
	.SI(Z[13]));
   SDFFRHQX1 \z_reg_reg[15]  (.CK(clk),
	.D(n_53),
	.Q(Z[15]),
	.RN(rst_n),
	.SE(SE),
	.SI(Z[14]));
   SDFFRHQX1 \z_reg_reg[16]  (.CK(clk),
	.D(n_68),
	.Q(Z[16]),
	.RN(rst_n),
	.SE(SE),
	.SI(Z[15]));
   SDFFRHQX1 \z_reg_reg[17]  (.CK(clk),
	.D(n_52),
	.Q(Z[17]),
	.RN(rst_n),
	.SE(SE),
	.SI(Z[16]));
   OAI21X1 g1928__5107 (.A0(n_24),
	.A1(n_137),
	.B0(n_41),
	.Y(n_141));
   OAI21X1 g1929__6260 (.A0(n_21),
	.A1(n_137),
	.B0(n_34),
	.Y(n_140));
   MX2X1 g1930__4319 (.A(n_136),
	.B(temp2_reg[8]),
	.S0(n_21),
	.Y(n_139));
   MX2X1 g1931__8428 (.A(n_136),
	.B(temp1_reg[8]),
	.S0(n_24),
	.Y(n_138));
   ADDFXL g1932__5526 (.A(n_9),
	.B(n_48),
	.CI(n_132),
	.CO(n_136),
	.S(n_137));
   OAI21X1 g1935__6783 (.A0(n_24),
	.A1(n_133),
	.B0(n_32),
	.Y(n_135));
   OAI21X1 g1936__3680 (.A0(n_21),
	.A1(n_133),
	.B0(n_36),
	.Y(n_134));
   ADDFX1 g1937__1617 (.A(n_43),
	.B(n_10),
	.CI(n_128),
	.CO(n_132),
	.S(n_133));
   OAI21X1 g1940__2802 (.A0(n_24),
	.A1(n_129),
	.B0(n_33),
	.Y(n_131));
   OAI21X1 g1941__1705 (.A0(n_21),
	.A1(n_129),
	.B0(n_40),
	.Y(n_130));
   ADDFX1 g1942__5122 (.A(n_44),
	.B(n_12),
	.CI(n_124),
	.CO(n_128),
	.S(n_129));
   OAI21X1 g1945__8246 (.A0(n_24),
	.A1(n_125),
	.B0(n_30),
	.Y(n_127));
   OAI21X1 g1946__7098 (.A0(n_21),
	.A1(n_125),
	.B0(n_31),
	.Y(n_126));
   ADDFX1 g1947__6131 (.A(n_45),
	.B(n_13),
	.CI(n_120),
	.CO(n_124),
	.S(n_125));
   OAI21X1 g1950__1881 (.A0(n_24),
	.A1(n_121),
	.B0(n_38),
	.Y(n_123));
   OAI21X1 g1951__5115 (.A0(n_21),
	.A1(n_121),
	.B0(n_39),
	.Y(n_122));
   ADDFX1 g1952__7482 (.A(n_46),
	.B(n_15),
	.CI(n_116),
	.CO(n_120),
	.S(n_121));
   OAI21X1 g1955__4733 (.A0(n_24),
	.A1(n_117),
	.B0(n_37),
	.Y(n_119));
   OAI21X1 g1956__6161 (.A0(n_21),
	.A1(n_117),
	.B0(n_42),
	.Y(n_118));
   ADDFX1 g1957__9315 (.A(n_47),
	.B(n_18),
	.CI(n_110),
	.CO(n_116),
	.S(n_117));
   MX2X1 g1960__9945 (.A(n_111),
	.B(temp2_reg[1]),
	.S0(n_21),
	.Y(n_115));
   MX2X1 g1961__2883 (.A(n_111),
	.B(temp1_reg[1]),
	.S0(n_24),
	.Y(n_114));
   MX2X1 g1964__2346 (.A(n_107),
	.B(temp2_reg[0]),
	.S0(n_21),
	.Y(n_113));
   MX2X1 g1965__1666 (.A(n_107),
	.B(temp1_reg[0]),
	.S0(n_24),
	.Y(n_112));
   OAI21X1 g1966__7410 (.A0(n_105),
	.A1(n_106),
	.B0(n_109),
	.Y(n_111));
   AOI21X1 g1967__6417 (.A0(n_102),
	.A1(n_108),
	.B0(n_103),
	.Y(n_110));
   NAND2XL g1968__5477 (.A(n_105),
	.B(n_106),
	.Y(n_109));
   INVX1 g1969 (.A(n_105),
	.Y(n_108));
   MXI2XL g1970__2398 (.A(n_20),
	.B(n_21),
	.S0(n_104),
	.Y(n_107));
   NOR2BX1 g2003__5107 (.AN(n_102),
	.B(n_103),
	.Y(n_106));
   AOI21X1 g2004__6260 (.A0(n_26),
	.A1(n_55),
	.B0(n_100),
	.Y(n_104));
   AOI22X1 g2005__4319 (.A0(n_29),
	.A1(n_55),
	.B0(n_25),
	.B1(n_20),
	.Y(n_105));
   MX2X1 g2006__8428 (.A(b_reg[3]),
	.B(B[3]),
	.S0(n_35),
	.Y(n_101));
   NOR2XL g2007__5526 (.A(n_26),
	.B(n_55),
	.Y(n_100));
   MX2X1 g2008__6783 (.A(a_reg[7]),
	.B(A[7]),
	.S0(n_35),
	.Y(n_99));
   MX2X1 g2009__3680 (.A(b_reg[0]),
	.B(B[0]),
	.S0(n_35),
	.Y(n_98));
   MX2X1 g2010__1617 (.A(b_reg[1]),
	.B(B[1]),
	.S0(n_35),
	.Y(n_97));
   MX2X1 g2011__2802 (.A(b_reg[2]),
	.B(B[2]),
	.S0(n_35),
	.Y(n_96));
   NOR2XL g2026__1705 (.A(n_27),
	.B(n_56),
	.Y(n_103));
   NAND2XL g2027__5122 (.A(n_27),
	.B(n_56),
	.Y(n_102));
   MX2X1 g2033__8246 (.A(b_reg[4]),
	.B(B[4]),
	.S0(n_35),
	.Y(n_95));
   MX2X1 g2034__7098 (.A(b_reg[5]),
	.B(B[5]),
	.S0(n_35),
	.Y(n_94));
   MX2X1 g2035__6131 (.A(b_reg[6]),
	.B(B[6]),
	.S0(n_35),
	.Y(n_93));
   MX2X1 g2036__1881 (.A(b_reg[7]),
	.B(B[7]),
	.S0(n_35),
	.Y(n_92));
   MX2X1 g2037__5115 (.A(c_reg[0]),
	.B(C[0]),
	.S0(n_35),
	.Y(n_91));
   MX2X1 g2038__7482 (.A(c_reg[1]),
	.B(C[1]),
	.S0(n_35),
	.Y(n_90));
   MX2X1 g2039__4733 (.A(c_reg[2]),
	.B(C[2]),
	.S0(n_35),
	.Y(n_89));
   MX2X1 g2040__6161 (.A(c_reg[3]),
	.B(C[3]),
	.S0(n_35),
	.Y(n_88));
   MX2X1 g2041__9315 (.A(c_reg[4]),
	.B(C[4]),
	.S0(n_35),
	.Y(n_87));
   MX2X1 g2042__9945 (.A(c_reg[5]),
	.B(C[5]),
	.S0(n_35),
	.Y(n_86));
   MX2X1 g2043__2883 (.A(c_reg[6]),
	.B(C[6]),
	.S0(n_35),
	.Y(n_85));
   MX2X1 g2044__2346 (.A(a_reg[2]),
	.B(A[2]),
	.S0(n_35),
	.Y(n_84));
   MX2X1 g2045__1666 (.A(a_reg[0]),
	.B(A[0]),
	.S0(n_35),
	.Y(n_83));
   MX2X1 g2046__7410 (.A(c_reg[7]),
	.B(C[7]),
	.S0(n_35),
	.Y(n_82));
   MX2X1 g2047__6417 (.A(a_reg[1]),
	.B(A[1]),
	.S0(n_35),
	.Y(n_81));
   MX2X1 g2048__5477 (.A(d_reg[0]),
	.B(D[0]),
	.S0(n_35),
	.Y(n_80));
   MX2X1 g2049__2398 (.A(d_reg[1]),
	.B(D[1]),
	.S0(n_35),
	.Y(n_79));
   MX2X1 g2050__5107 (.A(d_reg[2]),
	.B(D[2]),
	.S0(n_35),
	.Y(n_78));
   MX2X1 g2051__6260 (.A(a_reg[3]),
	.B(A[3]),
	.S0(n_35),
	.Y(n_77));
   MX2X1 g2052__4319 (.A(d_reg[3]),
	.B(D[3]),
	.S0(n_35),
	.Y(n_76));
   MX2X1 g2053__8428 (.A(a_reg[4]),
	.B(A[4]),
	.S0(n_35),
	.Y(n_75));
   MX2X1 g2054__5526 (.A(d_reg[4]),
	.B(D[4]),
	.S0(n_35),
	.Y(n_74));
   MX2X1 g2055__6783 (.A(a_reg[5]),
	.B(A[5]),
	.S0(n_35),
	.Y(n_73));
   MX2X1 g2056__3680 (.A(d_reg[5]),
	.B(D[5]),
	.S0(n_35),
	.Y(n_72));
   MX2X1 g2057__1617 (.A(d_reg[6]),
	.B(D[6]),
	.S0(n_35),
	.Y(n_71));
   MX2X1 g2058__2802 (.A(a_reg[6]),
	.B(A[6]),
	.S0(n_35),
	.Y(n_70));
   MX2X1 g2059__1705 (.A(d_reg[7]),
	.B(D[7]),
	.S0(n_35),
	.Y(n_69));
   MX2X1 g2060__5122 (.A(mul_out[16]),
	.B(Z[16]),
	.S0(n_23),
	.Y(n_68));
   MX2X1 g2062__8246 (.A(mul_out[9]),
	.B(Z[9]),
	.S0(n_23),
	.Y(n_67));
   MX2X1 g2063__7098 (.A(mul_out[10]),
	.B(Z[10]),
	.S0(n_23),
	.Y(n_66));
   MX2X1 g2064__6131 (.A(mul_out[11]),
	.B(Z[11]),
	.S0(n_23),
	.Y(n_65));
   MX2X1 g2065__1881 (.A(mul_out[12]),
	.B(Z[12]),
	.S0(n_23),
	.Y(n_64));
   MX2X1 g2066__5115 (.A(mul_out[2]),
	.B(Z[2]),
	.S0(n_23),
	.Y(n_63));
   MX2X1 g2067__7482 (.A(mul_out[3]),
	.B(Z[3]),
	.S0(n_23),
	.Y(n_62));
   MX2X1 g2068__4733 (.A(mul_out[4]),
	.B(Z[4]),
	.S0(n_23),
	.Y(n_61));
   MX2X1 g2069__6161 (.A(mul_out[8]),
	.B(Z[8]),
	.S0(n_23),
	.Y(n_60));
   MX2X1 g2070__9315 (.A(mul_out[6]),
	.B(Z[6]),
	.S0(n_23),
	.Y(n_59));
   MX2X1 g2071__9945 (.A(mul_out[13]),
	.B(Z[13]),
	.S0(n_23),
	.Y(n_58));
   MX2X1 g2072__2883 (.A(mul_out[14]),
	.B(Z[14]),
	.S0(n_23),
	.Y(n_57));
   MX2X1 g2074__2346 (.A(mul_out[7]),
	.B(Z[7]),
	.S0(n_23),
	.Y(n_54));
   MX2X1 g2075__1666 (.A(mul_out[15]),
	.B(Z[15]),
	.S0(n_23),
	.Y(n_53));
   MX2X1 g2076__7410 (.A(mul_out[17]),
	.B(Z[17]),
	.S0(n_23),
	.Y(n_52));
   MX2X1 g2077__6417 (.A(mul_out[0]),
	.B(Z[0]),
	.S0(n_23),
	.Y(n_51));
   MX2X1 g2078__5477 (.A(mul_out[5]),
	.B(Z[5]),
	.S0(n_23),
	.Y(n_50));
   MX2X1 g2079__2398 (.A(mul_out[1]),
	.B(Z[1]),
	.S0(n_23),
	.Y(n_49));
   MXI2XL g2080__5107 (.A(n_20),
	.B(n_21),
	.S0(n_8),
	.Y(n_48));
   MXI2XL g2081__6260 (.A(n_21),
	.B(n_20),
	.S0(n_17),
	.Y(n_56));
   MXI2XL g2082__4319 (.A(n_21),
	.B(n_20),
	.S0(n_19),
	.Y(n_47));
   MXI2XL g2083__8428 (.A(n_21),
	.B(n_20),
	.S0(n_14),
	.Y(n_46));
   MXI2XL g2084__5526 (.A(n_21),
	.B(n_20),
	.S0(n_7),
	.Y(n_45));
   MXI2XL g2085__6783 (.A(n_21),
	.B(n_20),
	.S0(n_11),
	.Y(n_44));
   MXI2XL g2086__3680 (.A(n_21),
	.B(n_20),
	.S0(n_6),
	.Y(n_43));
   MXI2XL g2087__1617 (.A(n_20),
	.B(n_21),
	.S0(n_16),
	.Y(n_55));
   NAND2XL g2088__2802 (.A(temp2_reg[2]),
	.B(n_21),
	.Y(n_42));
   NAND2XL g2089__1705 (.A(temp1_reg[7]),
	.B(n_24),
	.Y(n_41));
   NAND2XL g2090__5122 (.A(temp2_reg[5]),
	.B(n_21),
	.Y(n_40));
   NAND2XL g2091__8246 (.A(temp2_reg[3]),
	.B(n_21),
	.Y(n_39));
   NAND2XL g2092__7098 (.A(temp1_reg[3]),
	.B(n_24),
	.Y(n_38));
   NAND2XL g2093__6131 (.A(temp1_reg[2]),
	.B(n_24),
	.Y(n_37));
   NAND2XL g2094__1881 (.A(temp2_reg[6]),
	.B(n_21),
	.Y(n_36));
   NAND2XL g2097__5115 (.A(temp2_reg[7]),
	.B(n_21),
	.Y(n_34));
   NAND2XL g2098__7482 (.A(temp1_reg[5]),
	.B(n_24),
	.Y(n_33));
   NAND2XL g2099__4733 (.A(temp1_reg[6]),
	.B(n_24),
	.Y(n_32));
   NAND2XL g2100__6161 (.A(temp2_reg[4]),
	.B(n_21),
	.Y(n_31));
   NAND2XL g2101__9315 (.A(temp1_reg[4]),
	.B(n_24),
	.Y(n_30));
   NAND2XL g2102__9945 (.A(n_26),
	.B(n_21),
	.Y(n_29));
   NAND2XL g2103__2883 (.A(n_24),
	.B(n_21),
	.Y(n_28));
   AND4X1 g2104__2346 (.A(start),
	.B(n_4),
	.C(n_3),
	.D(n_1),
	.Y(n_35));
   INVXL g2105 (.A(n_26),
	.Y(n_25));
   INVXL g2106 (.A(n_23),
	.Y(n_22));
   CLKINVX1 g2107 (.A(n_21),
	.Y(n_20));
   AOI22X1 g2108__1666 (.A0(d_reg[2]),
	.A1(n_1),
	.B0(a_reg[2]),
	.B1(state[0]),
	.Y(n_19));
   AOI22X1 g2109__7410 (.A0(c_reg[2]),
	.A1(n_1),
	.B0(b_reg[2]),
	.B1(state[0]),
	.Y(n_18));
   AOI22X1 g2110__6417 (.A0(d_reg[1]),
	.A1(n_1),
	.B0(a_reg[1]),
	.B1(state[0]),
	.Y(n_17));
   AOI22X1 g2111__5477 (.A0(c_reg[1]),
	.A1(n_1),
	.B0(b_reg[1]),
	.B1(state[0]),
	.Y(n_27));
   AOI22X1 g2112__2398 (.A0(d_reg[0]),
	.A1(n_1),
	.B0(a_reg[0]),
	.B1(state[0]),
	.Y(n_16));
   AOI22X1 g2113__5107 (.A0(c_reg[0]),
	.A1(n_1),
	.B0(b_reg[0]),
	.B1(state[0]),
	.Y(n_26));
   OR3X1 g2114__6260 (.A(state[1]),
	.B(state[2]),
	.C(n_1),
	.Y(n_24));
   OR2X1 g2115__4319 (.A(n_1),
	.B(n_5),
	.Y(n_23));
   OR2X1 g2116__8428 (.A(state[0]),
	.B(n_5),
	.Y(n_21));
   AOI22X1 g2117__5526 (.A0(c_reg[3]),
	.A1(n_1),
	.B0(b_reg[3]),
	.B1(state[0]),
	.Y(n_15));
   AOI22X1 g2118__6783 (.A0(d_reg[3]),
	.A1(n_1),
	.B0(a_reg[3]),
	.B1(state[0]),
	.Y(n_14));
   AOI22X1 g2119__3680 (.A0(c_reg[4]),
	.A1(n_1),
	.B0(b_reg[4]),
	.B1(state[0]),
	.Y(n_13));
   AOI22X1 g2120__1617 (.A0(c_reg[5]),
	.A1(n_1),
	.B0(b_reg[5]),
	.B1(state[0]),
	.Y(n_12));
   AOI22X1 g2121__2802 (.A0(d_reg[5]),
	.A1(n_1),
	.B0(a_reg[5]),
	.B1(state[0]),
	.Y(n_11));
   AOI22X1 g2122__1705 (.A0(c_reg[6]),
	.A1(n_1),
	.B0(b_reg[6]),
	.B1(state[0]),
	.Y(n_10));
   MX2X1 g2123__5122 (.A(c_reg[7]),
	.B(b_reg[7]),
	.S0(state[0]),
	.Y(n_9));
   AOI22X1 g2124__8246 (.A0(d_reg[7]),
	.A1(n_1),
	.B0(a_reg[7]),
	.B1(state[0]),
	.Y(n_8));
   AOI22X1 g2125__7098 (.A0(d_reg[4]),
	.A1(n_1),
	.B0(a_reg[4]),
	.B1(state[0]),
	.Y(n_7));
   AOI22X1 g2126__6131 (.A0(d_reg[6]),
	.A1(n_1),
	.B0(a_reg[6]),
	.B1(state[0]),
	.Y(n_6));
   NAND2XL g2127__1881 (.A(state[1]),
	.B(n_4),
	.Y(n_5));
   CLKINVX1 g2128 (.A(state[2]),
	.Y(n_4));
   INVXL g2129 (.A(state[1]),
	.Y(n_3));
   CLKINVX1 g2171 (.A(state[0]),
	.Y(n_1));
   NAND2BX1 g2__5115 (.AN(n_35),
	.B(n_21),
	.Y(n_0));
   INVX1 mul_121_41_g1927 (.A(mul_121_41_n_233),
	.Y(mul_out[17]));
   ADDFXL mul_121_41_g1928__7482 (.A(mul_121_41_n_104),
	.B(mul_121_41_n_165),
	.CI(mul_121_41_n_231),
	.CO(mul_121_41_n_233),
	.S(mul_out[16]));
   ADDFX1 mul_121_41_g1929__4733 (.A(mul_121_41_n_185),
	.B(mul_121_41_n_166),
	.CI(mul_121_41_n_229),
	.CO(mul_121_41_n_231),
	.S(mul_out[15]));
   ADDFX1 mul_121_41_g1930__6161 (.A(mul_121_41_n_199),
	.B(mul_121_41_n_186),
	.CI(mul_121_41_n_227),
	.CO(mul_121_41_n_229),
	.S(mul_out[14]));
   ADDFX1 mul_121_41_g1931__9315 (.A(mul_121_41_n_200),
	.B(mul_121_41_n_201),
	.CI(mul_121_41_n_225),
	.CO(mul_121_41_n_227),
	.S(mul_out[13]));
   ADDFX1 mul_121_41_g1932__9945 (.A(mul_121_41_n_202),
	.B(mul_121_41_n_207),
	.CI(mul_121_41_n_223),
	.CO(mul_121_41_n_225),
	.S(mul_out[12]));
   ADDFX1 mul_121_41_g1933__2883 (.A(mul_121_41_n_208),
	.B(mul_121_41_n_209),
	.CI(mul_121_41_n_221),
	.CO(mul_121_41_n_223),
	.S(mul_out[11]));
   ADDFX1 mul_121_41_g1934__2346 (.A(mul_121_41_n_210),
	.B(mul_121_41_n_205),
	.CI(mul_121_41_n_219),
	.CO(mul_121_41_n_221),
	.S(mul_out[10]));
   ADDFX1 mul_121_41_g1935__1666 (.A(mul_121_41_n_206),
	.B(mul_121_41_n_197),
	.CI(mul_121_41_n_217),
	.CO(mul_121_41_n_219),
	.S(mul_out[9]));
   ADDFX1 mul_121_41_g1936__7410 (.A(mul_121_41_n_198),
	.B(mul_121_41_n_195),
	.CI(mul_121_41_n_215),
	.CO(mul_121_41_n_217),
	.S(mul_out[8]));
   ADDFX1 mul_121_41_g1937__6417 (.A(mul_121_41_n_196),
	.B(mul_121_41_n_191),
	.CI(mul_121_41_n_213),
	.CO(mul_121_41_n_215),
	.S(mul_out[7]));
   ADDFX1 mul_121_41_g1938__5477 (.A(mul_121_41_n_192),
	.B(mul_121_41_n_169),
	.CI(mul_121_41_n_211),
	.CO(mul_121_41_n_213),
	.S(mul_out[6]));
   ADDFX1 mul_121_41_g1939__2398 (.A(mul_121_41_n_170),
	.B(mul_121_41_n_163),
	.CI(mul_121_41_n_203),
	.CO(mul_121_41_n_211),
	.S(mul_out[5]));
   ADDFXL mul_121_41_g1940__5107 (.A(mul_121_41_n_160),
	.B(mul_121_41_n_194),
	.CI(mul_121_41_n_187),
	.CO(mul_121_41_n_209),
	.S(mul_121_41_n_210));
   ADDFXL mul_121_41_g1941__6260 (.A(mul_121_41_n_162),
	.B(mul_121_41_n_184),
	.CI(mul_121_41_n_193),
	.CO(mul_121_41_n_207),
	.S(mul_121_41_n_208));
   ADDFXL mul_121_41_g1942__4319 (.A(mul_121_41_n_181),
	.B(mul_121_41_n_174),
	.CI(mul_121_41_n_188),
	.CO(mul_121_41_n_205),
	.S(mul_121_41_n_206));
   ADDFX1 mul_121_41_g1943__8428 (.A(mul_121_41_n_164),
	.B(mul_121_41_n_151),
	.CI(mul_121_41_n_189),
	.CO(mul_121_41_n_203),
	.S(mul_out[4]));
   ADDFXL mul_121_41_g1944__5526 (.A(mul_121_41_n_161),
	.B(mul_121_41_n_172),
	.CI(mul_121_41_n_183),
	.CO(mul_121_41_n_201),
	.S(mul_121_41_n_202));
   ADDFXL mul_121_41_g1945__6783 (.A(mul_121_41_n_126),
	.B(mul_121_41_n_171),
	.CI(mul_121_41_n_158),
	.CO(mul_121_41_n_199),
	.S(mul_121_41_n_200));
   ADDFXL mul_121_41_g1946__3680 (.A(mul_121_41_n_177),
	.B(mul_121_41_n_180),
	.CI(mul_121_41_n_182),
	.CO(mul_121_41_n_197),
	.S(mul_121_41_n_198));
   ADDFXL mul_121_41_g1947__1617 (.A(mul_121_41_n_152),
	.B(mul_121_41_n_175),
	.CI(mul_121_41_n_178),
	.CO(mul_121_41_n_195),
	.S(mul_121_41_n_196));
   ADDFXL mul_121_41_g1948__2802 (.A(mul_121_41_n_125),
	.B(mul_121_41_n_147),
	.CI(mul_121_41_n_173),
	.CO(mul_121_41_n_193),
	.S(mul_121_41_n_194));
   ADDFXL mul_121_41_g1949__1705 (.A(mul_121_41_n_110),
	.B(mul_121_41_n_148),
	.CI(mul_121_41_n_176),
	.CO(mul_121_41_n_191),
	.S(mul_121_41_n_192));
   ADDFX1 mul_121_41_g1950__5122 (.A(mul_121_41_n_153),
	.B(mul_121_41_n_119),
	.CI(mul_121_41_n_167),
	.CO(mul_121_41_n_189),
	.S(mul_out[3]));
   ADDFXL mul_121_41_g1951__8246 (.A(mul_121_41_n_118),
	.B(mul_121_41_n_155),
	.CI(mul_121_41_n_179),
	.CO(mul_121_41_n_187),
	.S(mul_121_41_n_188));
   ADDFXL mul_121_41_g1952__7098 (.A(mul_121_41_n_101),
	.B(mul_121_41_n_112),
	.CI(mul_121_41_n_157),
	.CO(mul_121_41_n_185),
	.S(mul_121_41_n_186));
   ADDFXL mul_121_41_g1953__6131 (.A(mul_121_41_n_116),
	.B(mul_121_41_n_124),
	.CI(mul_121_41_n_159),
	.CO(mul_121_41_n_183),
	.S(mul_121_41_n_184));
   ADDFXL mul_121_41_g1954__1881 (.A(mul_121_41_n_109),
	.B(mul_121_41_n_113),
	.CI(mul_121_41_n_149),
	.CO(mul_121_41_n_181),
	.S(mul_121_41_n_182));
   ADDFXL mul_121_41_g1955__5115 (.A(mul_121_41_n_103),
	.B(mul_121_41_n_136),
	.CI(mul_121_41_n_123),
	.CO(mul_121_41_n_179),
	.S(mul_121_41_n_180));
   ADDFXL mul_121_41_g1956__7482 (.A(mul_121_41_n_114),
	.B(mul_121_41_n_115),
	.CI(mul_121_41_n_120),
	.CO(mul_121_41_n_177),
	.S(mul_121_41_n_178));
   ADDFXL mul_121_41_g1957__4733 (.A(mul_121_41_n_89),
	.B(mul_121_41_n_129),
	.CI(mul_121_41_n_121),
	.CO(mul_121_41_n_175),
	.S(mul_121_41_n_176));
   ADDFXL mul_121_41_g1958__6161 (.A(mul_121_41_n_97),
	.B(mul_121_41_n_135),
	.CI(mul_121_41_n_138),
	.CO(mul_121_41_n_173),
	.S(mul_121_41_n_174));
   ADDFXL mul_121_41_g1959__9315 (.A(mul_121_41_n_95),
	.B(mul_121_41_n_111),
	.CI(mul_121_41_n_127),
	.CO(mul_121_41_n_171),
	.S(mul_121_41_n_172));
   ADDFXL mul_121_41_g1960__9945 (.A(mul_121_41_n_133),
	.B(mul_121_41_n_134),
	.CI(mul_121_41_n_154),
	.CO(mul_121_41_n_169),
	.S(mul_121_41_n_170));
   ADDFX1 mul_121_41_g1961__2883 (.A(mul_121_41_n_132),
	.B(mul_121_41_n_90),
	.CI(mul_121_41_n_150),
	.CO(mul_121_41_n_167),
	.S(mul_out[2]));
   ADDFXL mul_121_41_g1962__2346 (.A(mul_121_41_n_98),
	.B(mul_121_41_n_102),
	.CI(mul_121_41_n_140),
	.CO(mul_121_41_n_165),
	.S(mul_121_41_n_166));
   ADDFXL mul_121_41_g1963__1666 (.A(mul_121_41_n_91),
	.B(mul_121_41_n_137),
	.CI(mul_121_41_n_139),
	.CO(mul_121_41_n_163),
	.S(mul_121_41_n_164));
   ADDFXL mul_121_41_g1964__7410 (.A(mul_121_41_n_99),
	.B(mul_121_41_n_131),
	.CI(mul_121_41_n_141),
	.CO(mul_121_41_n_161),
	.S(mul_121_41_n_162));
   ADDFXL mul_121_41_g1965__6417 (.A(mul_121_41_n_96),
	.B(mul_121_41_n_117),
	.CI(mul_121_41_n_122),
	.CO(mul_121_41_n_159),
	.S(mul_121_41_n_160));
   ADDFXL mul_121_41_g1966__5477 (.A(mul_121_41_n_100),
	.B(mul_121_41_n_130),
	.CI(mul_121_41_n_142),
	.CO(mul_121_41_n_157),
	.S(mul_121_41_n_158));
   AOI21XL mul_121_41_g1967__2398 (.A0(mul_121_41_n_74),
	.A1(mul_121_41_n_146),
	.B0(mul_121_41_n_150),
	.Y(mul_out[1]));
   OAI21X1 mul_121_41_g1968__5107 (.A0(mul_121_41_n_108),
	.A1(mul_121_41_n_128),
	.B0(mul_121_41_n_147),
	.Y(mul_121_41_n_155));
   CLKXOR2X1 mul_121_41_g1969__6260 (.A(mul_121_41_n_106),
	.B(mul_121_41_n_145),
	.Y(mul_121_41_n_154));
   CLKXOR2X1 mul_121_41_g1970__4319 (.A(mul_121_41_n_107),
	.B(mul_121_41_n_144),
	.Y(mul_121_41_n_153));
   CLKXOR2X1 mul_121_41_g1971__8428 (.A(mul_121_41_n_105),
	.B(mul_121_41_n_143),
	.Y(mul_121_41_n_152));
   NOR2XL mul_121_41_g1972__5526 (.A(mul_121_41_n_107),
	.B(mul_121_41_n_144),
	.Y(mul_121_41_n_151));
   NOR2XL mul_121_41_g1973__6783 (.A(mul_121_41_n_74),
	.B(mul_121_41_n_146),
	.Y(mul_121_41_n_150));
   NOR2XL mul_121_41_g1974__3680 (.A(mul_121_41_n_105),
	.B(mul_121_41_n_143),
	.Y(mul_121_41_n_149));
   NOR2XL mul_121_41_g1975__1617 (.A(mul_121_41_n_106),
	.B(mul_121_41_n_145),
	.Y(mul_121_41_n_148));
   NAND2XL mul_121_41_g1976__2802 (.A(mul_121_41_n_108),
	.B(mul_121_41_n_128),
	.Y(mul_121_41_n_147));
   AOI22X1 mul_121_41_g1977__1705 (.A0(mul_121_41_n_5),
	.A1(mul_121_41_n_93),
	.B0(temp2_reg[0]),
	.B1(mul_121_41_n_63),
	.Y(mul_121_41_n_146));
   OAI21X1 mul_121_41_g1978__5122 (.A0(mul_121_41_n_83),
	.A1(mul_121_41_n_53),
	.B0(mul_121_41_n_71),
	.Y(mul_121_41_n_142));
   OAI21X1 mul_121_41_g1979__8246 (.A0(mul_121_41_n_24),
	.A1(mul_121_41_n_85),
	.B0(mul_121_41_n_62),
	.Y(mul_121_41_n_141));
   OAI21X1 mul_121_41_g1980__7098 (.A0(mul_121_41_n_87),
	.A1(mul_121_41_n_55),
	.B0(mul_121_41_n_41),
	.Y(mul_121_41_n_140));
   OAI22X1 mul_121_41_g1981__6131 (.A0(mul_121_41_n_33),
	.A1(mul_121_41_n_86),
	.B0(mul_121_41_n_25),
	.B1(mul_121_41_n_70),
	.Y(mul_121_41_n_139));
   AOI22X1 mul_121_41_g1982__1881 (.A0(mul_121_41_n_67),
	.A1(mul_121_41_n_93),
	.B0(temp2_reg[0]),
	.B1(mul_121_41_n_27),
	.Y(mul_121_41_n_145));
   AOI22X1 mul_121_41_g1983__5115 (.A0(mul_121_41_n_32),
	.A1(mul_121_41_n_93),
	.B0(temp2_reg[0]),
	.B1(mul_121_41_n_58),
	.Y(mul_121_41_n_144));
   OAI21X1 mul_121_41_g1984__7482 (.A0(temp2_reg[0]),
	.A1(mul_121_41_n_93),
	.B0(mul_121_41_n_73),
	.Y(mul_121_41_n_138));
   AOI22X1 mul_121_41_g1985__4733 (.A0(mul_121_41_n_69),
	.A1(mul_121_41_n_93),
	.B0(temp2_reg[0]),
	.B1(mul_121_41_n_76),
	.Y(mul_121_41_n_143));
   OAI22X1 mul_121_41_g1986__6161 (.A0(mul_121_41_n_59),
	.A1(mul_121_41_n_92),
	.B0(mul_121_41_n_6),
	.B1(mul_121_41_n_66),
	.Y(mul_121_41_n_137));
   OAI22X1 mul_121_41_g1987__9315 (.A0(mul_121_41_n_77),
	.A1(mul_121_41_n_92),
	.B0(mul_121_41_n_6),
	.B1(mul_121_41_n_72),
	.Y(mul_121_41_n_136));
   OAI22X1 mul_121_41_g1988__9945 (.A0(mul_121_41_n_40),
	.A1(mul_121_41_n_88),
	.B0(mul_121_41_n_42),
	.B1(mul_121_41_n_56),
	.Y(mul_121_41_n_135));
   OAI22X1 mul_121_41_g1989__2883 (.A0(mul_121_41_n_22),
	.A1(mul_121_41_n_84),
	.B0(mul_121_41_n_30),
	.B1(mul_121_41_n_54),
	.Y(mul_121_41_n_134));
   OAI22X1 mul_121_41_g1990__2346 (.A0(mul_121_41_n_70),
	.A1(mul_121_41_n_86),
	.B0(mul_121_41_n_29),
	.B1(mul_121_41_n_25),
	.Y(mul_121_41_n_133));
   OAI22X1 mul_121_41_g1991__1666 (.A0(mul_121_41_n_64),
	.A1(mul_121_41_n_92),
	.B0(mul_121_41_n_6),
	.B1(mul_121_41_n_31),
	.Y(mul_121_41_n_132));
   OAI22X1 mul_121_41_g1992__7410 (.A0(mul_121_41_n_65),
	.A1(mul_121_41_n_84),
	.B0(mul_121_41_n_75),
	.B1(mul_121_41_n_54),
	.Y(mul_121_41_n_131));
   OAI22X1 mul_121_41_g1993__6417 (.A0(mul_121_41_n_39),
	.A1(mul_121_41_n_88),
	.B0(mul_121_41_n_38),
	.B1(mul_121_41_n_56),
	.Y(mul_121_41_n_130));
   OAI22X1 mul_121_41_g1994__5477 (.A0(mul_121_41_n_26),
	.A1(mul_121_41_n_92),
	.B0(mul_121_41_n_6),
	.B1(mul_121_41_n_68),
	.Y(mul_121_41_n_129));
   INVX1 mul_121_41_g1995 (.A(mul_121_41_n_126),
	.Y(mul_121_41_n_127));
   INVX1 mul_121_41_g1996 (.A(mul_121_41_n_124),
	.Y(mul_121_41_n_125));
   AOI22X1 mul_121_41_g1997__2398 (.A0(mul_121_41_n_34),
	.A1(mul_121_41_n_85),
	.B0(mul_121_41_n_79),
	.B1(mul_121_41_n_24),
	.Y(mul_121_41_n_128));
   OAI22X1 mul_121_41_g1998__5107 (.A0(mul_121_41_n_44),
	.A1(mul_121_41_n_88),
	.B0(mul_121_41_n_40),
	.B1(mul_121_41_n_56),
	.Y(mul_121_41_n_123));
   AO22X1 mul_121_41_g1999__6260 (.A0(mul_121_41_n_79),
	.A1(mul_121_41_n_85),
	.B0(mul_121_41_n_24),
	.B1(mul_121_41_n_62),
	.Y(mul_121_41_n_122));
   OAI22X1 mul_121_41_g2000__4319 (.A0(mul_121_41_n_29),
	.A1(mul_121_41_n_86),
	.B0(mul_121_41_n_36),
	.B1(mul_121_41_n_25),
	.Y(mul_121_41_n_121));
   OAI22X1 mul_121_41_g2001__8428 (.A0(mul_121_41_n_61),
	.A1(mul_121_41_n_84),
	.B0(mul_121_41_n_60),
	.B1(mul_121_41_n_54),
	.Y(mul_121_41_n_120));
   OAI22X1 mul_121_41_g2002__5526 (.A0(mul_121_41_n_45),
	.A1(mul_121_41_n_86),
	.B0(mul_121_41_n_33),
	.B1(mul_121_41_n_25),
	.Y(mul_121_41_n_119));
   OAI22X1 mul_121_41_g2003__6783 (.A0(mul_121_41_n_78),
	.A1(mul_121_41_n_84),
	.B0(mul_121_41_n_80),
	.B1(mul_121_41_n_54),
	.Y(mul_121_41_n_118));
   OAI22X1 mul_121_41_g2004__3680 (.A0(mul_121_41_n_42),
	.A1(mul_121_41_n_88),
	.B0(mul_121_41_n_43),
	.B1(mul_121_41_n_56),
	.Y(mul_121_41_n_117));
   OAI22X1 mul_121_41_g2005__1617 (.A0(mul_121_41_n_43),
	.A1(mul_121_41_n_88),
	.B0(mul_121_41_n_37),
	.B1(mul_121_41_n_56),
	.Y(mul_121_41_n_116));
   OAI22X1 mul_121_41_g2006__2802 (.A0(mul_121_41_n_14),
	.A1(mul_121_41_n_88),
	.B0(mul_121_41_n_44),
	.B1(mul_121_41_n_56),
	.Y(mul_121_41_n_115));
   OAI22X1 mul_121_41_g2007__1705 (.A0(mul_121_41_n_36),
	.A1(mul_121_41_n_86),
	.B0(mul_121_41_n_28),
	.B1(mul_121_41_n_25),
	.Y(mul_121_41_n_114));
   OAI22X1 mul_121_41_g2008__5122 (.A0(mul_121_41_n_60),
	.A1(mul_121_41_n_84),
	.B0(mul_121_41_n_78),
	.B1(mul_121_41_n_54),
	.Y(mul_121_41_n_113));
   OAI21X1 mul_121_41_g2009__8246 (.A0(mul_121_41_n_38),
	.A1(mul_121_41_n_88),
	.B0(mul_121_41_n_82),
	.Y(mul_121_41_n_112));
   OAI21X1 mul_121_41_g2010__7098 (.A0(mul_121_41_n_75),
	.A1(mul_121_41_n_84),
	.B0(mul_121_41_n_81),
	.Y(mul_121_41_n_111));
   OAI22X1 mul_121_41_g2011__6131 (.A0(mul_121_41_n_30),
	.A1(mul_121_41_n_84),
	.B0(mul_121_41_n_61),
	.B1(mul_121_41_n_54),
	.Y(mul_121_41_n_110));
   OAI22X1 mul_121_41_g2012__1881 (.A0(mul_121_41_n_28),
	.A1(mul_121_41_n_86),
	.B0(mul_121_41_n_35),
	.B1(mul_121_41_n_25),
	.Y(mul_121_41_n_109));
   OAI22X1 mul_121_41_g2013__5115 (.A0(mul_121_41_n_37),
	.A1(mul_121_41_n_88),
	.B0(mul_121_41_n_39),
	.B1(mul_121_41_n_56),
	.Y(mul_121_41_n_126));
   OAI22X1 mul_121_41_g2014__7482 (.A0(mul_121_41_n_80),
	.A1(mul_121_41_n_84),
	.B0(mul_121_41_n_65),
	.B1(mul_121_41_n_54),
	.Y(mul_121_41_n_124));
   NAND2XL mul_121_41_g2015__4733 (.A(mul_121_41_n_5),
	.B(mul_121_41_n_7),
	.Y(mul_121_41_n_108));
   OAI21X1 mul_121_41_g2016__6161 (.A0(mul_121_41_n_11),
	.A1(mul_121_41_n_48),
	.B0(temp2_reg[3]),
	.Y(mul_121_41_n_107));
   OAI21X1 mul_121_41_g2017__9315 (.A0(mul_121_41_n_10),
	.A1(mul_121_41_n_50),
	.B0(temp2_reg[5]),
	.Y(mul_121_41_n_106));
   OAI21X1 mul_121_41_g2018__9945 (.A0(mul_121_41_n_12),
	.A1(mul_121_41_n_51),
	.B0(temp2_reg[7]),
	.Y(mul_121_41_n_105));
   NAND2XL mul_121_41_g2019__2883 (.A(mul_121_41_n_17),
	.B(mul_121_41_n_94),
	.Y(mul_121_41_n_104));
   NOR2XL mul_121_41_g2020__2346 (.A(mul_121_41_n_5),
	.B(mul_121_41_n_57),
	.Y(mul_121_41_n_103));
   INVX1 mul_121_41_g2021 (.A(mul_121_41_n_101),
	.Y(mul_121_41_n_102));
   NOR2XL mul_121_41_g2022__1666 (.A(mul_121_41_n_21),
	.B(mul_121_41_n_57),
	.Y(mul_121_41_n_100));
   NOR2XL mul_121_41_g2023__7410 (.A(mul_121_41_n_20),
	.B(mul_121_41_n_57),
	.Y(mul_121_41_n_99));
   NOR2XL mul_121_41_g2024__6417 (.A(mul_121_41_n_15),
	.B(mul_121_41_n_57),
	.Y(mul_121_41_n_98));
   NOR2XL mul_121_41_g2025__5477 (.A(mul_121_41_n_19),
	.B(mul_121_41_n_57),
	.Y(mul_121_41_n_97));
   NOR2XL mul_121_41_g2026__2398 (.A(mul_121_41_n_18),
	.B(mul_121_41_n_57),
	.Y(mul_121_41_n_96));
   NOR2XL mul_121_41_g2027__5107 (.A(mul_121_41_n_23),
	.B(mul_121_41_n_57),
	.Y(mul_121_41_n_95));
   NAND2XL mul_121_41_g2028__6260 (.A(mul_121_41_n_16),
	.B(mul_121_41_n_94),
	.Y(mul_121_41_n_101));
   CLKINVX1 mul_121_41_g2029 (.A(mul_121_41_n_57),
	.Y(mul_121_41_n_94));
   CLKINVX1 mul_121_41_g2030 (.A(mul_121_41_n_93),
	.Y(mul_121_41_n_92));
   NOR2XL mul_121_41_g2031__4319 (.A(temp2_reg[0]),
	.B(mul_121_41_n_0),
	.Y(mul_121_41_n_93));
   NOR2XL mul_121_41_g2032__8428 (.A(mul_121_41_n_5),
	.B(mul_121_41_n_54),
	.Y(mul_121_41_n_91));
   NOR2XL mul_121_41_g2033__5526 (.A(mul_121_41_n_5),
	.B(mul_121_41_n_25),
	.Y(mul_121_41_n_90));
   NOR2XL mul_121_41_g2034__6783 (.A(mul_121_41_n_5),
	.B(mul_121_41_n_56),
	.Y(mul_121_41_n_89));
   INVXL mul_121_41_g2035 (.A(mul_121_41_n_88),
	.Y(mul_121_41_n_87));
   NAND2XL mul_121_41_g2036__3680 (.A(mul_121_41_n_13),
	.B(mul_121_41_n_56),
	.Y(mul_121_41_n_88));
   CLKINVX1 mul_121_41_g2037 (.A(mul_121_41_n_86),
	.Y(mul_121_41_n_85));
   NAND2XL mul_121_41_g2038__1617 (.A(mul_121_41_n_46),
	.B(mul_121_41_n_25),
	.Y(mul_121_41_n_86));
   INVXL mul_121_41_g2039 (.A(mul_121_41_n_84),
	.Y(mul_121_41_n_83));
   NAND2XL mul_121_41_g2040__2802 (.A(mul_121_41_n_49),
	.B(mul_121_41_n_54),
	.Y(mul_121_41_n_84));
   NAND2XL mul_121_41_g2041__1705 (.A(mul_121_41_n_41),
	.B(mul_121_41_n_55),
	.Y(mul_121_41_n_82));
   NAND2XL mul_121_41_g2042__5122 (.A(mul_121_41_n_71),
	.B(mul_121_41_n_53),
	.Y(mul_121_41_n_81));
   INVX1 mul_121_41_g2043 (.A(mul_121_41_n_76),
	.Y(mul_121_41_n_77));
   INVXL mul_121_41_g2044 (.A(mul_121_41_n_72),
	.Y(mul_121_41_n_73));
   INVXL mul_121_41_g2045 (.A(mul_121_41_n_68),
	.Y(mul_121_41_n_69));
   INVXL mul_121_41_g2046 (.A(mul_121_41_n_66),
	.Y(mul_121_41_n_67));
   INVX1 mul_121_41_g2047 (.A(mul_121_41_n_63),
	.Y(mul_121_41_n_64));
   INVXL mul_121_41_g2048 (.A(mul_121_41_n_58),
	.Y(mul_121_41_n_59));
   CLKINVX1 mul_121_41_g2049 (.A(mul_121_41_n_56),
	.Y(mul_121_41_n_55));
   CLKINVX1 mul_121_41_g2050 (.A(mul_121_41_n_54),
	.Y(mul_121_41_n_53));
   AOI21XL mul_121_41_g2052__8246 (.A0(temp2_reg[6]),
	.A1(temp1_reg[0]),
	.B0(temp2_reg[5]),
	.Y(mul_121_41_n_51));
   AOI21XL mul_121_41_g2053__7098 (.A0(temp2_reg[4]),
	.A1(temp1_reg[0]),
	.B0(temp2_reg[3]),
	.Y(mul_121_41_n_50));
   MXI2XL mul_121_41_g2054__6131 (.A(mul_121_41_n_4),
	.B(temp2_reg[5]),
	.S0(temp2_reg[4]),
	.Y(mul_121_41_n_49));
   AOI21XL mul_121_41_g2055__1881 (.A0(temp2_reg[2]),
	.A1(temp1_reg[0]),
	.B0(temp2_reg[1]),
	.Y(mul_121_41_n_48));
   MXI2XL mul_121_41_g2057__5115 (.A(mul_121_41_n_1),
	.B(temp2_reg[3]),
	.S0(temp2_reg[2]),
	.Y(mul_121_41_n_46));
   MXI2XL mul_121_41_g2058__7482 (.A(temp1_reg[0]),
	.B(mul_121_41_n_5),
	.S0(temp2_reg[3]),
	.Y(mul_121_41_n_45));
   MXI2XL mul_121_41_g2059__4733 (.A(temp2_reg[5]),
	.B(mul_121_41_n_4),
	.S0(temp1_reg[5]),
	.Y(mul_121_41_n_80));
   MXI2XL mul_121_41_g2060__6161 (.A(mul_121_41_n_1),
	.B(temp2_reg[3]),
	.S0(temp1_reg[7]),
	.Y(mul_121_41_n_79));
   MXI2XL mul_121_41_g2061__9315 (.A(temp2_reg[5]),
	.B(mul_121_41_n_4),
	.S0(temp1_reg[4]),
	.Y(mul_121_41_n_78));
   MXI2XL mul_121_41_g2062__9945 (.A(mul_121_41_n_0),
	.B(temp2_reg[1]),
	.S0(temp1_reg[7]),
	.Y(mul_121_41_n_76));
   MXI2XL mul_121_41_g2063__2883 (.A(temp2_reg[5]),
	.B(mul_121_41_n_4),
	.S0(temp1_reg[7]),
	.Y(mul_121_41_n_75));
   NAND2XL mul_121_41_g2064__2346 (.A(temp2_reg[1]),
	.B(mul_121_41_n_8),
	.Y(mul_121_41_n_74));
   MXI2XL mul_121_41_g2065__1666 (.A(temp2_reg[1]),
	.B(mul_121_41_n_0),
	.S0(temp1_reg[8]),
	.Y(mul_121_41_n_72));
   MXI2XL mul_121_41_g2066__7410 (.A(mul_121_41_n_4),
	.B(temp2_reg[5]),
	.S0(temp1_reg[8]),
	.Y(mul_121_41_n_71));
   MXI2XL mul_121_41_g2067__6417 (.A(temp2_reg[3]),
	.B(mul_121_41_n_1),
	.S0(temp1_reg[2]),
	.Y(mul_121_41_n_70));
   MXI2XL mul_121_41_g2068__5477 (.A(temp2_reg[1]),
	.B(mul_121_41_n_0),
	.S0(temp1_reg[6]),
	.Y(mul_121_41_n_68));
   MXI2XL mul_121_41_g2069__2398 (.A(temp2_reg[1]),
	.B(mul_121_41_n_0),
	.S0(temp1_reg[4]),
	.Y(mul_121_41_n_66));
   MXI2XL mul_121_41_g2070__5107 (.A(temp2_reg[5]),
	.B(mul_121_41_n_4),
	.S0(temp1_reg[6]),
	.Y(mul_121_41_n_65));
   MXI2XL mul_121_41_g2071__6260 (.A(mul_121_41_n_0),
	.B(temp2_reg[1]),
	.S0(temp1_reg[1]),
	.Y(mul_121_41_n_63));
   MXI2XL mul_121_41_g2072__4319 (.A(mul_121_41_n_1),
	.B(temp2_reg[3]),
	.S0(temp1_reg[8]),
	.Y(mul_121_41_n_62));
   MXI2XL mul_121_41_g2073__8428 (.A(temp2_reg[5]),
	.B(mul_121_41_n_4),
	.S0(temp1_reg[2]),
	.Y(mul_121_41_n_61));
   MXI2XL mul_121_41_g2074__5526 (.A(temp2_reg[5]),
	.B(mul_121_41_n_4),
	.S0(temp1_reg[3]),
	.Y(mul_121_41_n_60));
   MXI2XL mul_121_41_g2075__6783 (.A(mul_121_41_n_0),
	.B(temp2_reg[1]),
	.S0(temp1_reg[3]),
	.Y(mul_121_41_n_58));
   AOI21X1 mul_121_41_g2076__3680 (.A0(mul_121_41_n_3),
	.A1(temp2_reg[7]),
	.B0(mul_121_41_n_7),
	.Y(mul_121_41_n_57));
   MX2X1 mul_121_41_g2077__1617 (.A(mul_121_41_n_4),
	.B(temp2_reg[5]),
	.S0(temp2_reg[6]),
	.Y(mul_121_41_n_56));
   MX2X1 mul_121_41_g2078__2802 (.A(mul_121_41_n_1),
	.B(temp2_reg[3]),
	.S0(temp2_reg[4]),
	.Y(mul_121_41_n_54));
   INVX1 mul_121_41_g2079 (.A(mul_121_41_n_34),
	.Y(mul_121_41_n_35));
   INVX1 mul_121_41_g2080 (.A(mul_121_41_n_31),
	.Y(mul_121_41_n_32));
   INVX1 mul_121_41_g2081 (.A(mul_121_41_n_26),
	.Y(mul_121_41_n_27));
   CLKINVX1 mul_121_41_g2082 (.A(mul_121_41_n_25),
	.Y(mul_121_41_n_24));
   MXI2XL mul_121_41_g2083__1705 (.A(temp2_reg[8]),
	.B(mul_121_41_n_3),
	.S0(temp1_reg[4]),
	.Y(mul_121_41_n_23));
   AOI22X1 mul_121_41_g2084__5122 (.A0(mul_121_41_n_4),
	.A1(temp1_reg[0]),
	.B0(mul_121_41_n_5),
	.B1(temp2_reg[5]),
	.Y(mul_121_41_n_22));
   MXI2XL mul_121_41_g2085__8246 (.A(temp2_reg[8]),
	.B(mul_121_41_n_3),
	.S0(temp1_reg[5]),
	.Y(mul_121_41_n_21));
   MXI2XL mul_121_41_g2086__7098 (.A(temp2_reg[8]),
	.B(mul_121_41_n_3),
	.S0(temp1_reg[3]),
	.Y(mul_121_41_n_20));
   MXI2XL mul_121_41_g2087__6131 (.A(temp2_reg[8]),
	.B(mul_121_41_n_3),
	.S0(temp1_reg[1]),
	.Y(mul_121_41_n_19));
   MXI2XL mul_121_41_g2088__1881 (.A(temp2_reg[8]),
	.B(mul_121_41_n_3),
	.S0(temp1_reg[2]),
	.Y(mul_121_41_n_18));
   MXI2XL mul_121_41_g2089__5115 (.A(mul_121_41_n_3),
	.B(temp2_reg[8]),
	.S0(temp1_reg[8]),
	.Y(mul_121_41_n_17));
   MXI2XL mul_121_41_g2090__7482 (.A(mul_121_41_n_3),
	.B(temp2_reg[8]),
	.S0(temp1_reg[6]),
	.Y(mul_121_41_n_16));
   MXI2XL mul_121_41_g2091__4733 (.A(temp2_reg[8]),
	.B(mul_121_41_n_3),
	.S0(temp1_reg[7]),
	.Y(mul_121_41_n_15));
   MXI2XL mul_121_41_g2092__6161 (.A(temp1_reg[0]),
	.B(mul_121_41_n_5),
	.S0(temp2_reg[7]),
	.Y(mul_121_41_n_14));
   MXI2XL mul_121_41_g2093__9315 (.A(mul_121_41_n_2),
	.B(temp2_reg[7]),
	.S0(temp2_reg[6]),
	.Y(mul_121_41_n_13));
   MXI2XL mul_121_41_g2094__9945 (.A(temp2_reg[7]),
	.B(mul_121_41_n_2),
	.S0(temp1_reg[1]),
	.Y(mul_121_41_n_44));
   MXI2XL mul_121_41_g2095__2883 (.A(temp2_reg[7]),
	.B(mul_121_41_n_2),
	.S0(temp1_reg[4]),
	.Y(mul_121_41_n_43));
   MXI2XL mul_121_41_g2096__2346 (.A(temp2_reg[7]),
	.B(mul_121_41_n_2),
	.S0(temp1_reg[3]),
	.Y(mul_121_41_n_42));
   MXI2XL mul_121_41_g2097__1666 (.A(mul_121_41_n_2),
	.B(temp2_reg[7]),
	.S0(temp1_reg[8]),
	.Y(mul_121_41_n_41));
   MXI2XL mul_121_41_g2098__7410 (.A(temp2_reg[7]),
	.B(mul_121_41_n_2),
	.S0(temp1_reg[2]),
	.Y(mul_121_41_n_40));
   MXI2XL mul_121_41_g2099__6417 (.A(temp2_reg[7]),
	.B(mul_121_41_n_2),
	.S0(temp1_reg[6]),
	.Y(mul_121_41_n_39));
   MXI2XL mul_121_41_g2100__5477 (.A(temp2_reg[7]),
	.B(mul_121_41_n_2),
	.S0(temp1_reg[7]),
	.Y(mul_121_41_n_38));
   MXI2XL mul_121_41_g2101__2398 (.A(temp2_reg[7]),
	.B(mul_121_41_n_2),
	.S0(temp1_reg[5]),
	.Y(mul_121_41_n_37));
   MXI2XL mul_121_41_g2102__5107 (.A(temp2_reg[3]),
	.B(mul_121_41_n_1),
	.S0(temp1_reg[4]),
	.Y(mul_121_41_n_36));
   MXI2XL mul_121_41_g2103__6260 (.A(mul_121_41_n_1),
	.B(temp2_reg[3]),
	.S0(temp1_reg[6]),
	.Y(mul_121_41_n_34));
   MXI2XL mul_121_41_g2104__4319 (.A(temp2_reg[3]),
	.B(mul_121_41_n_1),
	.S0(temp1_reg[1]),
	.Y(mul_121_41_n_33));
   MXI2XL mul_121_41_g2105__8428 (.A(temp2_reg[1]),
	.B(mul_121_41_n_0),
	.S0(temp1_reg[2]),
	.Y(mul_121_41_n_31));
   MXI2XL mul_121_41_g2106__5526 (.A(temp2_reg[5]),
	.B(mul_121_41_n_4),
	.S0(temp1_reg[1]),
	.Y(mul_121_41_n_30));
   MXI2XL mul_121_41_g2107__6783 (.A(temp2_reg[3]),
	.B(mul_121_41_n_1),
	.S0(temp1_reg[3]),
	.Y(mul_121_41_n_29));
   MXI2XL mul_121_41_g2108__3680 (.A(temp2_reg[3]),
	.B(mul_121_41_n_1),
	.S0(temp1_reg[5]),
	.Y(mul_121_41_n_28));
   MXI2XL mul_121_41_g2109__1617 (.A(temp2_reg[1]),
	.B(mul_121_41_n_0),
	.S0(temp1_reg[5]),
	.Y(mul_121_41_n_26));
   MX2X1 mul_121_41_g2110__2802 (.A(mul_121_41_n_0),
	.B(temp2_reg[1]),
	.S0(temp2_reg[2]),
	.Y(mul_121_41_n_25));
   NOR2XL mul_121_41_g2111__1705 (.A(temp2_reg[6]),
	.B(temp1_reg[0]),
	.Y(mul_121_41_n_12));
   NOR2XL mul_121_41_g2112__5122 (.A(temp2_reg[2]),
	.B(temp1_reg[0]),
	.Y(mul_121_41_n_11));
   NOR2XL mul_121_41_g2113__8246 (.A(temp2_reg[4]),
	.B(temp1_reg[0]),
	.Y(mul_121_41_n_10));
   INVXL mul_121_41_g2114 (.A(mul_121_41_n_8),
	.Y(mul_out[0]));
   NAND2XL mul_121_41_g2115__7098 (.A(temp1_reg[0]),
	.B(temp2_reg[0]),
	.Y(mul_121_41_n_8));
   NOR2XL mul_121_41_g2116__6131 (.A(mul_121_41_n_3),
	.B(temp2_reg[7]),
	.Y(mul_121_41_n_7));
   CLKINVX1 mul_121_41_g2117 (.A(temp2_reg[0]),
	.Y(mul_121_41_n_6));
   CLKINVX1 mul_121_41_g2118 (.A(temp1_reg[0]),
	.Y(mul_121_41_n_5));
   CLKINVX1 mul_121_41_g2119 (.A(temp2_reg[5]),
	.Y(mul_121_41_n_4));
   CLKINVX1 mul_121_41_g2120 (.A(temp2_reg[8]),
	.Y(mul_121_41_n_3));
   CLKINVX1 mul_121_41_g2121 (.A(temp2_reg[7]),
	.Y(mul_121_41_n_2));
   CLKINVX1 mul_121_41_g2122 (.A(temp2_reg[3]),
	.Y(mul_121_41_n_1));
   CLKINVX1 mul_121_41_g2123 (.A(temp2_reg[1]),
	.Y(mul_121_41_n_0));
endmodule

