
//input ports
add mapped point clk clk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point addr_a[2] addr_a[2] -type PI PI
add mapped point addr_a[1] addr_a[1] -type PI PI
add mapped point addr_a[0] addr_a[0] -type PI PI
add mapped point addr_b[2] addr_b[2] -type PI PI
add mapped point addr_b[1] addr_b[1] -type PI PI
add mapped point addr_b[0] addr_b[0] -type PI PI
add mapped point we_w we_w -type PI PI
add mapped point addr_w[2] addr_w[2] -type PI PI
add mapped point addr_w[1] addr_w[1] -type PI PI
add mapped point addr_w[0] addr_w[0] -type PI PI
add mapped point data_w[31] data_w[31] -type PI PI
add mapped point data_w[30] data_w[30] -type PI PI
add mapped point data_w[29] data_w[29] -type PI PI
add mapped point data_w[28] data_w[28] -type PI PI
add mapped point data_w[27] data_w[27] -type PI PI
add mapped point data_w[26] data_w[26] -type PI PI
add mapped point data_w[25] data_w[25] -type PI PI
add mapped point data_w[24] data_w[24] -type PI PI
add mapped point data_w[23] data_w[23] -type PI PI
add mapped point data_w[22] data_w[22] -type PI PI
add mapped point data_w[21] data_w[21] -type PI PI
add mapped point data_w[20] data_w[20] -type PI PI
add mapped point data_w[19] data_w[19] -type PI PI
add mapped point data_w[18] data_w[18] -type PI PI
add mapped point data_w[17] data_w[17] -type PI PI
add mapped point data_w[16] data_w[16] -type PI PI
add mapped point data_w[15] data_w[15] -type PI PI
add mapped point data_w[14] data_w[14] -type PI PI
add mapped point data_w[13] data_w[13] -type PI PI
add mapped point data_w[12] data_w[12] -type PI PI
add mapped point data_w[11] data_w[11] -type PI PI
add mapped point data_w[10] data_w[10] -type PI PI
add mapped point data_w[9] data_w[9] -type PI PI
add mapped point data_w[8] data_w[8] -type PI PI
add mapped point data_w[7] data_w[7] -type PI PI
add mapped point data_w[6] data_w[6] -type PI PI
add mapped point data_w[5] data_w[5] -type PI PI
add mapped point data_w[4] data_w[4] -type PI PI
add mapped point data_w[3] data_w[3] -type PI PI
add mapped point data_w[2] data_w[2] -type PI PI
add mapped point data_w[1] data_w[1] -type PI PI
add mapped point data_w[0] data_w[0] -type PI PI

//output ports
add mapped point data_a[31] data_a[31] -type PO PO
add mapped point data_a[30] data_a[30] -type PO PO
add mapped point data_a[29] data_a[29] -type PO PO
add mapped point data_a[28] data_a[28] -type PO PO
add mapped point data_a[27] data_a[27] -type PO PO
add mapped point data_a[26] data_a[26] -type PO PO
add mapped point data_a[25] data_a[25] -type PO PO
add mapped point data_a[24] data_a[24] -type PO PO
add mapped point data_a[23] data_a[23] -type PO PO
add mapped point data_a[22] data_a[22] -type PO PO
add mapped point data_a[21] data_a[21] -type PO PO
add mapped point data_a[20] data_a[20] -type PO PO
add mapped point data_a[19] data_a[19] -type PO PO
add mapped point data_a[18] data_a[18] -type PO PO
add mapped point data_a[17] data_a[17] -type PO PO
add mapped point data_a[16] data_a[16] -type PO PO
add mapped point data_a[15] data_a[15] -type PO PO
add mapped point data_a[14] data_a[14] -type PO PO
add mapped point data_a[13] data_a[13] -type PO PO
add mapped point data_a[12] data_a[12] -type PO PO
add mapped point data_a[11] data_a[11] -type PO PO
add mapped point data_a[10] data_a[10] -type PO PO
add mapped point data_a[9] data_a[9] -type PO PO
add mapped point data_a[8] data_a[8] -type PO PO
add mapped point data_a[7] data_a[7] -type PO PO
add mapped point data_a[6] data_a[6] -type PO PO
add mapped point data_a[5] data_a[5] -type PO PO
add mapped point data_a[4] data_a[4] -type PO PO
add mapped point data_a[3] data_a[3] -type PO PO
add mapped point data_a[2] data_a[2] -type PO PO
add mapped point data_a[1] data_a[1] -type PO PO
add mapped point data_a[0] data_a[0] -type PO PO
add mapped point data_b[31] data_b[31] -type PO PO
add mapped point data_b[30] data_b[30] -type PO PO
add mapped point data_b[29] data_b[29] -type PO PO
add mapped point data_b[28] data_b[28] -type PO PO
add mapped point data_b[27] data_b[27] -type PO PO
add mapped point data_b[26] data_b[26] -type PO PO
add mapped point data_b[25] data_b[25] -type PO PO
add mapped point data_b[24] data_b[24] -type PO PO
add mapped point data_b[23] data_b[23] -type PO PO
add mapped point data_b[22] data_b[22] -type PO PO
add mapped point data_b[21] data_b[21] -type PO PO
add mapped point data_b[20] data_b[20] -type PO PO
add mapped point data_b[19] data_b[19] -type PO PO
add mapped point data_b[18] data_b[18] -type PO PO
add mapped point data_b[17] data_b[17] -type PO PO
add mapped point data_b[16] data_b[16] -type PO PO
add mapped point data_b[15] data_b[15] -type PO PO
add mapped point data_b[14] data_b[14] -type PO PO
add mapped point data_b[13] data_b[13] -type PO PO
add mapped point data_b[12] data_b[12] -type PO PO
add mapped point data_b[11] data_b[11] -type PO PO
add mapped point data_b[10] data_b[10] -type PO PO
add mapped point data_b[9] data_b[9] -type PO PO
add mapped point data_b[8] data_b[8] -type PO PO
add mapped point data_b[7] data_b[7] -type PO PO
add mapped point data_b[6] data_b[6] -type PO PO
add mapped point data_b[5] data_b[5] -type PO PO
add mapped point data_b[4] data_b[4] -type PO PO
add mapped point data_b[3] data_b[3] -type PO PO
add mapped point data_b[2] data_b[2] -type PO PO
add mapped point data_b[1] data_b[1] -type PO PO
add mapped point data_b[0] data_b[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point registers[5][9]/q registers_reg[5][9]/Q -type DFF DFF
add mapped point registers[5][29]/q registers_reg[5][29]/Q -type DFF DFF
add mapped point registers[5][30]/q registers_reg[5][30]/Q -type DFF DFF
add mapped point registers[5][31]/q registers_reg[5][31]/Q -type DFF DFF
add mapped point registers[5][27]/q registers_reg[5][27]/Q -type DFF DFF
add mapped point registers[5][26]/q registers_reg[5][26]/Q -type DFF DFF
add mapped point registers[5][0]/q registers_reg[5][0]/Q -type DFF DFF
add mapped point registers[5][1]/q registers_reg[5][1]/Q -type DFF DFF
add mapped point registers[5][2]/q registers_reg[5][2]/Q -type DFF DFF
add mapped point registers[5][3]/q registers_reg[5][3]/Q -type DFF DFF
add mapped point registers[5][4]/q registers_reg[5][4]/Q -type DFF DFF
add mapped point registers[5][5]/q registers_reg[5][5]/Q -type DFF DFF
add mapped point registers[5][6]/q registers_reg[5][6]/Q -type DFF DFF
add mapped point registers[5][7]/q registers_reg[5][7]/Q -type DFF DFF
add mapped point registers[5][8]/q registers_reg[5][8]/Q -type DFF DFF
add mapped point registers[5][28]/q registers_reg[5][28]/Q -type DFF DFF
add mapped point registers[5][25]/q registers_reg[5][25]/Q -type DFF DFF
add mapped point registers[5][11]/q registers_reg[5][11]/Q -type DFF DFF
add mapped point registers[5][12]/q registers_reg[5][12]/Q -type DFF DFF
add mapped point registers[5][13]/q registers_reg[5][13]/Q -type DFF DFF
add mapped point registers[5][14]/q registers_reg[5][14]/Q -type DFF DFF
add mapped point registers[5][15]/q registers_reg[5][15]/Q -type DFF DFF
add mapped point registers[5][16]/q registers_reg[5][16]/Q -type DFF DFF
add mapped point registers[5][17]/q registers_reg[5][17]/Q -type DFF DFF
add mapped point registers[5][18]/q registers_reg[5][18]/Q -type DFF DFF
add mapped point registers[5][19]/q registers_reg[5][19]/Q -type DFF DFF
add mapped point registers[5][20]/q registers_reg[5][20]/Q -type DFF DFF
add mapped point registers[5][21]/q registers_reg[5][21]/Q -type DFF DFF
add mapped point registers[5][22]/q registers_reg[5][22]/Q -type DFF DFF
add mapped point registers[5][23]/q registers_reg[5][23]/Q -type DFF DFF
add mapped point registers[5][24]/q registers_reg[5][24]/Q -type DFF DFF
add mapped point registers[5][10]/q registers_reg[5][10]/Q -type DFF DFF
add mapped point registers[1][16]/q registers_reg[1][16]/Q -type DFF DFF
add mapped point registers[6][0]/q registers_reg[6][0]/Q -type DFF DFF
add mapped point registers[6][1]/q registers_reg[6][1]/Q -type DFF DFF
add mapped point registers[6][2]/q registers_reg[6][2]/Q -type DFF DFF
add mapped point registers[6][3]/q registers_reg[6][3]/Q -type DFF DFF
add mapped point registers[6][4]/q registers_reg[6][4]/Q -type DFF DFF
add mapped point registers[6][5]/q registers_reg[6][5]/Q -type DFF DFF
add mapped point registers[6][6]/q registers_reg[6][6]/Q -type DFF DFF
add mapped point registers[6][7]/q registers_reg[6][7]/Q -type DFF DFF
add mapped point registers[6][8]/q registers_reg[6][8]/Q -type DFF DFF
add mapped point registers[6][9]/q registers_reg[6][9]/Q -type DFF DFF
add mapped point registers[6][10]/q registers_reg[6][10]/Q -type DFF DFF
add mapped point registers[6][11]/q registers_reg[6][11]/Q -type DFF DFF
add mapped point registers[6][12]/q registers_reg[6][12]/Q -type DFF DFF
add mapped point registers[6][13]/q registers_reg[6][13]/Q -type DFF DFF
add mapped point registers[6][14]/q registers_reg[6][14]/Q -type DFF DFF
add mapped point registers[6][15]/q registers_reg[6][15]/Q -type DFF DFF
add mapped point registers[6][16]/q registers_reg[6][16]/Q -type DFF DFF
add mapped point registers[6][17]/q registers_reg[6][17]/Q -type DFF DFF
add mapped point registers[6][18]/q registers_reg[6][18]/Q -type DFF DFF
add mapped point registers[6][19]/q registers_reg[6][19]/Q -type DFF DFF
add mapped point registers[6][20]/q registers_reg[6][20]/Q -type DFF DFF
add mapped point registers[6][21]/q registers_reg[6][21]/Q -type DFF DFF
add mapped point registers[6][22]/q registers_reg[6][22]/Q -type DFF DFF
add mapped point registers[6][23]/q registers_reg[6][23]/Q -type DFF DFF
add mapped point registers[6][24]/q registers_reg[6][24]/Q -type DFF DFF
add mapped point registers[6][25]/q registers_reg[6][25]/Q -type DFF DFF
add mapped point registers[6][26]/q registers_reg[6][26]/Q -type DFF DFF
add mapped point registers[6][27]/q registers_reg[6][27]/Q -type DFF DFF
add mapped point registers[6][28]/q registers_reg[6][28]/Q -type DFF DFF
add mapped point registers[6][29]/q registers_reg[6][29]/Q -type DFF DFF
add mapped point registers[6][30]/q registers_reg[6][30]/Q -type DFF DFF
add mapped point registers[6][31]/q registers_reg[6][31]/Q -type DFF DFF
add mapped point registers[7][0]/q registers_reg[7][0]/Q -type DFF DFF
add mapped point registers[7][1]/q registers_reg[7][1]/Q -type DFF DFF
add mapped point registers[7][2]/q registers_reg[7][2]/Q -type DFF DFF
add mapped point registers[7][3]/q registers_reg[7][3]/Q -type DFF DFF
add mapped point registers[7][4]/q registers_reg[7][4]/Q -type DFF DFF
add mapped point registers[7][5]/q registers_reg[7][5]/Q -type DFF DFF
add mapped point registers[7][6]/q registers_reg[7][6]/Q -type DFF DFF
add mapped point registers[7][7]/q registers_reg[7][7]/Q -type DFF DFF
add mapped point registers[7][8]/q registers_reg[7][8]/Q -type DFF DFF
add mapped point registers[7][9]/q registers_reg[7][9]/Q -type DFF DFF
add mapped point registers[7][10]/q registers_reg[7][10]/Q -type DFF DFF
add mapped point registers[7][11]/q registers_reg[7][11]/Q -type DFF DFF
add mapped point registers[7][12]/q registers_reg[7][12]/Q -type DFF DFF
add mapped point registers[7][13]/q registers_reg[7][13]/Q -type DFF DFF
add mapped point registers[7][14]/q registers_reg[7][14]/Q -type DFF DFF
add mapped point registers[7][15]/q registers_reg[7][15]/Q -type DFF DFF
add mapped point registers[7][16]/q registers_reg[7][16]/Q -type DFF DFF
add mapped point registers[7][17]/q registers_reg[7][17]/Q -type DFF DFF
add mapped point registers[7][18]/q registers_reg[7][18]/Q -type DFF DFF
add mapped point registers[7][19]/q registers_reg[7][19]/Q -type DFF DFF
add mapped point registers[7][20]/q registers_reg[7][20]/Q -type DFF DFF
add mapped point registers[7][21]/q registers_reg[7][21]/Q -type DFF DFF
add mapped point registers[7][22]/q registers_reg[7][22]/Q -type DFF DFF
add mapped point registers[7][23]/q registers_reg[7][23]/Q -type DFF DFF
add mapped point registers[7][24]/q registers_reg[7][24]/Q -type DFF DFF
add mapped point registers[7][25]/q registers_reg[7][25]/Q -type DFF DFF
add mapped point registers[7][26]/q registers_reg[7][26]/Q -type DFF DFF
add mapped point registers[7][27]/q registers_reg[7][27]/Q -type DFF DFF
add mapped point registers[7][28]/q registers_reg[7][28]/Q -type DFF DFF
add mapped point registers[7][29]/q registers_reg[7][29]/Q -type DFF DFF
add mapped point registers[7][30]/q registers_reg[7][30]/Q -type DFF DFF
add mapped point registers[7][31]/q registers_reg[7][31]/Q -type DFF DFF
add mapped point registers[0][0]/q registers_reg[0][0]/Q -type DFF DFF
add mapped point registers[0][1]/q registers_reg[0][1]/Q -type DFF DFF
add mapped point registers[0][2]/q registers_reg[0][2]/Q -type DFF DFF
add mapped point registers[0][3]/q registers_reg[0][3]/Q -type DFF DFF
add mapped point registers[0][4]/q registers_reg[0][4]/Q -type DFF DFF
add mapped point registers[0][5]/q registers_reg[0][5]/Q -type DFF DFF
add mapped point registers[0][6]/q registers_reg[0][6]/Q -type DFF DFF
add mapped point registers[0][7]/q registers_reg[0][7]/Q -type DFF DFF
add mapped point registers[0][8]/q registers_reg[0][8]/Q -type DFF DFF
add mapped point registers[0][9]/q registers_reg[0][9]/Q -type DFF DFF
add mapped point registers[0][10]/q registers_reg[0][10]/Q -type DFF DFF
add mapped point registers[0][11]/q registers_reg[0][11]/Q -type DFF DFF
add mapped point registers[0][12]/q registers_reg[0][12]/Q -type DFF DFF
add mapped point registers[0][13]/q registers_reg[0][13]/Q -type DFF DFF
add mapped point registers[0][14]/q registers_reg[0][14]/Q -type DFF DFF
add mapped point registers[0][15]/q registers_reg[0][15]/Q -type DFF DFF
add mapped point registers[0][16]/q registers_reg[0][16]/Q -type DFF DFF
add mapped point registers[0][17]/q registers_reg[0][17]/Q -type DFF DFF
add mapped point registers[0][18]/q registers_reg[0][18]/Q -type DFF DFF
add mapped point registers[0][19]/q registers_reg[0][19]/Q -type DFF DFF
add mapped point registers[0][20]/q registers_reg[0][20]/Q -type DFF DFF
add mapped point registers[0][21]/q registers_reg[0][21]/Q -type DFF DFF
add mapped point registers[0][22]/q registers_reg[0][22]/Q -type DFF DFF
add mapped point registers[0][25]/q registers_reg[0][25]/Q -type DFF DFF
add mapped point registers[0][26]/q registers_reg[0][26]/Q -type DFF DFF
add mapped point registers[0][27]/q registers_reg[0][27]/Q -type DFF DFF
add mapped point registers[0][28]/q registers_reg[0][28]/Q -type DFF DFF
add mapped point registers[0][29]/q registers_reg[0][29]/Q -type DFF DFF
add mapped point registers[0][30]/q registers_reg[0][30]/Q -type DFF DFF
add mapped point registers[0][31]/q registers_reg[0][31]/Q -type DFF DFF
add mapped point registers[1][0]/q registers_reg[1][0]/Q -type DFF DFF
add mapped point registers[1][1]/q registers_reg[1][1]/Q -type DFF DFF
add mapped point registers[1][2]/q registers_reg[1][2]/Q -type DFF DFF
add mapped point registers[1][3]/q registers_reg[1][3]/Q -type DFF DFF
add mapped point registers[1][4]/q registers_reg[1][4]/Q -type DFF DFF
add mapped point registers[1][5]/q registers_reg[1][5]/Q -type DFF DFF
add mapped point registers[1][6]/q registers_reg[1][6]/Q -type DFF DFF
add mapped point registers[1][7]/q registers_reg[1][7]/Q -type DFF DFF
add mapped point registers[1][8]/q registers_reg[1][8]/Q -type DFF DFF
add mapped point registers[1][9]/q registers_reg[1][9]/Q -type DFF DFF
add mapped point registers[1][10]/q registers_reg[1][10]/Q -type DFF DFF
add mapped point registers[1][11]/q registers_reg[1][11]/Q -type DFF DFF
add mapped point registers[1][12]/q registers_reg[1][12]/Q -type DFF DFF
add mapped point registers[1][13]/q registers_reg[1][13]/Q -type DFF DFF
add mapped point registers[1][14]/q registers_reg[1][14]/Q -type DFF DFF
add mapped point registers[1][15]/q registers_reg[1][15]/Q -type DFF DFF
add mapped point registers[1][26]/q registers_reg[1][26]/Q -type DFF DFF
add mapped point registers[1][27]/q registers_reg[1][27]/Q -type DFF DFF
add mapped point registers[1][18]/q registers_reg[1][18]/Q -type DFF DFF
add mapped point registers[1][19]/q registers_reg[1][19]/Q -type DFF DFF
add mapped point registers[1][20]/q registers_reg[1][20]/Q -type DFF DFF
add mapped point registers[1][21]/q registers_reg[1][21]/Q -type DFF DFF
add mapped point registers[0][23]/q registers_reg[0][23]/Q -type DFF DFF
add mapped point registers[0][24]/q registers_reg[0][24]/Q -type DFF DFF
add mapped point registers[1][22]/q registers_reg[1][22]/Q -type DFF DFF
add mapped point registers[1][25]/q registers_reg[1][25]/Q -type DFF DFF
add mapped point registers[1][23]/q registers_reg[1][23]/Q -type DFF DFF
add mapped point registers[1][24]/q registers_reg[1][24]/Q -type DFF DFF
add mapped point registers[1][28]/q registers_reg[1][28]/Q -type DFF DFF
add mapped point registers[1][29]/q registers_reg[1][29]/Q -type DFF DFF
add mapped point registers[1][30]/q registers_reg[1][30]/Q -type DFF DFF
add mapped point registers[1][31]/q registers_reg[1][31]/Q -type DFF DFF
add mapped point registers[2][0]/q registers_reg[2][0]/Q -type DFF DFF
add mapped point registers[2][1]/q registers_reg[2][1]/Q -type DFF DFF
add mapped point registers[2][2]/q registers_reg[2][2]/Q -type DFF DFF
add mapped point registers[2][3]/q registers_reg[2][3]/Q -type DFF DFF
add mapped point registers[2][4]/q registers_reg[2][4]/Q -type DFF DFF
add mapped point registers[2][5]/q registers_reg[2][5]/Q -type DFF DFF
add mapped point registers[2][6]/q registers_reg[2][6]/Q -type DFF DFF
add mapped point registers[2][7]/q registers_reg[2][7]/Q -type DFF DFF
add mapped point registers[2][8]/q registers_reg[2][8]/Q -type DFF DFF
add mapped point registers[2][9]/q registers_reg[2][9]/Q -type DFF DFF
add mapped point registers[2][10]/q registers_reg[2][10]/Q -type DFF DFF
add mapped point registers[2][11]/q registers_reg[2][11]/Q -type DFF DFF
add mapped point registers[2][12]/q registers_reg[2][12]/Q -type DFF DFF
add mapped point registers[2][13]/q registers_reg[2][13]/Q -type DFF DFF
add mapped point registers[2][14]/q registers_reg[2][14]/Q -type DFF DFF
add mapped point registers[2][15]/q registers_reg[2][15]/Q -type DFF DFF
add mapped point registers[2][16]/q registers_reg[2][16]/Q -type DFF DFF
add mapped point registers[2][17]/q registers_reg[2][17]/Q -type DFF DFF
add mapped point registers[2][18]/q registers_reg[2][18]/Q -type DFF DFF
add mapped point registers[2][19]/q registers_reg[2][19]/Q -type DFF DFF
add mapped point registers[2][20]/q registers_reg[2][20]/Q -type DFF DFF
add mapped point registers[2][21]/q registers_reg[2][21]/Q -type DFF DFF
add mapped point registers[2][22]/q registers_reg[2][22]/Q -type DFF DFF
add mapped point registers[2][23]/q registers_reg[2][23]/Q -type DFF DFF
add mapped point registers[2][24]/q registers_reg[2][24]/Q -type DFF DFF
add mapped point registers[2][25]/q registers_reg[2][25]/Q -type DFF DFF
add mapped point registers[2][26]/q registers_reg[2][26]/Q -type DFF DFF
add mapped point registers[2][27]/q registers_reg[2][27]/Q -type DFF DFF
add mapped point registers[2][28]/q registers_reg[2][28]/Q -type DFF DFF
add mapped point registers[2][29]/q registers_reg[2][29]/Q -type DFF DFF
add mapped point registers[2][30]/q registers_reg[2][30]/Q -type DFF DFF
add mapped point registers[2][31]/q registers_reg[2][31]/Q -type DFF DFF
add mapped point registers[3][0]/q registers_reg[3][0]/Q -type DFF DFF
add mapped point registers[3][1]/q registers_reg[3][1]/Q -type DFF DFF
add mapped point registers[3][2]/q registers_reg[3][2]/Q -type DFF DFF
add mapped point registers[3][3]/q registers_reg[3][3]/Q -type DFF DFF
add mapped point registers[3][4]/q registers_reg[3][4]/Q -type DFF DFF
add mapped point registers[3][5]/q registers_reg[3][5]/Q -type DFF DFF
add mapped point registers[3][6]/q registers_reg[3][6]/Q -type DFF DFF
add mapped point registers[3][7]/q registers_reg[3][7]/Q -type DFF DFF
add mapped point registers[3][8]/q registers_reg[3][8]/Q -type DFF DFF
add mapped point registers[3][9]/q registers_reg[3][9]/Q -type DFF DFF
add mapped point registers[3][10]/q registers_reg[3][10]/Q -type DFF DFF
add mapped point registers[3][11]/q registers_reg[3][11]/Q -type DFF DFF
add mapped point registers[3][12]/q registers_reg[3][12]/Q -type DFF DFF
add mapped point registers[3][13]/q registers_reg[3][13]/Q -type DFF DFF
add mapped point registers[3][14]/q registers_reg[3][14]/Q -type DFF DFF
add mapped point registers[3][15]/q registers_reg[3][15]/Q -type DFF DFF
add mapped point registers[3][16]/q registers_reg[3][16]/Q -type DFF DFF
add mapped point registers[3][17]/q registers_reg[3][17]/Q -type DFF DFF
add mapped point registers[3][18]/q registers_reg[3][18]/Q -type DFF DFF
add mapped point registers[3][19]/q registers_reg[3][19]/Q -type DFF DFF
add mapped point registers[3][20]/q registers_reg[3][20]/Q -type DFF DFF
add mapped point registers[3][21]/q registers_reg[3][21]/Q -type DFF DFF
add mapped point registers[3][22]/q registers_reg[3][22]/Q -type DFF DFF
add mapped point registers[4][23]/q registers_reg[4][23]/Q -type DFF DFF
add mapped point registers[3][23]/q registers_reg[3][23]/Q -type DFF DFF
add mapped point registers[3][24]/q registers_reg[3][24]/Q -type DFF DFF
add mapped point registers[3][25]/q registers_reg[3][25]/Q -type DFF DFF
add mapped point registers[3][26]/q registers_reg[3][26]/Q -type DFF DFF
add mapped point registers[3][27]/q registers_reg[3][27]/Q -type DFF DFF
add mapped point registers[3][28]/q registers_reg[3][28]/Q -type DFF DFF
add mapped point registers[3][29]/q registers_reg[3][29]/Q -type DFF DFF
add mapped point registers[3][30]/q registers_reg[3][30]/Q -type DFF DFF
add mapped point registers[3][31]/q registers_reg[3][31]/Q -type DFF DFF
add mapped point registers[4][0]/q registers_reg[4][0]/Q -type DFF DFF
add mapped point registers[4][1]/q registers_reg[4][1]/Q -type DFF DFF
add mapped point registers[4][2]/q registers_reg[4][2]/Q -type DFF DFF
add mapped point registers[4][3]/q registers_reg[4][3]/Q -type DFF DFF
add mapped point registers[4][4]/q registers_reg[4][4]/Q -type DFF DFF
add mapped point registers[4][5]/q registers_reg[4][5]/Q -type DFF DFF
add mapped point registers[4][21]/q registers_reg[4][21]/Q -type DFF DFF
add mapped point registers[4][6]/q registers_reg[4][6]/Q -type DFF DFF
add mapped point registers[4][7]/q registers_reg[4][7]/Q -type DFF DFF
add mapped point registers[4][8]/q registers_reg[4][8]/Q -type DFF DFF
add mapped point registers[4][9]/q registers_reg[4][9]/Q -type DFF DFF
add mapped point registers[4][10]/q registers_reg[4][10]/Q -type DFF DFF
add mapped point registers[4][11]/q registers_reg[4][11]/Q -type DFF DFF
add mapped point registers[4][12]/q registers_reg[4][12]/Q -type DFF DFF
add mapped point registers[4][13]/q registers_reg[4][13]/Q -type DFF DFF
add mapped point registers[4][14]/q registers_reg[4][14]/Q -type DFF DFF
add mapped point registers[4][15]/q registers_reg[4][15]/Q -type DFF DFF
add mapped point registers[4][16]/q registers_reg[4][16]/Q -type DFF DFF
add mapped point registers[4][17]/q registers_reg[4][17]/Q -type DFF DFF
add mapped point registers[4][18]/q registers_reg[4][18]/Q -type DFF DFF
add mapped point registers[4][19]/q registers_reg[4][19]/Q -type DFF DFF
add mapped point registers[4][20]/q registers_reg[4][20]/Q -type DFF DFF
add mapped point registers[4][26]/q registers_reg[4][26]/Q -type DFF DFF
add mapped point registers[4][27]/q registers_reg[4][27]/Q -type DFF DFF
add mapped point registers[4][28]/q registers_reg[4][28]/Q -type DFF DFF
add mapped point registers[4][29]/q registers_reg[4][29]/Q -type DFF DFF
add mapped point registers[4][25]/q registers_reg[4][25]/Q -type DFF DFF
add mapped point registers[4][30]/q registers_reg[4][30]/Q -type DFF DFF
add mapped point registers[4][31]/q registers_reg[4][31]/Q -type DFF DFF
add mapped point registers[4][24]/q registers_reg[4][24]/Q -type DFF DFF
add mapped point registers[4][22]/q registers_reg[4][22]/Q -type DFF DFF
add mapped point registers[1][17]/q registers_reg[1][17]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
