# ####################################################################

#  Created by Genus(TM) Synthesis Solution 21.14-s082_1 on Tue Nov 04 18:06:01 IST 2025

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design register_file

create_clock -name "clk" -period 10.0 -waveform {0.0 5.0} [get_ports clk]
set_clock_transition 0.1 [get_clocks clk]
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports rst_n]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports we_w]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {addr_a[2]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {addr_a[1]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {addr_a[0]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {addr_b[2]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {addr_b[1]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {addr_b[0]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {addr_w[2]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {addr_w[1]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {addr_w[0]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[31]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[30]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[29]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[28]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[27]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[26]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[25]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[24]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[23]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[22]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[21]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[20]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[19]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[18]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[17]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[16]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[15]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[14]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[13]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[12]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[11]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[10]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[9]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[8]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[7]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[6]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[5]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[4]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[3]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[2]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[1]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_w[0]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[31]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[30]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[29]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[28]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[27]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[26]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[25]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[24]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[23]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[22]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[21]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[20]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[19]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[18]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[17]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[16]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[15]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[14]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[13]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[12]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[11]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[10]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[9]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[8]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[7]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[6]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[5]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[4]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[3]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[2]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[1]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_a[0]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[31]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[30]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[29]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[28]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[27]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[26]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[25]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[24]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[23]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[22]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[21]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[20]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[19]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[18]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[17]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[16]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[15]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[14]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[13]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[12]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[11]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[10]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[9]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[8]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[7]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[6]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[5]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[4]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[3]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[2]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[1]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {data_b[0]}]
set_wire_load_mode "enclosed"
set_clock_uncertainty -setup 0.01 [get_ports clk]
set_clock_uncertainty -hold 0.01 [get_ports clk]
