###############################################################
#  Generated by:      Cadence  
#  OS:                Linux x86_64(Host ID ic312.vit.ac.in)
#  Generated on:      Tue Nov  4 18:09:15 2025
###############################################################

################################################
#  Preference File                             #
################################################

set ::uiHalo::sch::sgnColor(Text_-_Pin_Name/Signal_Value) #ffff00
set ::uiHalo::sch::sgnWidth(Text_-_Pin_Name/Signal_Value) 1
set ::uiHalo::sch::sgnStyle(Text_-_Pin_Name/Signal_Value) 0
set ::uiHalo::sch::sgnColor(Traced_Load_Object) #ff0000
set ::uiHalo::sch::sgnWidth(Traced_Load_Object) 1
set ::uiHalo::sch::sgnStyle(Traced_Load_Object) 0
set ::uiHalo::sch::sgnColor(Cursor_Object) #00ffff
set ::uiHalo::sch::sgnWidth(Cursor_Object) 1
set ::uiHalo::sch::sgnStyle(Cursor_Object) 1
set ::uiHalo::sch::sgnColor(Background) #ffffff
set ::uiHalo::sch::sgnWidth(Background) 1
set ::uiHalo::sch::sgnStyle(Background) 0
set ::uiHalo::sch::sgnColor(Text) #00ffff
set ::uiHalo::sch::sgnWidth(Text) 1
set ::uiHalo::sch::sgnStyle(Text) 0
set ::uiHalo::sch::sgnColor(Instance) #ffa07a
set ::uiHalo::sch::sgnWidth(Instance) 1
set ::uiHalo::sch::sgnStyle(Instance) 0
set ::uiHalo::sch::sgnColor(Traced_Drive_Object) #ffff00
set ::uiHalo::sch::sgnWidth(Traced_Drive_Object) 1
set ::uiHalo::sch::sgnStyle(Traced_Drive_Object) 0
set ::uiHalo::sch::sgnColor(Module_Port) #ffa07a
set ::uiHalo::sch::sgnWidth(Module_Port) 1
set ::uiHalo::sch::sgnStyle(Module_Port) 0
set ::uiHalo::sch::sgnColor(Bus) #c1ffc1
set ::uiHalo::sch::sgnWidth(Bus) 1
set ::uiHalo::sch::sgnStyle(Bus) 0
set ::uiHalo::sch::sgnColor(Net) #c1ffc1
set ::uiHalo::sch::sgnWidth(Net) 1
set ::uiHalo::sch::sgnStyle(Net) 0
set ::uiHalo::sch::sgnFontFamily courier
set ::uiHalo::sch::sgnFontSize 14
set ::uiHalo::sch::sgnFontBold 0
set ::uiHalo::sch::sgnFontItalic 0
set ::uiHalo::sch::sgnDisplay(primitive) 1
set ::uiHalo::sch::sgnDisplay(cross) 1
set ::uiHalo::sch::sgnDisplay(port) 1
set ::uiHalo::sch::sgnDisplay(instance) 0
set ::uiHalo::sch::sgnDisplay(infobox) 1
set ::uiHalo::sch::sgnDisplay(pan) 20
set ::uiHalo::sch::sgnDisplay(highlight) 1
set ::uiHalo::sch::sgnDisplay(module) 1
set ::uiHalo::sch::sgnDisplay(autozoom) 0
set ::uiHalo::sch::sgnDisplay(pin) 0
set ::uiHalo::sch::sgnDisplay(net) 0
set ::uiHalo::sch::sgnDisplay(bitindex) 0
::uiHalo::sch::source_file
